// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AssetEdgesColumns holds the columns for the "asset_edges" table.
	AssetEdgesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "from_asset", Type: field.TypeString, Size: 256},
		{Name: "to_asset", Type: field.TypeString, Size: 256},
		{Name: "code_hash_first", Type: field.TypeString, Size: 64},
		{Name: "code_hash_latest", Type: field.TypeString, Size: 64},
		{Name: "first_seen_run_id", Type: field.TypeUUID},
		{Name: "first_seen_at", Type: field.TypeTime},
		{Name: "last_seen_run_id", Type: field.TypeUUID},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "superseded_at", Type: field.TypeTime, Nullable: true},
	}
	// AssetEdgesTable holds the schema information for the "asset_edges" table.
	AssetEdgesTable = &schema.Table{
		Name:       "asset_edges",
		Columns:    AssetEdgesColumns,
		PrimaryKey: []*schema.Column{AssetEdgesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "assetedge_from_asset",
				Unique:  false,
				Columns: []*schema.Column{AssetEdgesColumns[1]},
			},
			{
				Name:    "assetedge_to_asset",
				Unique:  false,
				Columns: []*schema.Column{AssetEdgesColumns[2]},
			},
		},
	}
	// AssetMetadataColumns holds the columns for the "asset_metadata" table.
	AssetMetadataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "asset", Type: field.TypeString, Size: 256},
		{Name: "column_name", Type: field.TypeString, Nullable: true, Size: 256},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "owner", Type: field.TypeString, Nullable: true, Size: 256},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "set_by", Type: field.TypeUUID},
		{Name: "set_at", Type: field.TypeTime},
	}
	// AssetMetadataTable holds the schema information for the "asset_metadata" table.
	AssetMetadataTable = &schema.Table{
		Name:       "asset_metadata",
		Columns:    AssetMetadataColumns,
		PrimaryKey: []*schema.Column{AssetMetadataColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "assetmetadata_asset_column_name_set_at",
				Unique:  false,
				Columns: []*schema.Column{AssetMetadataColumns[1], AssetMetadataColumns[2], AssetMetadataColumns[7]},
			},
		},
	}
	// AssetVersionsColumns holds the columns for the "asset_versions" table.
	AssetVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "asset", Type: field.TypeString, Size: 256},
		{Name: "code_hash", Type: field.TypeString, Size: 64},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "owner", Type: field.TypeString, Nullable: true, Size: 256},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "column_lineage", Type: field.TypeJSON, Nullable: true},
		{Name: "drift_status", Type: field.TypeString, Size: 16, Default: "clean"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AssetVersionsTable holds the schema information for the "asset_versions" table.
	AssetVersionsTable = &schema.Table{
		Name:       "asset_versions",
		Columns:    AssetVersionsColumns,
		PrimaryKey: []*schema.Column{AssetVersionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "assetversion_asset_created_at",
				Unique:  false,
				Columns: []*schema.Column{AssetVersionsColumns[1], AssetVersionsColumns[8]},
			},
			{
				Name:    "assetversion_asset_code_hash",
				Unique:  true,
				Columns: []*schema.Column{AssetVersionsColumns[1], AssetVersionsColumns[2]},
			},
		},
	}
	// BackfillsColumns holds the columns for the "backfills" table.
	BackfillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "asset_name", Type: field.TypeString, Size: 256},
		{Name: "partition_spec", Type: field.TypeString, Size: 1024},
		{Name: "status", Type: field.TypeString, Size: 16, Default: "submitted"},
		{Name: "total_partitions", Type: field.TypeInt, Default: 0},
		{Name: "submitted_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
	}
	// BackfillsTable holds the schema information for the "backfills" table.
	BackfillsTable = &schema.Table{
		Name:       "backfills",
		Columns:    BackfillsColumns,
		PrimaryKey: []*schema.Column{BackfillsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "backfill_asset_name",
				Unique:  false,
				Columns: []*schema.Column{BackfillsColumns[1]},
			},
			{
				Name:    "backfill_status_submitted_at",
				Unique:  false,
				Columns: []*schema.Column{BackfillsColumns[3], BackfillsColumns[5]},
			},
		},
	}
	// ColumnEdgesColumns holds the columns for the "column_edges" table.
	ColumnEdgesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "from_asset", Type: field.TypeString, Size: 256},
		{Name: "from_column", Type: field.TypeString, Size: 256},
		{Name: "to_asset", Type: field.TypeString, Size: 256},
		{Name: "to_column", Type: field.TypeString, Size: 256},
		{Name: "code_hash_first", Type: field.TypeString, Size: 64},
		{Name: "code_hash_latest", Type: field.TypeString, Size: 64},
		{Name: "first_seen_run_id", Type: field.TypeUUID},
		{Name: "first_seen_at", Type: field.TypeTime},
		{Name: "last_seen_run_id", Type: field.TypeUUID},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "superseded_at", Type: field.TypeTime, Nullable: true},
		{Name: "partition_key", Type: field.TypeString, Nullable: true, Size: 128},
	}
	// ColumnEdgesTable holds the schema information for the "column_edges" table.
	ColumnEdgesTable = &schema.Table{
		Name:       "column_edges",
		Columns:    ColumnEdgesColumns,
		PrimaryKey: []*schema.Column{ColumnEdgesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "columnedge_from_asset_from_column",
				Unique:  false,
				Columns: []*schema.Column{ColumnEdgesColumns[1], ColumnEdgesColumns[2]},
			},
			{
				Name:    "columnedge_to_asset_to_column",
				Unique:  false,
				Columns: []*schema.Column{ColumnEdgesColumns[3], ColumnEdgesColumns[4]},
			},
		},
	}
	// ConcurrencyTokensColumns holds the columns for the "concurrency_tokens" table.
	ConcurrencyTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "run_id", Type: field.TypeUUID},
		{Name: "asset_name", Type: field.TypeString, Size: 256},
		{Name: "resource_tag", Type: field.TypeString, Size: 128},
		{Name: "weight", Type: field.TypeInt, Default: 1},
		{Name: "acquired_at", Type: field.TypeTime},
	}
	// ConcurrencyTokensTable holds the schema information for the "concurrency_tokens" table.
	ConcurrencyTokensTable = &schema.Table{
		Name:       "concurrency_tokens",
		Columns:    ConcurrencyTokensColumns,
		PrimaryKey: []*schema.Column{ConcurrencyTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "concurrencytoken_resource_tag",
				Unique:  false,
				Columns: []*schema.Column{ConcurrencyTokensColumns[3]},
			},
			{
				Name:    "concurrencytoken_run_id",
				Unique:  false,
				Columns: []*schema.Column{ConcurrencyTokensColumns[1]},
			},
			{
				Name:    "concurrencytoken_acquired_at",
				Unique:  false,
				Columns: []*schema.Column{ConcurrencyTokensColumns[5]},
			},
		},
	}
	// EventLogColumns holds the columns for the "event_log" table.
	EventLogColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "occurred_at", Type: field.TypeTime},
		{Name: "event_type", Type: field.TypeString, Size: 64},
		{Name: "actor_id", Type: field.TypeUUID, Nullable: true},
		{Name: "resource_type", Type: field.TypeString, Size: 64},
		{Name: "resource_id", Type: field.TypeString, Size: 128},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
	}
	// EventLogTable holds the schema information for the "event_log" table.
	EventLogTable = &schema.Table{
		Name:       "event_log",
		Columns:    EventLogColumns,
		PrimaryKey: []*schema.Column{EventLogColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "eventlog_event_type_occurred_at",
				Unique:  false,
				Columns: []*schema.Column{EventLogColumns[2], EventLogColumns[1]},
			},
			{
				Name:    "eventlog_resource_type_resource_id",
				Unique:  false,
				Columns: []*schema.Column{EventLogColumns[4], EventLogColumns[5]},
			},
			{
				Name:    "eventlog_occurred_at",
				Unique:  false,
				Columns: []*schema.Column{EventLogColumns[1]},
			},
		},
	}
	// InviteTokenColumns holds the columns for the "invite_token" table.
	InviteTokenColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "token_hash", Type: field.TypeString, Size: 128},
		{Name: "email", Type: field.TypeString, Size: 254},
		{Name: "invited_by", Type: field.TypeUUID},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "accepted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// InviteTokenTable holds the schema information for the "invite_token" table.
	InviteTokenTable = &schema.Table{
		Name:       "invite_token",
		Columns:    InviteTokenColumns,
		PrimaryKey: []*schema.Column{InviteTokenColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "invitetoken_token_hash",
				Unique:  true,
				Columns: []*schema.Column{InviteTokenColumns[1]},
			},
			{
				Name:    "invitetoken_email",
				Unique:  false,
				Columns: []*schema.Column{InviteTokenColumns[2]},
			},
		},
	}
	// RunsColumns holds the columns for the "runs" table.
	RunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "asset_name", Type: field.TypeString, Size: 256},
		{Name: "state", Type: field.TypeString, Size: 16, Default: "queued"},
		{Name: "trigger", Type: field.TypeString, Size: 32, Default: "manual"},
		{Name: "triggered_by", Type: field.TypeUUID, Nullable: true},
		{Name: "claimed_by", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "queued_at", Type: field.TypeTime},
		{Name: "claimed_at", Type: field.TypeTime, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_heartbeat", Type: field.TypeTime, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "partition_key", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "priority", Type: field.TypeString, Size: 16, Default: "normal"},
		{Name: "backfill_id", Type: field.TypeUUID, Nullable: true},
	}
	// RunsTable holds the schema information for the "runs" table.
	RunsTable = &schema.Table{
		Name:       "runs",
		Columns:    RunsColumns,
		PrimaryKey: []*schema.Column{RunsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "run_state_queued_at",
				Unique:  false,
				Columns: []*schema.Column{RunsColumns[2], RunsColumns[6]},
			},
			{
				Name:    "run_asset_name_queued_at",
				Unique:  false,
				Columns: []*schema.Column{RunsColumns[1], RunsColumns[6]},
			},
			{
				Name:    "run_queued_at",
				Unique:  false,
				Columns: []*schema.Column{RunsColumns[6]},
			},
			{
				Name:    "run_state_last_heartbeat",
				Unique:  false,
				Columns: []*schema.Column{RunsColumns[2], RunsColumns[10]},
			},
		},
	}
	// RunStepsColumns holds the columns for the "run_steps" table.
	RunStepsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "run_id", Type: field.TypeUUID},
		{Name: "asset_name", Type: field.TypeString, Size: 256},
		{Name: "state", Type: field.TypeString, Size: 16, Default: "pending"},
		{Name: "attempt", Type: field.TypeInt, Default: 0},
		{Name: "topo_order", Type: field.TypeInt, Default: 0},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "rows_written", Type: field.TypeInt64, Default: 0},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
	}
	// RunStepsTable holds the schema information for the "run_steps" table.
	RunStepsTable = &schema.Table{
		Name:       "run_steps",
		Columns:    RunStepsColumns,
		PrimaryKey: []*schema.Column{RunStepsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "runstep_run_id_topo_order",
				Unique:  false,
				Columns: []*schema.Column{RunStepsColumns[1], RunStepsColumns[5]},
			},
			{
				Name:    "runstep_run_id_state",
				Unique:  false,
				Columns: []*schema.Column{RunStepsColumns[1], RunStepsColumns[3]},
			},
			{
				Name:    "runstep_asset_name",
				Unique:  false,
				Columns: []*schema.Column{RunStepsColumns[2]},
			},
		},
	}
	// SchedulesColumns holds the columns for the "schedules" table.
	SchedulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "asset_name", Type: field.TypeString, Size: 256},
		{Name: "cron_expr", Type: field.TypeString, Size: 128},
		{Name: "last_fire_at", Type: field.TypeTime, Nullable: true},
		{Name: "next_fire_at", Type: field.TypeTime, Nullable: true},
		{Name: "paused_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SchedulesTable holds the schema information for the "schedules" table.
	SchedulesTable = &schema.Table{
		Name:       "schedules",
		Columns:    SchedulesColumns,
		PrimaryKey: []*schema.Column{SchedulesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "schedule_asset_name",
				Unique:  false,
				Columns: []*schema.Column{SchedulesColumns[1]},
			},
			{
				Name:    "schedule_next_fire_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulesColumns[4]},
			},
			{
				Name:    "schedule_paused_at_next_fire_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulesColumns[5], SchedulesColumns[4]},
			},
		},
	}
	// SchemaChangesColumns holds the columns for the "schema_changes" table.
	SchemaChangesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "asset", Type: field.TypeString, Size: 256},
		{Name: "run_id", Type: field.TypeUUID},
		{Name: "code_hash", Type: field.TypeString, Size: 64},
		{Name: "prev_version_id", Type: field.TypeUUID, Nullable: true},
		{Name: "new_version_id", Type: field.TypeUUID},
		{Name: "change_type", Type: field.TypeString, Size: 32},
		{Name: "column_name", Type: field.TypeString, Nullable: true, Size: 256},
		{Name: "prev_type", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "new_type", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "prev_nullable", Type: field.TypeBool, Nullable: true},
		{Name: "new_nullable", Type: field.TypeBool, Nullable: true},
		{Name: "is_breaking", Type: field.TypeBool, Default: false},
		{Name: "observed_at", Type: field.TypeTime},
		{Name: "acknowledged_at", Type: field.TypeTime, Nullable: true},
		{Name: "acknowledged_by", Type: field.TypeUUID, Nullable: true},
		{Name: "acknowledgement_reason", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// SchemaChangesTable holds the schema information for the "schema_changes" table.
	SchemaChangesTable = &schema.Table{
		Name:       "schema_changes",
		Columns:    SchemaChangesColumns,
		PrimaryKey: []*schema.Column{SchemaChangesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "schemachange_asset_observed_at",
				Unique:  false,
				Columns: []*schema.Column{SchemaChangesColumns[1], SchemaChangesColumns[13]},
			},
			{
				Name:    "schemachange_asset_column_name_observed_at",
				Unique:  false,
				Columns: []*schema.Column{SchemaChangesColumns[1], SchemaChangesColumns[7], SchemaChangesColumns[13]},
			},
			{
				Name:    "schemachange_acknowledged_at",
				Unique:  false,
				Columns: []*schema.Column{SchemaChangesColumns[14]},
			},
		},
	}
	// SchemaVersionsColumns holds the columns for the "schema_versions" table.
	SchemaVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "asset", Type: field.TypeString, Size: 256},
		{Name: "code_hash", Type: field.TypeString, Size: 64},
		{Name: "schema_hash", Type: field.TypeString, Size: 64},
		{Name: "schema_data", Type: field.TypeJSON},
		{Name: "captured_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "last_seen_run_id", Type: field.TypeUUID},
	}
	// SchemaVersionsTable holds the schema information for the "schema_versions" table.
	SchemaVersionsTable = &schema.Table{
		Name:       "schema_versions",
		Columns:    SchemaVersionsColumns,
		PrimaryKey: []*schema.Column{SchemaVersionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "schemaversion_asset_captured_at",
				Unique:  false,
				Columns: []*schema.Column{SchemaVersionsColumns[1], SchemaVersionsColumns[5]},
			},
			{
				Name:    "schemaversion_schema_hash",
				Unique:  false,
				Columns: []*schema.Column{SchemaVersionsColumns[3]},
			},
		},
	}
	// SensorsColumns holds the columns for the "sensors" table.
	SensorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "asset_name", Type: field.TypeString, Size: 256},
		{Name: "sensor_name", Type: field.TypeString, Size: 128},
		{Name: "min_interval_seconds", Type: field.TypeInt64, Default: 30},
		{Name: "last_evaluated_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_fired_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_run_key", Type: field.TypeString, Nullable: true, Size: 256},
		{Name: "cooldown_until", Type: field.TypeTime, Nullable: true},
		{Name: "consecutive_failures", Type: field.TypeInt, Default: 0},
		{Name: "disabled_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SensorsTable holds the schema information for the "sensors" table.
	SensorsTable = &schema.Table{
		Name:       "sensors",
		Columns:    SensorsColumns,
		PrimaryKey: []*schema.Column{SensorsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sensor_asset_name_sensor_name",
				Unique:  false,
				Columns: []*schema.Column{SensorsColumns[1], SensorsColumns[2]},
			},
			{
				Name:    "sensor_disabled_at_last_evaluated_at",
				Unique:  false,
				Columns: []*schema.Column{SensorsColumns[9], SensorsColumns[4]},
			},
		},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Size: 254},
		{Name: "password_hash", Type: field.TypeString, Size: 72},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "member"}, Default: "member"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "invited", "disabled"}, Default: "invited"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UserColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AssetEdgesTable,
		AssetMetadataTable,
		AssetVersionsTable,
		BackfillsTable,
		ColumnEdgesTable,
		ConcurrencyTokensTable,
		EventLogTable,
		InviteTokenTable,
		RunsTable,
		RunStepsTable,
		SchedulesTable,
		SchemaChangesTable,
		SchemaVersionsTable,
		SensorsTable,
		UserTable,
	}
)

func init() {
	AssetEdgesTable.Annotation = &entsql.Annotation{
		Table: "asset_edges",
	}
	AssetMetadataTable.Annotation = &entsql.Annotation{
		Table: "asset_metadata",
	}
	AssetVersionsTable.Annotation = &entsql.Annotation{
		Table: "asset_versions",
	}
	BackfillsTable.Annotation = &entsql.Annotation{
		Table: "backfills",
	}
	ColumnEdgesTable.Annotation = &entsql.Annotation{
		Table: "column_edges",
	}
	ConcurrencyTokensTable.Annotation = &entsql.Annotation{
		Table: "concurrency_tokens",
	}
	EventLogTable.Annotation = &entsql.Annotation{
		Table: "event_log",
	}
	InviteTokenTable.Annotation = &entsql.Annotation{
		Table: "invite_token",
	}
	RunsTable.Annotation = &entsql.Annotation{
		Table: "runs",
	}
	RunStepsTable.Annotation = &entsql.Annotation{
		Table: "run_steps",
	}
	SchedulesTable.Annotation = &entsql.Annotation{
		Table: "schedules",
	}
	SchemaChangesTable.Annotation = &entsql.Annotation{
		Table: "schema_changes",
	}
	SchemaVersionsTable.Annotation = &entsql.Annotation{
		Table: "schema_versions",
	}
	SensorsTable.Annotation = &entsql.Annotation{
		Table: "sensors",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
}
