// Code generated by ent, DO NOT EDIT.

package schemaversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLTE(FieldID, id))
}

// Asset applies equality check predicate on the "asset" field. It's identical to AssetEQ.
func Asset(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldAsset, v))
}

// CodeHash applies equality check predicate on the "code_hash" field. It's identical to CodeHashEQ.
func CodeHash(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldCodeHash, v))
}

// SchemaHash applies equality check predicate on the "schema_hash" field. It's identical to SchemaHashEQ.
func SchemaHash(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldSchemaHash, v))
}

// CapturedAt applies equality check predicate on the "captured_at" field. It's identical to CapturedAtEQ.
func CapturedAt(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldCapturedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenRunID applies equality check predicate on the "last_seen_run_id" field. It's identical to LastSeenRunIDEQ.
func LastSeenRunID(v uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldLastSeenRunID, v))
}

// AssetEQ applies the EQ predicate on the "asset" field.
func AssetEQ(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldAsset, v))
}

// AssetNEQ applies the NEQ predicate on the "asset" field.
func AssetNEQ(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNEQ(FieldAsset, v))
}

// AssetIn applies the In predicate on the "asset" field.
func AssetIn(vs ...string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldIn(FieldAsset, vs...))
}

// AssetNotIn applies the NotIn predicate on the "asset" field.
func AssetNotIn(vs ...string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNotIn(FieldAsset, vs...))
}

// AssetGT applies the GT predicate on the "asset" field.
func AssetGT(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGT(FieldAsset, v))
}

// AssetGTE applies the GTE predicate on the "asset" field.
func AssetGTE(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGTE(FieldAsset, v))
}

// AssetLT applies the LT predicate on the "asset" field.
func AssetLT(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLT(FieldAsset, v))
}

// AssetLTE applies the LTE predicate on the "asset" field.
func AssetLTE(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLTE(FieldAsset, v))
}

// AssetContains applies the Contains predicate on the "asset" field.
func AssetContains(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldContains(FieldAsset, v))
}

// AssetHasPrefix applies the HasPrefix predicate on the "asset" field.
func AssetHasPrefix(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldHasPrefix(FieldAsset, v))
}

// AssetHasSuffix applies the HasSuffix predicate on the "asset" field.
func AssetHasSuffix(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldHasSuffix(FieldAsset, v))
}

// AssetEqualFold applies the EqualFold predicate on the "asset" field.
func AssetEqualFold(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEqualFold(FieldAsset, v))
}

// AssetContainsFold applies the ContainsFold predicate on the "asset" field.
func AssetContainsFold(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldContainsFold(FieldAsset, v))
}

// CodeHashEQ applies the EQ predicate on the "code_hash" field.
func CodeHashEQ(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldCodeHash, v))
}

// CodeHashNEQ applies the NEQ predicate on the "code_hash" field.
func CodeHashNEQ(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNEQ(FieldCodeHash, v))
}

// CodeHashIn applies the In predicate on the "code_hash" field.
func CodeHashIn(vs ...string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldIn(FieldCodeHash, vs...))
}

// CodeHashNotIn applies the NotIn predicate on the "code_hash" field.
func CodeHashNotIn(vs ...string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNotIn(FieldCodeHash, vs...))
}

// CodeHashGT applies the GT predicate on the "code_hash" field.
func CodeHashGT(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGT(FieldCodeHash, v))
}

// CodeHashGTE applies the GTE predicate on the "code_hash" field.
func CodeHashGTE(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGTE(FieldCodeHash, v))
}

// CodeHashLT applies the LT predicate on the "code_hash" field.
func CodeHashLT(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLT(FieldCodeHash, v))
}

// CodeHashLTE applies the LTE predicate on the "code_hash" field.
func CodeHashLTE(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLTE(FieldCodeHash, v))
}

// CodeHashContains applies the Contains predicate on the "code_hash" field.
func CodeHashContains(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldContains(FieldCodeHash, v))
}

// CodeHashHasPrefix applies the HasPrefix predicate on the "code_hash" field.
func CodeHashHasPrefix(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldHasPrefix(FieldCodeHash, v))
}

// CodeHashHasSuffix applies the HasSuffix predicate on the "code_hash" field.
func CodeHashHasSuffix(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldHasSuffix(FieldCodeHash, v))
}

// CodeHashEqualFold applies the EqualFold predicate on the "code_hash" field.
func CodeHashEqualFold(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEqualFold(FieldCodeHash, v))
}

// CodeHashContainsFold applies the ContainsFold predicate on the "code_hash" field.
func CodeHashContainsFold(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldContainsFold(FieldCodeHash, v))
}

// SchemaHashEQ applies the EQ predicate on the "schema_hash" field.
func SchemaHashEQ(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldSchemaHash, v))
}

// SchemaHashNEQ applies the NEQ predicate on the "schema_hash" field.
func SchemaHashNEQ(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNEQ(FieldSchemaHash, v))
}

// SchemaHashIn applies the In predicate on the "schema_hash" field.
func SchemaHashIn(vs ...string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldIn(FieldSchemaHash, vs...))
}

// SchemaHashNotIn applies the NotIn predicate on the "schema_hash" field.
func SchemaHashNotIn(vs ...string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNotIn(FieldSchemaHash, vs...))
}

// SchemaHashGT applies the GT predicate on the "schema_hash" field.
func SchemaHashGT(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGT(FieldSchemaHash, v))
}

// SchemaHashGTE applies the GTE predicate on the "schema_hash" field.
func SchemaHashGTE(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGTE(FieldSchemaHash, v))
}

// SchemaHashLT applies the LT predicate on the "schema_hash" field.
func SchemaHashLT(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLT(FieldSchemaHash, v))
}

// SchemaHashLTE applies the LTE predicate on the "schema_hash" field.
func SchemaHashLTE(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLTE(FieldSchemaHash, v))
}

// SchemaHashContains applies the Contains predicate on the "schema_hash" field.
func SchemaHashContains(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldContains(FieldSchemaHash, v))
}

// SchemaHashHasPrefix applies the HasPrefix predicate on the "schema_hash" field.
func SchemaHashHasPrefix(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldHasPrefix(FieldSchemaHash, v))
}

// SchemaHashHasSuffix applies the HasSuffix predicate on the "schema_hash" field.
func SchemaHashHasSuffix(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldHasSuffix(FieldSchemaHash, v))
}

// SchemaHashEqualFold applies the EqualFold predicate on the "schema_hash" field.
func SchemaHashEqualFold(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEqualFold(FieldSchemaHash, v))
}

// SchemaHashContainsFold applies the ContainsFold predicate on the "schema_hash" field.
func SchemaHashContainsFold(v string) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldContainsFold(FieldSchemaHash, v))
}

// CapturedAtEQ applies the EQ predicate on the "captured_at" field.
func CapturedAtEQ(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldCapturedAt, v))
}

// CapturedAtNEQ applies the NEQ predicate on the "captured_at" field.
func CapturedAtNEQ(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNEQ(FieldCapturedAt, v))
}

// CapturedAtIn applies the In predicate on the "captured_at" field.
func CapturedAtIn(vs ...time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldIn(FieldCapturedAt, vs...))
}

// CapturedAtNotIn applies the NotIn predicate on the "captured_at" field.
func CapturedAtNotIn(vs ...time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNotIn(FieldCapturedAt, vs...))
}

// CapturedAtGT applies the GT predicate on the "captured_at" field.
func CapturedAtGT(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGT(FieldCapturedAt, v))
}

// CapturedAtGTE applies the GTE predicate on the "captured_at" field.
func CapturedAtGTE(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGTE(FieldCapturedAt, v))
}

// CapturedAtLT applies the LT predicate on the "captured_at" field.
func CapturedAtLT(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLT(FieldCapturedAt, v))
}

// CapturedAtLTE applies the LTE predicate on the "captured_at" field.
func CapturedAtLTE(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLTE(FieldCapturedAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenRunIDEQ applies the EQ predicate on the "last_seen_run_id" field.
func LastSeenRunIDEQ(v uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldEQ(FieldLastSeenRunID, v))
}

// LastSeenRunIDNEQ applies the NEQ predicate on the "last_seen_run_id" field.
func LastSeenRunIDNEQ(v uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNEQ(FieldLastSeenRunID, v))
}

// LastSeenRunIDIn applies the In predicate on the "last_seen_run_id" field.
func LastSeenRunIDIn(vs ...uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldIn(FieldLastSeenRunID, vs...))
}

// LastSeenRunIDNotIn applies the NotIn predicate on the "last_seen_run_id" field.
func LastSeenRunIDNotIn(vs ...uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldNotIn(FieldLastSeenRunID, vs...))
}

// LastSeenRunIDGT applies the GT predicate on the "last_seen_run_id" field.
func LastSeenRunIDGT(v uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGT(FieldLastSeenRunID, v))
}

// LastSeenRunIDGTE applies the GTE predicate on the "last_seen_run_id" field.
func LastSeenRunIDGTE(v uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldGTE(FieldLastSeenRunID, v))
}

// LastSeenRunIDLT applies the LT predicate on the "last_seen_run_id" field.
func LastSeenRunIDLT(v uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLT(FieldLastSeenRunID, v))
}

// LastSeenRunIDLTE applies the LTE predicate on the "last_seen_run_id" field.
func LastSeenRunIDLTE(v uuid.UUID) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.FieldLTE(FieldLastSeenRunID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SchemaVersion) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SchemaVersion) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SchemaVersion) predicate.SchemaVersion {
	return predicate.SchemaVersion(sql.NotPredicates(p))
}
