// Code generated by ent, DO NOT EDIT.

package runstep

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the runstep type in the database.
	Label = "run_step"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldAssetName holds the string denoting the asset_name field in the database.
	FieldAssetName = "asset_name"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldAttempt holds the string denoting the attempt field in the database.
	FieldAttempt = "attempt"
	// FieldTopoOrder holds the string denoting the topo_order field in the database.
	FieldTopoOrder = "topo_order"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldRowsWritten holds the string denoting the rows_written field in the database.
	FieldRowsWritten = "rows_written"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// Table holds the table name of the runstep in the database.
	Table = "run_steps"
)

// Columns holds all SQL columns for runstep fields.
var Columns = []string{
	FieldID,
	FieldRunID,
	FieldAssetName,
	FieldState,
	FieldAttempt,
	FieldTopoOrder,
	FieldStartedAt,
	FieldFinishedAt,
	FieldRowsWritten,
	FieldErrorMessage,
	FieldMetadata,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AssetNameValidator is a validator for the "asset_name" field. It is called by the builders before save.
	AssetNameValidator func(string) error
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState string
	// StateValidator is a validator for the "state" field. It is called by the builders before save.
	StateValidator func(string) error
	// DefaultAttempt holds the default value on creation for the "attempt" field.
	DefaultAttempt int
	// DefaultTopoOrder holds the default value on creation for the "topo_order" field.
	DefaultTopoOrder int
	// DefaultRowsWritten holds the default value on creation for the "rows_written" field.
	DefaultRowsWritten int64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the RunStep queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByAssetName orders the results by the asset_name field.
func ByAssetName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssetName, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByAttempt orders the results by the attempt field.
func ByAttempt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempt, opts...).ToFunc()
}

// ByTopoOrder orders the results by the topo_order field.
func ByTopoOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopoOrder, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByRowsWritten orders the results by the rows_written field.
func ByRowsWritten(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRowsWritten, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}
