// Code generated by ent, DO NOT EDIT.

package concurrencytoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldLTE(FieldID, id))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEQ(FieldRunID, v))
}

// AssetName applies equality check predicate on the "asset_name" field. It's identical to AssetNameEQ.
func AssetName(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEQ(FieldAssetName, v))
}

// ResourceTag applies equality check predicate on the "resource_tag" field. It's identical to ResourceTagEQ.
func ResourceTag(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEQ(FieldResourceTag, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v int) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEQ(FieldWeight, v))
}

// AcquiredAt applies equality check predicate on the "acquired_at" field. It's identical to AcquiredAtEQ.
func AcquiredAt(v time.Time) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEQ(FieldAcquiredAt, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldNotIn(FieldRunID, vs...))
}

// RunIDGT applies the GT predicate on the "run_id" field.
func RunIDGT(v uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldGT(FieldRunID, v))
}

// RunIDGTE applies the GTE predicate on the "run_id" field.
func RunIDGTE(v uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldGTE(FieldRunID, v))
}

// RunIDLT applies the LT predicate on the "run_id" field.
func RunIDLT(v uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldLT(FieldRunID, v))
}

// RunIDLTE applies the LTE predicate on the "run_id" field.
func RunIDLTE(v uuid.UUID) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldLTE(FieldRunID, v))
}

// AssetNameEQ applies the EQ predicate on the "asset_name" field.
func AssetNameEQ(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEQ(FieldAssetName, v))
}

// AssetNameNEQ applies the NEQ predicate on the "asset_name" field.
func AssetNameNEQ(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldNEQ(FieldAssetName, v))
}

// AssetNameIn applies the In predicate on the "asset_name" field.
func AssetNameIn(vs ...string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldIn(FieldAssetName, vs...))
}

// AssetNameNotIn applies the NotIn predicate on the "asset_name" field.
func AssetNameNotIn(vs ...string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldNotIn(FieldAssetName, vs...))
}

// AssetNameGT applies the GT predicate on the "asset_name" field.
func AssetNameGT(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldGT(FieldAssetName, v))
}

// AssetNameGTE applies the GTE predicate on the "asset_name" field.
func AssetNameGTE(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldGTE(FieldAssetName, v))
}

// AssetNameLT applies the LT predicate on the "asset_name" field.
func AssetNameLT(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldLT(FieldAssetName, v))
}

// AssetNameLTE applies the LTE predicate on the "asset_name" field.
func AssetNameLTE(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldLTE(FieldAssetName, v))
}

// AssetNameContains applies the Contains predicate on the "asset_name" field.
func AssetNameContains(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldContains(FieldAssetName, v))
}

// AssetNameHasPrefix applies the HasPrefix predicate on the "asset_name" field.
func AssetNameHasPrefix(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldHasPrefix(FieldAssetName, v))
}

// AssetNameHasSuffix applies the HasSuffix predicate on the "asset_name" field.
func AssetNameHasSuffix(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldHasSuffix(FieldAssetName, v))
}

// AssetNameEqualFold applies the EqualFold predicate on the "asset_name" field.
func AssetNameEqualFold(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEqualFold(FieldAssetName, v))
}

// AssetNameContainsFold applies the ContainsFold predicate on the "asset_name" field.
func AssetNameContainsFold(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldContainsFold(FieldAssetName, v))
}

// ResourceTagEQ applies the EQ predicate on the "resource_tag" field.
func ResourceTagEQ(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEQ(FieldResourceTag, v))
}

// ResourceTagNEQ applies the NEQ predicate on the "resource_tag" field.
func ResourceTagNEQ(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldNEQ(FieldResourceTag, v))
}

// ResourceTagIn applies the In predicate on the "resource_tag" field.
func ResourceTagIn(vs ...string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldIn(FieldResourceTag, vs...))
}

// ResourceTagNotIn applies the NotIn predicate on the "resource_tag" field.
func ResourceTagNotIn(vs ...string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldNotIn(FieldResourceTag, vs...))
}

// ResourceTagGT applies the GT predicate on the "resource_tag" field.
func ResourceTagGT(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldGT(FieldResourceTag, v))
}

// ResourceTagGTE applies the GTE predicate on the "resource_tag" field.
func ResourceTagGTE(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldGTE(FieldResourceTag, v))
}

// ResourceTagLT applies the LT predicate on the "resource_tag" field.
func ResourceTagLT(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldLT(FieldResourceTag, v))
}

// ResourceTagLTE applies the LTE predicate on the "resource_tag" field.
func ResourceTagLTE(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldLTE(FieldResourceTag, v))
}

// ResourceTagContains applies the Contains predicate on the "resource_tag" field.
func ResourceTagContains(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldContains(FieldResourceTag, v))
}

// ResourceTagHasPrefix applies the HasPrefix predicate on the "resource_tag" field.
func ResourceTagHasPrefix(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldHasPrefix(FieldResourceTag, v))
}

// ResourceTagHasSuffix applies the HasSuffix predicate on the "resource_tag" field.
func ResourceTagHasSuffix(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldHasSuffix(FieldResourceTag, v))
}

// ResourceTagEqualFold applies the EqualFold predicate on the "resource_tag" field.
func ResourceTagEqualFold(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEqualFold(FieldResourceTag, v))
}

// ResourceTagContainsFold applies the ContainsFold predicate on the "resource_tag" field.
func ResourceTagContainsFold(v string) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldContainsFold(FieldResourceTag, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v int) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v int) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...int) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...int) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v int) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v int) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v int) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v int) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldLTE(FieldWeight, v))
}

// AcquiredAtEQ applies the EQ predicate on the "acquired_at" field.
func AcquiredAtEQ(v time.Time) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldEQ(FieldAcquiredAt, v))
}

// AcquiredAtNEQ applies the NEQ predicate on the "acquired_at" field.
func AcquiredAtNEQ(v time.Time) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldNEQ(FieldAcquiredAt, v))
}

// AcquiredAtIn applies the In predicate on the "acquired_at" field.
func AcquiredAtIn(vs ...time.Time) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldIn(FieldAcquiredAt, vs...))
}

// AcquiredAtNotIn applies the NotIn predicate on the "acquired_at" field.
func AcquiredAtNotIn(vs ...time.Time) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldNotIn(FieldAcquiredAt, vs...))
}

// AcquiredAtGT applies the GT predicate on the "acquired_at" field.
func AcquiredAtGT(v time.Time) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldGT(FieldAcquiredAt, v))
}

// AcquiredAtGTE applies the GTE predicate on the "acquired_at" field.
func AcquiredAtGTE(v time.Time) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldGTE(FieldAcquiredAt, v))
}

// AcquiredAtLT applies the LT predicate on the "acquired_at" field.
func AcquiredAtLT(v time.Time) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldLT(FieldAcquiredAt, v))
}

// AcquiredAtLTE applies the LTE predicate on the "acquired_at" field.
func AcquiredAtLTE(v time.Time) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.FieldLTE(FieldAcquiredAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConcurrencyToken) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConcurrencyToken) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConcurrencyToken) predicate.ConcurrencyToken {
	return predicate.ConcurrencyToken(sql.NotPredicates(p))
}
