// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lineage.sql

package lineageq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const traverseAssetLineage = `-- name: TraverseAssetLineage :many

WITH RECURSIVE lineage AS (
    -- base: assets directly adjacent to @asset
    SELECT
        CASE WHEN $1::text = 'downstream' THEN to_asset
                                                    ELSE from_asset END AS asset,
        1 AS depth,
        ARRAY[CASE WHEN $1::text = 'downstream' THEN from_asset
                                                          ELSE to_asset END,
              CASE WHEN $1::text = 'downstream' THEN to_asset
                                                          ELSE from_asset END]::text[] AS path
    FROM asset_edges
    WHERE
        CASE WHEN $1::text = 'downstream' THEN from_asset = $2::text
                                                    ELSE to_asset   = $2::text END
        AND CASE WHEN $3::bool
                 THEN first_seen_at <= $4::timestamptz
                      AND (superseded_at IS NULL OR superseded_at > $4::timestamptz)
                 ELSE superseded_at IS NULL END

    UNION ALL

    SELECT
        CASE WHEN $1::text = 'downstream' THEN e.to_asset
                                                    ELSE e.from_asset END,
        l.depth + 1,
        l.path || ARRAY[CASE WHEN $1::text = 'downstream' THEN e.to_asset
                                                                    ELSE e.from_asset END]::text[]
    FROM asset_edges e
    JOIN lineage l ON
        CASE WHEN $1::text = 'downstream' THEN e.from_asset = l.asset
                                                    ELSE e.to_asset   = l.asset END
    WHERE
        l.depth < LEAST($5::int, 25)  -- D-14 SQL-level hard ceiling (defense in depth; impact.Analyze is layer 1, this CTE bound is layer 2)
        AND CASE WHEN $3::bool
                 THEN e.first_seen_at <= $4::timestamptz
                      AND (e.superseded_at IS NULL OR e.superseded_at > $4::timestamptz)
                 ELSE e.superseded_at IS NULL END
        AND NOT (l.path @> ARRAY[
            CASE WHEN $1::text = 'downstream' THEN e.to_asset
                                                        ELSE e.from_asset END
        ]::text[])  -- cycle guard (Pitfall 2)
)
SELECT DISTINCT asset, depth FROM lineage ORDER BY depth, asset
`

type TraverseAssetLineageParams struct {
	Direction string
	Asset     string
	UseAsOf   bool
	AsOf      pgtype.Timestamptz
	MaxDepth  int32
}

type TraverseAssetLineageRow struct {
	Asset interface{}
	Depth int32
}

// internal/lineage/queries/lineage.sql
// TraverseAssetLineage walks the asset_edges graph from @asset in the requested
// direction (downstream | upstream), returning each visited (asset, depth) up to
// @max_depth. Caller MUST validate @max_depth <= 25 before calling (D-14).
func (q *Queries) TraverseAssetLineage(ctx context.Context, db DBTX, arg TraverseAssetLineageParams) ([]TraverseAssetLineageRow, error) {
	rows, err := db.Query(ctx, traverseAssetLineage,
		arg.Direction,
		arg.Asset,
		arg.UseAsOf,
		arg.AsOf,
		arg.MaxDepth,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TraverseAssetLineageRow
	for rows.Next() {
		var i TraverseAssetLineageRow
		if err := rows.Scan(&i.Asset, &i.Depth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const traverseColumnLineage = `-- name: TraverseColumnLineage :many
WITH RECURSIVE lineage AS (
    SELECT
        CASE WHEN $1::text = 'downstream' THEN to_asset    ELSE from_asset    END AS asset,
        CASE WHEN $1::text = 'downstream' THEN to_column   ELSE from_column   END AS column_name,
        1 AS depth,
        ARRAY[
            CASE WHEN $1::text = 'downstream' THEN from_asset || '.' || from_column
                                                        ELSE to_asset   || '.' || to_column   END,
            CASE WHEN $1::text = 'downstream' THEN to_asset   || '.' || to_column
                                                        ELSE from_asset || '.' || from_column END
        ]::text[] AS path
    FROM column_edges
    WHERE
        CASE WHEN $1::text = 'downstream'
             THEN from_asset = $2::text AND from_column = $3::text
             ELSE to_asset   = $2::text AND to_column   = $3::text END
        AND CASE WHEN $4::bool
                 THEN first_seen_at <= $5::timestamptz
                      AND (superseded_at IS NULL OR superseded_at > $5::timestamptz)
                 ELSE superseded_at IS NULL END

    UNION ALL

    SELECT
        CASE WHEN $1::text = 'downstream' THEN e.to_asset    ELSE e.from_asset    END,
        CASE WHEN $1::text = 'downstream' THEN e.to_column   ELSE e.from_column   END,
        l.depth + 1,
        l.path || ARRAY[
            CASE WHEN $1::text = 'downstream' THEN e.to_asset || '.' || e.to_column
                                                        ELSE e.from_asset || '.' || e.from_column END
        ]::text[]
    FROM column_edges e
    JOIN lineage l ON
        CASE WHEN $1::text = 'downstream'
             THEN e.from_asset = l.asset AND e.from_column = l.column_name
             ELSE e.to_asset   = l.asset AND e.to_column   = l.column_name END
    WHERE
        l.depth < LEAST($6::int, 25)  -- D-14 SQL-level hard ceiling (defense in depth)
        AND CASE WHEN $4::bool
                 THEN e.first_seen_at <= $5::timestamptz
                      AND (e.superseded_at IS NULL OR e.superseded_at > $5::timestamptz)
                 ELSE e.superseded_at IS NULL END
        AND NOT (l.path @> ARRAY[
            CASE WHEN $1::text = 'downstream' THEN e.to_asset || '.' || e.to_column
                                                        ELSE e.from_asset || '.' || e.from_column END
        ]::text[])
)
SELECT DISTINCT asset, column_name, depth FROM lineage ORDER BY depth, asset, column_name
`

type TraverseColumnLineageParams struct {
	Direction string
	Asset     string
	ColName   string
	UseAsOf   bool
	AsOf      pgtype.Timestamptz
	MaxDepth  int32
}

type TraverseColumnLineageRow struct {
	Asset      interface{}
	ColumnName interface{}
	Depth      int32
}

// Same template but on column_edges, with (asset, column) tuples in the path.
func (q *Queries) TraverseColumnLineage(ctx context.Context, db DBTX, arg TraverseColumnLineageParams) ([]TraverseColumnLineageRow, error) {
	rows, err := db.Query(ctx, traverseColumnLineage,
		arg.Direction,
		arg.Asset,
		arg.ColName,
		arg.UseAsOf,
		arg.AsOf,
		arg.MaxDepth,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TraverseColumnLineageRow
	for rows.Next() {
		var i TraverseColumnLineageRow
		if err := rows.Scan(&i.Asset, &i.ColumnName, &i.Depth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
