// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package lineageq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AssetEdge struct {
	ID             pgtype.UUID
	FromAsset      string
	ToAsset        string
	CodeHashFirst  string
	CodeHashLatest string
	FirstSeenRunID pgtype.UUID
	FirstSeenAt    pgtype.Timestamptz
	LastSeenRunID  pgtype.UUID
	LastSeenAt     pgtype.Timestamptz
	SupersededAt   pgtype.Timestamptz
}

type AssetMetadatum struct {
	ID          pgtype.UUID
	Asset       string
	ColumnName  *string
	Description *string
	Owner       *string
	Tags        []byte
	SetBy       pgtype.UUID
	SetAt       pgtype.Timestamptz
}

type AssetVersion struct {
	ID            pgtype.UUID
	Asset         string
	CodeHash      string
	Description   *string
	Owner         *string
	Tags          []byte
	ColumnLineage []byte
	DriftStatus   string
	CreatedAt     pgtype.Timestamptz
}

type Backfill struct {
	ID              pgtype.UUID
	AssetName       string
	PartitionSpec   string
	Status          string
	TotalPartitions int64
	SubmittedAt     pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
}

type ColumnEdge struct {
	ID             pgtype.UUID
	FromAsset      string
	FromColumn     string
	ToAsset        string
	ToColumn       string
	CodeHashFirst  string
	CodeHashLatest string
	FirstSeenRunID pgtype.UUID
	FirstSeenAt    pgtype.Timestamptz
	LastSeenRunID  pgtype.UUID
	LastSeenAt     pgtype.Timestamptz
	SupersededAt   pgtype.Timestamptz
	PartitionKey   *string
}

type ConcurrencyToken struct {
	ID          pgtype.UUID
	RunID       pgtype.UUID
	AssetName   string
	ResourceTag string
	Weight      int64
	AcquiredAt  pgtype.Timestamptz
}

type EventLog struct {
	ID           pgtype.UUID
	OccurredAt   pgtype.Timestamptz
	EventType    string
	ActorID      pgtype.UUID
	ResourceType string
	ResourceID   string
	Payload      []byte
}

type InviteToken struct {
	ID         pgtype.UUID
	TokenHash  string
	Email      string
	InvitedBy  pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Run struct {
	ID          pgtype.UUID
	AssetName   string
	State       string
	Trigger     string
	TriggeredBy pgtype.UUID
	ClaimedBy   *string
	QueuedAt    pgtype.Timestamptz
	ClaimedAt   pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	// Set on claim, ticked every ~30s by executor. Reaper resets stale rows (>5m old) to queued.
	LastHeartbeat pgtype.Timestamptz
	ErrorMessage  *string
	Metadata      []byte
	PartitionKey  *string
	Priority      string
	BackfillID    pgtype.UUID
}

type RunStep struct {
	ID           pgtype.UUID
	RunID        pgtype.UUID
	AssetName    string
	State        string
	Attempt      int64
	TopoOrder    int64
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	RowsWritten  int64
	ErrorMessage *string
	Metadata     []byte
}

type Schedule struct {
	ID         pgtype.UUID
	AssetName  string
	CronExpr   string
	LastFireAt pgtype.Timestamptz
	NextFireAt pgtype.Timestamptz
	PausedAt   pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type SchemaChange struct {
	ID                    pgtype.UUID
	Asset                 string
	RunID                 pgtype.UUID
	CodeHash              string
	PrevVersionID         pgtype.UUID
	NewVersionID          pgtype.UUID
	ChangeType            string
	ColumnName            *string
	PrevType              *string
	NewType               *string
	PrevNullable          *bool
	NewNullable           *bool
	IsBreaking            bool
	ObservedAt            pgtype.Timestamptz
	AcknowledgedAt        pgtype.Timestamptz
	AcknowledgedBy        pgtype.UUID
	AcknowledgementReason *string
}

type SchemaVersion struct {
	ID            pgtype.UUID
	Asset         string
	CodeHash      string
	SchemaHash    string
	SchemaData    []byte
	CapturedAt    pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	LastSeenRunID pgtype.UUID
}

type Sensor struct {
	ID                  pgtype.UUID
	AssetName           string
	SensorName          string
	MinIntervalSeconds  int64
	LastEvaluatedAt     pgtype.Timestamptz
	LastFiredAt         pgtype.Timestamptz
	LastRunKey          *string
	CooldownUntil       pgtype.Timestamptz
	ConsecutiveFailures int64
	DisabledAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Role         string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
