// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kanpon/data-governance/internal/storage/ent/assetversion"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
)

// AssetVersionDelete is the builder for deleting a AssetVersion entity.
type AssetVersionDelete struct {
	config
	hooks    []Hook
	mutation *AssetVersionMutation
}

// Where appends a list predicates to the AssetVersionDelete builder.
func (avd *AssetVersionDelete) Where(ps ...predicate.AssetVersion) *AssetVersionDelete {
	avd.mutation.Where(ps...)
	return avd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (avd *AssetVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, avd.sqlExec, avd.mutation, avd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (avd *AssetVersionDelete) ExecX(ctx context.Context) int {
	n, err := avd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (avd *AssetVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(assetversion.Table, sqlgraph.NewFieldSpec(assetversion.FieldID, field.TypeUUID))
	if ps := avd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, avd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	avd.mutation.done = true
	return affected, err
}

// AssetVersionDeleteOne is the builder for deleting a single AssetVersion entity.
type AssetVersionDeleteOne struct {
	avd *AssetVersionDelete
}

// Where appends a list predicates to the AssetVersionDelete builder.
func (avdo *AssetVersionDeleteOne) Where(ps ...predicate.AssetVersion) *AssetVersionDeleteOne {
	avdo.avd.mutation.Where(ps...)
	return avdo
}

// Exec executes the deletion query.
func (avdo *AssetVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := avdo.avd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{assetversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (avdo *AssetVersionDeleteOne) ExecX(ctx context.Context) {
	if err := avdo.Exec(ctx); err != nil {
		panic(err)
	}
}
