// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/assetedge"
)

// AssetEdge is the model entity for the AssetEdge schema.
type AssetEdge struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// FromAsset holds the value of the "from_asset" field.
	FromAsset string `json:"from_asset,omitempty"`
	// ToAsset holds the value of the "to_asset" field.
	ToAsset string `json:"to_asset,omitempty"`
	// CodeHashFirst holds the value of the "code_hash_first" field.
	CodeHashFirst string `json:"code_hash_first,omitempty"`
	// CodeHashLatest holds the value of the "code_hash_latest" field.
	CodeHashLatest string `json:"code_hash_latest,omitempty"`
	// FirstSeenRunID holds the value of the "first_seen_run_id" field.
	FirstSeenRunID uuid.UUID `json:"first_seen_run_id,omitempty"`
	// FirstSeenAt holds the value of the "first_seen_at" field.
	FirstSeenAt time.Time `json:"first_seen_at,omitempty"`
	// LastSeenRunID holds the value of the "last_seen_run_id" field.
	LastSeenRunID uuid.UUID `json:"last_seen_run_id,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// SupersededAt holds the value of the "superseded_at" field.
	SupersededAt *time.Time `json:"superseded_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AssetEdge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case assetedge.FieldFromAsset, assetedge.FieldToAsset, assetedge.FieldCodeHashFirst, assetedge.FieldCodeHashLatest:
			values[i] = new(sql.NullString)
		case assetedge.FieldFirstSeenAt, assetedge.FieldLastSeenAt, assetedge.FieldSupersededAt:
			values[i] = new(sql.NullTime)
		case assetedge.FieldID, assetedge.FieldFirstSeenRunID, assetedge.FieldLastSeenRunID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AssetEdge fields.
func (ae *AssetEdge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case assetedge.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ae.ID = *value
			}
		case assetedge.FieldFromAsset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_asset", values[i])
			} else if value.Valid {
				ae.FromAsset = value.String
			}
		case assetedge.FieldToAsset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_asset", values[i])
			} else if value.Valid {
				ae.ToAsset = value.String
			}
		case assetedge.FieldCodeHashFirst:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_hash_first", values[i])
			} else if value.Valid {
				ae.CodeHashFirst = value.String
			}
		case assetedge.FieldCodeHashLatest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_hash_latest", values[i])
			} else if value.Valid {
				ae.CodeHashLatest = value.String
			}
		case assetedge.FieldFirstSeenRunID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field first_seen_run_id", values[i])
			} else if value != nil {
				ae.FirstSeenRunID = *value
			}
		case assetedge.FieldFirstSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_seen_at", values[i])
			} else if value.Valid {
				ae.FirstSeenAt = value.Time
			}
		case assetedge.FieldLastSeenRunID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_run_id", values[i])
			} else if value != nil {
				ae.LastSeenRunID = *value
			}
		case assetedge.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				ae.LastSeenAt = value.Time
			}
		case assetedge.FieldSupersededAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field superseded_at", values[i])
			} else if value.Valid {
				ae.SupersededAt = new(time.Time)
				*ae.SupersededAt = value.Time
			}
		default:
			ae.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AssetEdge.
// This includes values selected through modifiers, order, etc.
func (ae *AssetEdge) Value(name string) (ent.Value, error) {
	return ae.selectValues.Get(name)
}

// Update returns a builder for updating this AssetEdge.
// Note that you need to call AssetEdge.Unwrap() before calling this method if this AssetEdge
// was returned from a transaction, and the transaction was committed or rolled back.
func (ae *AssetEdge) Update() *AssetEdgeUpdateOne {
	return NewAssetEdgeClient(ae.config).UpdateOne(ae)
}

// Unwrap unwraps the AssetEdge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ae *AssetEdge) Unwrap() *AssetEdge {
	_tx, ok := ae.config.driver.(*txDriver)
	if !ok {
		panic("ent: AssetEdge is not a transactional entity")
	}
	ae.config.driver = _tx.drv
	return ae
}

// String implements the fmt.Stringer.
func (ae *AssetEdge) String() string {
	var builder strings.Builder
	builder.WriteString("AssetEdge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ae.ID))
	builder.WriteString("from_asset=")
	builder.WriteString(ae.FromAsset)
	builder.WriteString(", ")
	builder.WriteString("to_asset=")
	builder.WriteString(ae.ToAsset)
	builder.WriteString(", ")
	builder.WriteString("code_hash_first=")
	builder.WriteString(ae.CodeHashFirst)
	builder.WriteString(", ")
	builder.WriteString("code_hash_latest=")
	builder.WriteString(ae.CodeHashLatest)
	builder.WriteString(", ")
	builder.WriteString("first_seen_run_id=")
	builder.WriteString(fmt.Sprintf("%v", ae.FirstSeenRunID))
	builder.WriteString(", ")
	builder.WriteString("first_seen_at=")
	builder.WriteString(ae.FirstSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_run_id=")
	builder.WriteString(fmt.Sprintf("%v", ae.LastSeenRunID))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(ae.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ae.SupersededAt; v != nil {
		builder.WriteString("superseded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AssetEdges is a parsable slice of AssetEdge.
type AssetEdges []*AssetEdge
