// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/assetedge"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
)

// AssetEdgeUpdate is the builder for updating AssetEdge entities.
type AssetEdgeUpdate struct {
	config
	hooks    []Hook
	mutation *AssetEdgeMutation
}

// Where appends a list predicates to the AssetEdgeUpdate builder.
func (aeu *AssetEdgeUpdate) Where(ps ...predicate.AssetEdge) *AssetEdgeUpdate {
	aeu.mutation.Where(ps...)
	return aeu
}

// SetCodeHashLatest sets the "code_hash_latest" field.
func (aeu *AssetEdgeUpdate) SetCodeHashLatest(s string) *AssetEdgeUpdate {
	aeu.mutation.SetCodeHashLatest(s)
	return aeu
}

// SetNillableCodeHashLatest sets the "code_hash_latest" field if the given value is not nil.
func (aeu *AssetEdgeUpdate) SetNillableCodeHashLatest(s *string) *AssetEdgeUpdate {
	if s != nil {
		aeu.SetCodeHashLatest(*s)
	}
	return aeu
}

// SetLastSeenRunID sets the "last_seen_run_id" field.
func (aeu *AssetEdgeUpdate) SetLastSeenRunID(u uuid.UUID) *AssetEdgeUpdate {
	aeu.mutation.SetLastSeenRunID(u)
	return aeu
}

// SetNillableLastSeenRunID sets the "last_seen_run_id" field if the given value is not nil.
func (aeu *AssetEdgeUpdate) SetNillableLastSeenRunID(u *uuid.UUID) *AssetEdgeUpdate {
	if u != nil {
		aeu.SetLastSeenRunID(*u)
	}
	return aeu
}

// SetLastSeenAt sets the "last_seen_at" field.
func (aeu *AssetEdgeUpdate) SetLastSeenAt(t time.Time) *AssetEdgeUpdate {
	aeu.mutation.SetLastSeenAt(t)
	return aeu
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (aeu *AssetEdgeUpdate) SetNillableLastSeenAt(t *time.Time) *AssetEdgeUpdate {
	if t != nil {
		aeu.SetLastSeenAt(*t)
	}
	return aeu
}

// SetSupersededAt sets the "superseded_at" field.
func (aeu *AssetEdgeUpdate) SetSupersededAt(t time.Time) *AssetEdgeUpdate {
	aeu.mutation.SetSupersededAt(t)
	return aeu
}

// SetNillableSupersededAt sets the "superseded_at" field if the given value is not nil.
func (aeu *AssetEdgeUpdate) SetNillableSupersededAt(t *time.Time) *AssetEdgeUpdate {
	if t != nil {
		aeu.SetSupersededAt(*t)
	}
	return aeu
}

// ClearSupersededAt clears the value of the "superseded_at" field.
func (aeu *AssetEdgeUpdate) ClearSupersededAt() *AssetEdgeUpdate {
	aeu.mutation.ClearSupersededAt()
	return aeu
}

// Mutation returns the AssetEdgeMutation object of the builder.
func (aeu *AssetEdgeUpdate) Mutation() *AssetEdgeMutation {
	return aeu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aeu *AssetEdgeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, aeu.sqlSave, aeu.mutation, aeu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aeu *AssetEdgeUpdate) SaveX(ctx context.Context) int {
	affected, err := aeu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aeu *AssetEdgeUpdate) Exec(ctx context.Context) error {
	_, err := aeu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aeu *AssetEdgeUpdate) ExecX(ctx context.Context) {
	if err := aeu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aeu *AssetEdgeUpdate) check() error {
	if v, ok := aeu.mutation.CodeHashLatest(); ok {
		if err := assetedge.CodeHashLatestValidator(v); err != nil {
			return &ValidationError{Name: "code_hash_latest", err: fmt.Errorf(`ent: validator failed for field "AssetEdge.code_hash_latest": %w`, err)}
		}
	}
	return nil
}

func (aeu *AssetEdgeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := aeu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(assetedge.Table, assetedge.Columns, sqlgraph.NewFieldSpec(assetedge.FieldID, field.TypeUUID))
	if ps := aeu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aeu.mutation.CodeHashLatest(); ok {
		_spec.SetField(assetedge.FieldCodeHashLatest, field.TypeString, value)
	}
	if value, ok := aeu.mutation.LastSeenRunID(); ok {
		_spec.SetField(assetedge.FieldLastSeenRunID, field.TypeUUID, value)
	}
	if value, ok := aeu.mutation.LastSeenAt(); ok {
		_spec.SetField(assetedge.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := aeu.mutation.SupersededAt(); ok {
		_spec.SetField(assetedge.FieldSupersededAt, field.TypeTime, value)
	}
	if aeu.mutation.SupersededAtCleared() {
		_spec.ClearField(assetedge.FieldSupersededAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aeu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assetedge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aeu.mutation.done = true
	return n, nil
}

// AssetEdgeUpdateOne is the builder for updating a single AssetEdge entity.
type AssetEdgeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssetEdgeMutation
}

// SetCodeHashLatest sets the "code_hash_latest" field.
func (aeuo *AssetEdgeUpdateOne) SetCodeHashLatest(s string) *AssetEdgeUpdateOne {
	aeuo.mutation.SetCodeHashLatest(s)
	return aeuo
}

// SetNillableCodeHashLatest sets the "code_hash_latest" field if the given value is not nil.
func (aeuo *AssetEdgeUpdateOne) SetNillableCodeHashLatest(s *string) *AssetEdgeUpdateOne {
	if s != nil {
		aeuo.SetCodeHashLatest(*s)
	}
	return aeuo
}

// SetLastSeenRunID sets the "last_seen_run_id" field.
func (aeuo *AssetEdgeUpdateOne) SetLastSeenRunID(u uuid.UUID) *AssetEdgeUpdateOne {
	aeuo.mutation.SetLastSeenRunID(u)
	return aeuo
}

// SetNillableLastSeenRunID sets the "last_seen_run_id" field if the given value is not nil.
func (aeuo *AssetEdgeUpdateOne) SetNillableLastSeenRunID(u *uuid.UUID) *AssetEdgeUpdateOne {
	if u != nil {
		aeuo.SetLastSeenRunID(*u)
	}
	return aeuo
}

// SetLastSeenAt sets the "last_seen_at" field.
func (aeuo *AssetEdgeUpdateOne) SetLastSeenAt(t time.Time) *AssetEdgeUpdateOne {
	aeuo.mutation.SetLastSeenAt(t)
	return aeuo
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (aeuo *AssetEdgeUpdateOne) SetNillableLastSeenAt(t *time.Time) *AssetEdgeUpdateOne {
	if t != nil {
		aeuo.SetLastSeenAt(*t)
	}
	return aeuo
}

// SetSupersededAt sets the "superseded_at" field.
func (aeuo *AssetEdgeUpdateOne) SetSupersededAt(t time.Time) *AssetEdgeUpdateOne {
	aeuo.mutation.SetSupersededAt(t)
	return aeuo
}

// SetNillableSupersededAt sets the "superseded_at" field if the given value is not nil.
func (aeuo *AssetEdgeUpdateOne) SetNillableSupersededAt(t *time.Time) *AssetEdgeUpdateOne {
	if t != nil {
		aeuo.SetSupersededAt(*t)
	}
	return aeuo
}

// ClearSupersededAt clears the value of the "superseded_at" field.
func (aeuo *AssetEdgeUpdateOne) ClearSupersededAt() *AssetEdgeUpdateOne {
	aeuo.mutation.ClearSupersededAt()
	return aeuo
}

// Mutation returns the AssetEdgeMutation object of the builder.
func (aeuo *AssetEdgeUpdateOne) Mutation() *AssetEdgeMutation {
	return aeuo.mutation
}

// Where appends a list predicates to the AssetEdgeUpdate builder.
func (aeuo *AssetEdgeUpdateOne) Where(ps ...predicate.AssetEdge) *AssetEdgeUpdateOne {
	aeuo.mutation.Where(ps...)
	return aeuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aeuo *AssetEdgeUpdateOne) Select(field string, fields ...string) *AssetEdgeUpdateOne {
	aeuo.fields = append([]string{field}, fields...)
	return aeuo
}

// Save executes the query and returns the updated AssetEdge entity.
func (aeuo *AssetEdgeUpdateOne) Save(ctx context.Context) (*AssetEdge, error) {
	return withHooks(ctx, aeuo.sqlSave, aeuo.mutation, aeuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aeuo *AssetEdgeUpdateOne) SaveX(ctx context.Context) *AssetEdge {
	node, err := aeuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aeuo *AssetEdgeUpdateOne) Exec(ctx context.Context) error {
	_, err := aeuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aeuo *AssetEdgeUpdateOne) ExecX(ctx context.Context) {
	if err := aeuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aeuo *AssetEdgeUpdateOne) check() error {
	if v, ok := aeuo.mutation.CodeHashLatest(); ok {
		if err := assetedge.CodeHashLatestValidator(v); err != nil {
			return &ValidationError{Name: "code_hash_latest", err: fmt.Errorf(`ent: validator failed for field "AssetEdge.code_hash_latest": %w`, err)}
		}
	}
	return nil
}

func (aeuo *AssetEdgeUpdateOne) sqlSave(ctx context.Context) (_node *AssetEdge, err error) {
	if err := aeuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(assetedge.Table, assetedge.Columns, sqlgraph.NewFieldSpec(assetedge.FieldID, field.TypeUUID))
	id, ok := aeuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AssetEdge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aeuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assetedge.FieldID)
		for _, f := range fields {
			if !assetedge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != assetedge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aeuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aeuo.mutation.CodeHashLatest(); ok {
		_spec.SetField(assetedge.FieldCodeHashLatest, field.TypeString, value)
	}
	if value, ok := aeuo.mutation.LastSeenRunID(); ok {
		_spec.SetField(assetedge.FieldLastSeenRunID, field.TypeUUID, value)
	}
	if value, ok := aeuo.mutation.LastSeenAt(); ok {
		_spec.SetField(assetedge.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := aeuo.mutation.SupersededAt(); ok {
		_spec.SetField(assetedge.FieldSupersededAt, field.TypeTime, value)
	}
	if aeuo.mutation.SupersededAtCleared() {
		_spec.ClearField(assetedge.FieldSupersededAt, field.TypeTime)
	}
	_node = &AssetEdge{config: aeuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aeuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assetedge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aeuo.mutation.done = true
	return _node, nil
}
