// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/assetversion"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
)

// AssetVersionQuery is the builder for querying AssetVersion entities.
type AssetVersionQuery struct {
	config
	ctx        *QueryContext
	order      []assetversion.OrderOption
	inters     []Interceptor
	predicates []predicate.AssetVersion
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AssetVersionQuery builder.
func (avq *AssetVersionQuery) Where(ps ...predicate.AssetVersion) *AssetVersionQuery {
	avq.predicates = append(avq.predicates, ps...)
	return avq
}

// Limit the number of records to be returned by this query.
func (avq *AssetVersionQuery) Limit(limit int) *AssetVersionQuery {
	avq.ctx.Limit = &limit
	return avq
}

// Offset to start from.
func (avq *AssetVersionQuery) Offset(offset int) *AssetVersionQuery {
	avq.ctx.Offset = &offset
	return avq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (avq *AssetVersionQuery) Unique(unique bool) *AssetVersionQuery {
	avq.ctx.Unique = &unique
	return avq
}

// Order specifies how the records should be ordered.
func (avq *AssetVersionQuery) Order(o ...assetversion.OrderOption) *AssetVersionQuery {
	avq.order = append(avq.order, o...)
	return avq
}

// First returns the first AssetVersion entity from the query.
// Returns a *NotFoundError when no AssetVersion was found.
func (avq *AssetVersionQuery) First(ctx context.Context) (*AssetVersion, error) {
	nodes, err := avq.Limit(1).All(setContextOp(ctx, avq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{assetversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (avq *AssetVersionQuery) FirstX(ctx context.Context) *AssetVersion {
	node, err := avq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AssetVersion ID from the query.
// Returns a *NotFoundError when no AssetVersion ID was found.
func (avq *AssetVersionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = avq.Limit(1).IDs(setContextOp(ctx, avq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{assetversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (avq *AssetVersionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := avq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AssetVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AssetVersion entity is found.
// Returns a *NotFoundError when no AssetVersion entities are found.
func (avq *AssetVersionQuery) Only(ctx context.Context) (*AssetVersion, error) {
	nodes, err := avq.Limit(2).All(setContextOp(ctx, avq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{assetversion.Label}
	default:
		return nil, &NotSingularError{assetversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (avq *AssetVersionQuery) OnlyX(ctx context.Context) *AssetVersion {
	node, err := avq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AssetVersion ID in the query.
// Returns a *NotSingularError when more than one AssetVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (avq *AssetVersionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = avq.Limit(2).IDs(setContextOp(ctx, avq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{assetversion.Label}
	default:
		err = &NotSingularError{assetversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (avq *AssetVersionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := avq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AssetVersions.
func (avq *AssetVersionQuery) All(ctx context.Context) ([]*AssetVersion, error) {
	ctx = setContextOp(ctx, avq.ctx, ent.OpQueryAll)
	if err := avq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AssetVersion, *AssetVersionQuery]()
	return withInterceptors[[]*AssetVersion](ctx, avq, qr, avq.inters)
}

// AllX is like All, but panics if an error occurs.
func (avq *AssetVersionQuery) AllX(ctx context.Context) []*AssetVersion {
	nodes, err := avq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AssetVersion IDs.
func (avq *AssetVersionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if avq.ctx.Unique == nil && avq.path != nil {
		avq.Unique(true)
	}
	ctx = setContextOp(ctx, avq.ctx, ent.OpQueryIDs)
	if err = avq.Select(assetversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (avq *AssetVersionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := avq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (avq *AssetVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, avq.ctx, ent.OpQueryCount)
	if err := avq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, avq, querierCount[*AssetVersionQuery](), avq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (avq *AssetVersionQuery) CountX(ctx context.Context) int {
	count, err := avq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (avq *AssetVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, avq.ctx, ent.OpQueryExist)
	switch _, err := avq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (avq *AssetVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := avq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AssetVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (avq *AssetVersionQuery) Clone() *AssetVersionQuery {
	if avq == nil {
		return nil
	}
	return &AssetVersionQuery{
		config:     avq.config,
		ctx:        avq.ctx.Clone(),
		order:      append([]assetversion.OrderOption{}, avq.order...),
		inters:     append([]Interceptor{}, avq.inters...),
		predicates: append([]predicate.AssetVersion{}, avq.predicates...),
		// clone intermediate query.
		sql:  avq.sql.Clone(),
		path: avq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Asset string `json:"asset,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AssetVersion.Query().
//		GroupBy(assetversion.FieldAsset).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (avq *AssetVersionQuery) GroupBy(field string, fields ...string) *AssetVersionGroupBy {
	avq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AssetVersionGroupBy{build: avq}
	grbuild.flds = &avq.ctx.Fields
	grbuild.label = assetversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Asset string `json:"asset,omitempty"`
//	}
//
//	client.AssetVersion.Query().
//		Select(assetversion.FieldAsset).
//		Scan(ctx, &v)
func (avq *AssetVersionQuery) Select(fields ...string) *AssetVersionSelect {
	avq.ctx.Fields = append(avq.ctx.Fields, fields...)
	sbuild := &AssetVersionSelect{AssetVersionQuery: avq}
	sbuild.label = assetversion.Label
	sbuild.flds, sbuild.scan = &avq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AssetVersionSelect configured with the given aggregations.
func (avq *AssetVersionQuery) Aggregate(fns ...AggregateFunc) *AssetVersionSelect {
	return avq.Select().Aggregate(fns...)
}

func (avq *AssetVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range avq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, avq); err != nil {
				return err
			}
		}
	}
	for _, f := range avq.ctx.Fields {
		if !assetversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if avq.path != nil {
		prev, err := avq.path(ctx)
		if err != nil {
			return err
		}
		avq.sql = prev
	}
	return nil
}

func (avq *AssetVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AssetVersion, error) {
	var (
		nodes = []*AssetVersion{}
		_spec = avq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AssetVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AssetVersion{config: avq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, avq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (avq *AssetVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := avq.querySpec()
	_spec.Node.Columns = avq.ctx.Fields
	if len(avq.ctx.Fields) > 0 {
		_spec.Unique = avq.ctx.Unique != nil && *avq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, avq.driver, _spec)
}

func (avq *AssetVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(assetversion.Table, assetversion.Columns, sqlgraph.NewFieldSpec(assetversion.FieldID, field.TypeUUID))
	_spec.From = avq.sql
	if unique := avq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if avq.path != nil {
		_spec.Unique = true
	}
	if fields := avq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assetversion.FieldID)
		for i := range fields {
			if fields[i] != assetversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := avq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := avq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := avq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := avq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (avq *AssetVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(avq.driver.Dialect())
	t1 := builder.Table(assetversion.Table)
	columns := avq.ctx.Fields
	if len(columns) == 0 {
		columns = assetversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if avq.sql != nil {
		selector = avq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if avq.ctx.Unique != nil && *avq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range avq.predicates {
		p(selector)
	}
	for _, p := range avq.order {
		p(selector)
	}
	if offset := avq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := avq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AssetVersionGroupBy is the group-by builder for AssetVersion entities.
type AssetVersionGroupBy struct {
	selector
	build *AssetVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (avgb *AssetVersionGroupBy) Aggregate(fns ...AggregateFunc) *AssetVersionGroupBy {
	avgb.fns = append(avgb.fns, fns...)
	return avgb
}

// Scan applies the selector query and scans the result into the given value.
func (avgb *AssetVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, avgb.build.ctx, ent.OpQueryGroupBy)
	if err := avgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssetVersionQuery, *AssetVersionGroupBy](ctx, avgb.build, avgb, avgb.build.inters, v)
}

func (avgb *AssetVersionGroupBy) sqlScan(ctx context.Context, root *AssetVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(avgb.fns))
	for _, fn := range avgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*avgb.flds)+len(avgb.fns))
		for _, f := range *avgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*avgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := avgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AssetVersionSelect is the builder for selecting fields of AssetVersion entities.
type AssetVersionSelect struct {
	*AssetVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (avs *AssetVersionSelect) Aggregate(fns ...AggregateFunc) *AssetVersionSelect {
	avs.fns = append(avs.fns, fns...)
	return avs
}

// Scan applies the selector query and scans the result into the given value.
func (avs *AssetVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, avs.ctx, ent.OpQuerySelect)
	if err := avs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssetVersionQuery, *AssetVersionSelect](ctx, avs.AssetVersionQuery, avs, avs.inters, v)
}

func (avs *AssetVersionSelect) sqlScan(ctx context.Context, root *AssetVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(avs.fns))
	for _, fn := range avs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*avs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := avs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
