// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/assetmetadata"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
)

// AssetMetadataQuery is the builder for querying AssetMetadata entities.
type AssetMetadataQuery struct {
	config
	ctx        *QueryContext
	order      []assetmetadata.OrderOption
	inters     []Interceptor
	predicates []predicate.AssetMetadata
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AssetMetadataQuery builder.
func (amq *AssetMetadataQuery) Where(ps ...predicate.AssetMetadata) *AssetMetadataQuery {
	amq.predicates = append(amq.predicates, ps...)
	return amq
}

// Limit the number of records to be returned by this query.
func (amq *AssetMetadataQuery) Limit(limit int) *AssetMetadataQuery {
	amq.ctx.Limit = &limit
	return amq
}

// Offset to start from.
func (amq *AssetMetadataQuery) Offset(offset int) *AssetMetadataQuery {
	amq.ctx.Offset = &offset
	return amq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (amq *AssetMetadataQuery) Unique(unique bool) *AssetMetadataQuery {
	amq.ctx.Unique = &unique
	return amq
}

// Order specifies how the records should be ordered.
func (amq *AssetMetadataQuery) Order(o ...assetmetadata.OrderOption) *AssetMetadataQuery {
	amq.order = append(amq.order, o...)
	return amq
}

// First returns the first AssetMetadata entity from the query.
// Returns a *NotFoundError when no AssetMetadata was found.
func (amq *AssetMetadataQuery) First(ctx context.Context) (*AssetMetadata, error) {
	nodes, err := amq.Limit(1).All(setContextOp(ctx, amq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{assetmetadata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (amq *AssetMetadataQuery) FirstX(ctx context.Context) *AssetMetadata {
	node, err := amq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AssetMetadata ID from the query.
// Returns a *NotFoundError when no AssetMetadata ID was found.
func (amq *AssetMetadataQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = amq.Limit(1).IDs(setContextOp(ctx, amq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{assetmetadata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (amq *AssetMetadataQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := amq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AssetMetadata entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AssetMetadata entity is found.
// Returns a *NotFoundError when no AssetMetadata entities are found.
func (amq *AssetMetadataQuery) Only(ctx context.Context) (*AssetMetadata, error) {
	nodes, err := amq.Limit(2).All(setContextOp(ctx, amq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{assetmetadata.Label}
	default:
		return nil, &NotSingularError{assetmetadata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (amq *AssetMetadataQuery) OnlyX(ctx context.Context) *AssetMetadata {
	node, err := amq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AssetMetadata ID in the query.
// Returns a *NotSingularError when more than one AssetMetadata ID is found.
// Returns a *NotFoundError when no entities are found.
func (amq *AssetMetadataQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = amq.Limit(2).IDs(setContextOp(ctx, amq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{assetmetadata.Label}
	default:
		err = &NotSingularError{assetmetadata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (amq *AssetMetadataQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := amq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AssetMetadataSlice.
func (amq *AssetMetadataQuery) All(ctx context.Context) ([]*AssetMetadata, error) {
	ctx = setContextOp(ctx, amq.ctx, ent.OpQueryAll)
	if err := amq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AssetMetadata, *AssetMetadataQuery]()
	return withInterceptors[[]*AssetMetadata](ctx, amq, qr, amq.inters)
}

// AllX is like All, but panics if an error occurs.
func (amq *AssetMetadataQuery) AllX(ctx context.Context) []*AssetMetadata {
	nodes, err := amq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AssetMetadata IDs.
func (amq *AssetMetadataQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if amq.ctx.Unique == nil && amq.path != nil {
		amq.Unique(true)
	}
	ctx = setContextOp(ctx, amq.ctx, ent.OpQueryIDs)
	if err = amq.Select(assetmetadata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (amq *AssetMetadataQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := amq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (amq *AssetMetadataQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, amq.ctx, ent.OpQueryCount)
	if err := amq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, amq, querierCount[*AssetMetadataQuery](), amq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (amq *AssetMetadataQuery) CountX(ctx context.Context) int {
	count, err := amq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (amq *AssetMetadataQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, amq.ctx, ent.OpQueryExist)
	switch _, err := amq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (amq *AssetMetadataQuery) ExistX(ctx context.Context) bool {
	exist, err := amq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AssetMetadataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (amq *AssetMetadataQuery) Clone() *AssetMetadataQuery {
	if amq == nil {
		return nil
	}
	return &AssetMetadataQuery{
		config:     amq.config,
		ctx:        amq.ctx.Clone(),
		order:      append([]assetmetadata.OrderOption{}, amq.order...),
		inters:     append([]Interceptor{}, amq.inters...),
		predicates: append([]predicate.AssetMetadata{}, amq.predicates...),
		// clone intermediate query.
		sql:  amq.sql.Clone(),
		path: amq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Asset string `json:"asset,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AssetMetadata.Query().
//		GroupBy(assetmetadata.FieldAsset).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (amq *AssetMetadataQuery) GroupBy(field string, fields ...string) *AssetMetadataGroupBy {
	amq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AssetMetadataGroupBy{build: amq}
	grbuild.flds = &amq.ctx.Fields
	grbuild.label = assetmetadata.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Asset string `json:"asset,omitempty"`
//	}
//
//	client.AssetMetadata.Query().
//		Select(assetmetadata.FieldAsset).
//		Scan(ctx, &v)
func (amq *AssetMetadataQuery) Select(fields ...string) *AssetMetadataSelect {
	amq.ctx.Fields = append(amq.ctx.Fields, fields...)
	sbuild := &AssetMetadataSelect{AssetMetadataQuery: amq}
	sbuild.label = assetmetadata.Label
	sbuild.flds, sbuild.scan = &amq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AssetMetadataSelect configured with the given aggregations.
func (amq *AssetMetadataQuery) Aggregate(fns ...AggregateFunc) *AssetMetadataSelect {
	return amq.Select().Aggregate(fns...)
}

func (amq *AssetMetadataQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range amq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, amq); err != nil {
				return err
			}
		}
	}
	for _, f := range amq.ctx.Fields {
		if !assetmetadata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if amq.path != nil {
		prev, err := amq.path(ctx)
		if err != nil {
			return err
		}
		amq.sql = prev
	}
	return nil
}

func (amq *AssetMetadataQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AssetMetadata, error) {
	var (
		nodes = []*AssetMetadata{}
		_spec = amq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AssetMetadata).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AssetMetadata{config: amq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, amq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (amq *AssetMetadataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := amq.querySpec()
	_spec.Node.Columns = amq.ctx.Fields
	if len(amq.ctx.Fields) > 0 {
		_spec.Unique = amq.ctx.Unique != nil && *amq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, amq.driver, _spec)
}

func (amq *AssetMetadataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(assetmetadata.Table, assetmetadata.Columns, sqlgraph.NewFieldSpec(assetmetadata.FieldID, field.TypeUUID))
	_spec.From = amq.sql
	if unique := amq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if amq.path != nil {
		_spec.Unique = true
	}
	if fields := amq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assetmetadata.FieldID)
		for i := range fields {
			if fields[i] != assetmetadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := amq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := amq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := amq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := amq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (amq *AssetMetadataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(amq.driver.Dialect())
	t1 := builder.Table(assetmetadata.Table)
	columns := amq.ctx.Fields
	if len(columns) == 0 {
		columns = assetmetadata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if amq.sql != nil {
		selector = amq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if amq.ctx.Unique != nil && *amq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range amq.predicates {
		p(selector)
	}
	for _, p := range amq.order {
		p(selector)
	}
	if offset := amq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := amq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AssetMetadataGroupBy is the group-by builder for AssetMetadata entities.
type AssetMetadataGroupBy struct {
	selector
	build *AssetMetadataQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (amgb *AssetMetadataGroupBy) Aggregate(fns ...AggregateFunc) *AssetMetadataGroupBy {
	amgb.fns = append(amgb.fns, fns...)
	return amgb
}

// Scan applies the selector query and scans the result into the given value.
func (amgb *AssetMetadataGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, amgb.build.ctx, ent.OpQueryGroupBy)
	if err := amgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssetMetadataQuery, *AssetMetadataGroupBy](ctx, amgb.build, amgb, amgb.build.inters, v)
}

func (amgb *AssetMetadataGroupBy) sqlScan(ctx context.Context, root *AssetMetadataQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(amgb.fns))
	for _, fn := range amgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*amgb.flds)+len(amgb.fns))
		for _, f := range *amgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*amgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := amgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AssetMetadataSelect is the builder for selecting fields of AssetMetadata entities.
type AssetMetadataSelect struct {
	*AssetMetadataQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ams *AssetMetadataSelect) Aggregate(fns ...AggregateFunc) *AssetMetadataSelect {
	ams.fns = append(ams.fns, fns...)
	return ams
}

// Scan applies the selector query and scans the result into the given value.
func (ams *AssetMetadataSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ams.ctx, ent.OpQuerySelect)
	if err := ams.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssetMetadataQuery, *AssetMetadataSelect](ctx, ams.AssetMetadataQuery, ams, ams.inters, v)
}

func (ams *AssetMetadataSelect) sqlScan(ctx context.Context, root *AssetMetadataQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ams.fns))
	for _, fn := range ams.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ams.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ams.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
