// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/backfill"
)

// Backfill is the model entity for the Backfill schema.
type Backfill struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// AssetName holds the value of the "asset_name" field.
	AssetName string `json:"asset_name,omitempty"`
	// PartitionSpec holds the value of the "partition_spec" field.
	PartitionSpec string `json:"partition_spec,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TotalPartitions holds the value of the "total_partitions" field.
	TotalPartitions int `json:"total_partitions,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt time.Time `json:"submitted_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Backfill) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backfill.FieldTotalPartitions:
			values[i] = new(sql.NullInt64)
		case backfill.FieldAssetName, backfill.FieldPartitionSpec, backfill.FieldStatus:
			values[i] = new(sql.NullString)
		case backfill.FieldSubmittedAt, backfill.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case backfill.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Backfill fields.
func (b *Backfill) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backfill.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				b.ID = *value
			}
		case backfill.FieldAssetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_name", values[i])
			} else if value.Valid {
				b.AssetName = value.String
			}
		case backfill.FieldPartitionSpec:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field partition_spec", values[i])
			} else if value.Valid {
				b.PartitionSpec = value.String
			}
		case backfill.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				b.Status = value.String
			}
		case backfill.FieldTotalPartitions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_partitions", values[i])
			} else if value.Valid {
				b.TotalPartitions = int(value.Int64)
			}
		case backfill.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				b.SubmittedAt = value.Time
			}
		case backfill.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				b.CompletedAt = new(time.Time)
				*b.CompletedAt = value.Time
			}
		default:
			b.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Backfill.
// This includes values selected through modifiers, order, etc.
func (b *Backfill) Value(name string) (ent.Value, error) {
	return b.selectValues.Get(name)
}

// Update returns a builder for updating this Backfill.
// Note that you need to call Backfill.Unwrap() before calling this method if this Backfill
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Backfill) Update() *BackfillUpdateOne {
	return NewBackfillClient(b.config).UpdateOne(b)
}

// Unwrap unwraps the Backfill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (b *Backfill) Unwrap() *Backfill {
	_tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Backfill is not a transactional entity")
	}
	b.config.driver = _tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Backfill) String() string {
	var builder strings.Builder
	builder.WriteString("Backfill(")
	builder.WriteString(fmt.Sprintf("id=%v, ", b.ID))
	builder.WriteString("asset_name=")
	builder.WriteString(b.AssetName)
	builder.WriteString(", ")
	builder.WriteString("partition_spec=")
	builder.WriteString(b.PartitionSpec)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(b.Status)
	builder.WriteString(", ")
	builder.WriteString("total_partitions=")
	builder.WriteString(fmt.Sprintf("%v", b.TotalPartitions))
	builder.WriteString(", ")
	builder.WriteString("submitted_at=")
	builder.WriteString(b.SubmittedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := b.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Backfills is a parsable slice of Backfill.
type Backfills []*Backfill
