// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/kanpon/data-governance/internal/storage/ent/concurrencytoken"
	"github.com/kanpon/data-governance/internal/storage/ent/eventlog"
	"github.com/kanpon/data-governance/internal/storage/ent/invitetoken"
	"github.com/kanpon/data-governance/internal/storage/ent/run"
	"github.com/kanpon/data-governance/internal/storage/ent/runstep"
	"github.com/kanpon/data-governance/internal/storage/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ConcurrencyToken is the client for interacting with the ConcurrencyToken builders.
	ConcurrencyToken *ConcurrencyTokenClient
	// EventLog is the client for interacting with the EventLog builders.
	EventLog *EventLogClient
	// InviteToken is the client for interacting with the InviteToken builders.
	InviteToken *InviteTokenClient
	// Run is the client for interacting with the Run builders.
	Run *RunClient
	// RunStep is the client for interacting with the RunStep builders.
	RunStep *RunStepClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ConcurrencyToken = NewConcurrencyTokenClient(c.config)
	c.EventLog = NewEventLogClient(c.config)
	c.InviteToken = NewInviteTokenClient(c.config)
	c.Run = NewRunClient(c.config)
	c.RunStep = NewRunStepClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		ConcurrencyToken: NewConcurrencyTokenClient(cfg),
		EventLog:         NewEventLogClient(cfg),
		InviteToken:      NewInviteTokenClient(cfg),
		Run:              NewRunClient(cfg),
		RunStep:          NewRunStepClient(cfg),
		User:             NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		ConcurrencyToken: NewConcurrencyTokenClient(cfg),
		EventLog:         NewEventLogClient(cfg),
		InviteToken:      NewInviteTokenClient(cfg),
		Run:              NewRunClient(cfg),
		RunStep:          NewRunStepClient(cfg),
		User:             NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ConcurrencyToken.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.ConcurrencyToken, c.EventLog, c.InviteToken, c.Run, c.RunStep, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.ConcurrencyToken, c.EventLog, c.InviteToken, c.Run, c.RunStep, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ConcurrencyTokenMutation:
		return c.ConcurrencyToken.mutate(ctx, m)
	case *EventLogMutation:
		return c.EventLog.mutate(ctx, m)
	case *InviteTokenMutation:
		return c.InviteToken.mutate(ctx, m)
	case *RunMutation:
		return c.Run.mutate(ctx, m)
	case *RunStepMutation:
		return c.RunStep.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ConcurrencyTokenClient is a client for the ConcurrencyToken schema.
type ConcurrencyTokenClient struct {
	config
}

// NewConcurrencyTokenClient returns a client for the ConcurrencyToken from the given config.
func NewConcurrencyTokenClient(c config) *ConcurrencyTokenClient {
	return &ConcurrencyTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `concurrencytoken.Hooks(f(g(h())))`.
func (c *ConcurrencyTokenClient) Use(hooks ...Hook) {
	c.hooks.ConcurrencyToken = append(c.hooks.ConcurrencyToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `concurrencytoken.Intercept(f(g(h())))`.
func (c *ConcurrencyTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.ConcurrencyToken = append(c.inters.ConcurrencyToken, interceptors...)
}

// Create returns a builder for creating a ConcurrencyToken entity.
func (c *ConcurrencyTokenClient) Create() *ConcurrencyTokenCreate {
	mutation := newConcurrencyTokenMutation(c.config, OpCreate)
	return &ConcurrencyTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ConcurrencyToken entities.
func (c *ConcurrencyTokenClient) CreateBulk(builders ...*ConcurrencyTokenCreate) *ConcurrencyTokenCreateBulk {
	return &ConcurrencyTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ConcurrencyTokenClient) MapCreateBulk(slice any, setFunc func(*ConcurrencyTokenCreate, int)) *ConcurrencyTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ConcurrencyTokenCreateBulk{err: fmt.Errorf("calling to ConcurrencyTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ConcurrencyTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ConcurrencyTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ConcurrencyToken.
func (c *ConcurrencyTokenClient) Update() *ConcurrencyTokenUpdate {
	mutation := newConcurrencyTokenMutation(c.config, OpUpdate)
	return &ConcurrencyTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ConcurrencyTokenClient) UpdateOne(ct *ConcurrencyToken) *ConcurrencyTokenUpdateOne {
	mutation := newConcurrencyTokenMutation(c.config, OpUpdateOne, withConcurrencyToken(ct))
	return &ConcurrencyTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ConcurrencyTokenClient) UpdateOneID(id uuid.UUID) *ConcurrencyTokenUpdateOne {
	mutation := newConcurrencyTokenMutation(c.config, OpUpdateOne, withConcurrencyTokenID(id))
	return &ConcurrencyTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ConcurrencyToken.
func (c *ConcurrencyTokenClient) Delete() *ConcurrencyTokenDelete {
	mutation := newConcurrencyTokenMutation(c.config, OpDelete)
	return &ConcurrencyTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ConcurrencyTokenClient) DeleteOne(ct *ConcurrencyToken) *ConcurrencyTokenDeleteOne {
	return c.DeleteOneID(ct.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ConcurrencyTokenClient) DeleteOneID(id uuid.UUID) *ConcurrencyTokenDeleteOne {
	builder := c.Delete().Where(concurrencytoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ConcurrencyTokenDeleteOne{builder}
}

// Query returns a query builder for ConcurrencyToken.
func (c *ConcurrencyTokenClient) Query() *ConcurrencyTokenQuery {
	return &ConcurrencyTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeConcurrencyToken},
		inters: c.Interceptors(),
	}
}

// Get returns a ConcurrencyToken entity by its id.
func (c *ConcurrencyTokenClient) Get(ctx context.Context, id uuid.UUID) (*ConcurrencyToken, error) {
	return c.Query().Where(concurrencytoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ConcurrencyTokenClient) GetX(ctx context.Context, id uuid.UUID) *ConcurrencyToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ConcurrencyTokenClient) Hooks() []Hook {
	return c.hooks.ConcurrencyToken
}

// Interceptors returns the client interceptors.
func (c *ConcurrencyTokenClient) Interceptors() []Interceptor {
	return c.inters.ConcurrencyToken
}

func (c *ConcurrencyTokenClient) mutate(ctx context.Context, m *ConcurrencyTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ConcurrencyTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ConcurrencyTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ConcurrencyTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ConcurrencyTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ConcurrencyToken mutation op: %q", m.Op())
	}
}

// EventLogClient is a client for the EventLog schema.
type EventLogClient struct {
	config
}

// NewEventLogClient returns a client for the EventLog from the given config.
func NewEventLogClient(c config) *EventLogClient {
	return &EventLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `eventlog.Hooks(f(g(h())))`.
func (c *EventLogClient) Use(hooks ...Hook) {
	c.hooks.EventLog = append(c.hooks.EventLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `eventlog.Intercept(f(g(h())))`.
func (c *EventLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.EventLog = append(c.inters.EventLog, interceptors...)
}

// Create returns a builder for creating a EventLog entity.
func (c *EventLogClient) Create() *EventLogCreate {
	mutation := newEventLogMutation(c.config, OpCreate)
	return &EventLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EventLog entities.
func (c *EventLogClient) CreateBulk(builders ...*EventLogCreate) *EventLogCreateBulk {
	return &EventLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EventLogClient) MapCreateBulk(slice any, setFunc func(*EventLogCreate, int)) *EventLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EventLogCreateBulk{err: fmt.Errorf("calling to EventLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EventLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EventLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EventLog.
func (c *EventLogClient) Update() *EventLogUpdate {
	mutation := newEventLogMutation(c.config, OpUpdate)
	return &EventLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EventLogClient) UpdateOne(el *EventLog) *EventLogUpdateOne {
	mutation := newEventLogMutation(c.config, OpUpdateOne, withEventLog(el))
	return &EventLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EventLogClient) UpdateOneID(id uuid.UUID) *EventLogUpdateOne {
	mutation := newEventLogMutation(c.config, OpUpdateOne, withEventLogID(id))
	return &EventLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EventLog.
func (c *EventLogClient) Delete() *EventLogDelete {
	mutation := newEventLogMutation(c.config, OpDelete)
	return &EventLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EventLogClient) DeleteOne(el *EventLog) *EventLogDeleteOne {
	return c.DeleteOneID(el.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EventLogClient) DeleteOneID(id uuid.UUID) *EventLogDeleteOne {
	builder := c.Delete().Where(eventlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EventLogDeleteOne{builder}
}

// Query returns a query builder for EventLog.
func (c *EventLogClient) Query() *EventLogQuery {
	return &EventLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEventLog},
		inters: c.Interceptors(),
	}
}

// Get returns a EventLog entity by its id.
func (c *EventLogClient) Get(ctx context.Context, id uuid.UUID) (*EventLog, error) {
	return c.Query().Where(eventlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EventLogClient) GetX(ctx context.Context, id uuid.UUID) *EventLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EventLogClient) Hooks() []Hook {
	return c.hooks.EventLog
}

// Interceptors returns the client interceptors.
func (c *EventLogClient) Interceptors() []Interceptor {
	return c.inters.EventLog
}

func (c *EventLogClient) mutate(ctx context.Context, m *EventLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EventLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EventLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EventLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EventLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EventLog mutation op: %q", m.Op())
	}
}

// InviteTokenClient is a client for the InviteToken schema.
type InviteTokenClient struct {
	config
}

// NewInviteTokenClient returns a client for the InviteToken from the given config.
func NewInviteTokenClient(c config) *InviteTokenClient {
	return &InviteTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `invitetoken.Hooks(f(g(h())))`.
func (c *InviteTokenClient) Use(hooks ...Hook) {
	c.hooks.InviteToken = append(c.hooks.InviteToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `invitetoken.Intercept(f(g(h())))`.
func (c *InviteTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.InviteToken = append(c.inters.InviteToken, interceptors...)
}

// Create returns a builder for creating a InviteToken entity.
func (c *InviteTokenClient) Create() *InviteTokenCreate {
	mutation := newInviteTokenMutation(c.config, OpCreate)
	return &InviteTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of InviteToken entities.
func (c *InviteTokenClient) CreateBulk(builders ...*InviteTokenCreate) *InviteTokenCreateBulk {
	return &InviteTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InviteTokenClient) MapCreateBulk(slice any, setFunc func(*InviteTokenCreate, int)) *InviteTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InviteTokenCreateBulk{err: fmt.Errorf("calling to InviteTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InviteTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InviteTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for InviteToken.
func (c *InviteTokenClient) Update() *InviteTokenUpdate {
	mutation := newInviteTokenMutation(c.config, OpUpdate)
	return &InviteTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InviteTokenClient) UpdateOne(it *InviteToken) *InviteTokenUpdateOne {
	mutation := newInviteTokenMutation(c.config, OpUpdateOne, withInviteToken(it))
	return &InviteTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InviteTokenClient) UpdateOneID(id uuid.UUID) *InviteTokenUpdateOne {
	mutation := newInviteTokenMutation(c.config, OpUpdateOne, withInviteTokenID(id))
	return &InviteTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for InviteToken.
func (c *InviteTokenClient) Delete() *InviteTokenDelete {
	mutation := newInviteTokenMutation(c.config, OpDelete)
	return &InviteTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InviteTokenClient) DeleteOne(it *InviteToken) *InviteTokenDeleteOne {
	return c.DeleteOneID(it.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InviteTokenClient) DeleteOneID(id uuid.UUID) *InviteTokenDeleteOne {
	builder := c.Delete().Where(invitetoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InviteTokenDeleteOne{builder}
}

// Query returns a query builder for InviteToken.
func (c *InviteTokenClient) Query() *InviteTokenQuery {
	return &InviteTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInviteToken},
		inters: c.Interceptors(),
	}
}

// Get returns a InviteToken entity by its id.
func (c *InviteTokenClient) Get(ctx context.Context, id uuid.UUID) (*InviteToken, error) {
	return c.Query().Where(invitetoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InviteTokenClient) GetX(ctx context.Context, id uuid.UUID) *InviteToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *InviteTokenClient) Hooks() []Hook {
	return c.hooks.InviteToken
}

// Interceptors returns the client interceptors.
func (c *InviteTokenClient) Interceptors() []Interceptor {
	return c.inters.InviteToken
}

func (c *InviteTokenClient) mutate(ctx context.Context, m *InviteTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InviteTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InviteTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InviteTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InviteTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown InviteToken mutation op: %q", m.Op())
	}
}

// RunClient is a client for the Run schema.
type RunClient struct {
	config
}

// NewRunClient returns a client for the Run from the given config.
func NewRunClient(c config) *RunClient {
	return &RunClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `run.Hooks(f(g(h())))`.
func (c *RunClient) Use(hooks ...Hook) {
	c.hooks.Run = append(c.hooks.Run, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `run.Intercept(f(g(h())))`.
func (c *RunClient) Intercept(interceptors ...Interceptor) {
	c.inters.Run = append(c.inters.Run, interceptors...)
}

// Create returns a builder for creating a Run entity.
func (c *RunClient) Create() *RunCreate {
	mutation := newRunMutation(c.config, OpCreate)
	return &RunCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Run entities.
func (c *RunClient) CreateBulk(builders ...*RunCreate) *RunCreateBulk {
	return &RunCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RunClient) MapCreateBulk(slice any, setFunc func(*RunCreate, int)) *RunCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RunCreateBulk{err: fmt.Errorf("calling to RunClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RunCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RunCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Run.
func (c *RunClient) Update() *RunUpdate {
	mutation := newRunMutation(c.config, OpUpdate)
	return &RunUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RunClient) UpdateOne(r *Run) *RunUpdateOne {
	mutation := newRunMutation(c.config, OpUpdateOne, withRun(r))
	return &RunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RunClient) UpdateOneID(id uuid.UUID) *RunUpdateOne {
	mutation := newRunMutation(c.config, OpUpdateOne, withRunID(id))
	return &RunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Run.
func (c *RunClient) Delete() *RunDelete {
	mutation := newRunMutation(c.config, OpDelete)
	return &RunDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RunClient) DeleteOne(r *Run) *RunDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RunClient) DeleteOneID(id uuid.UUID) *RunDeleteOne {
	builder := c.Delete().Where(run.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RunDeleteOne{builder}
}

// Query returns a query builder for Run.
func (c *RunClient) Query() *RunQuery {
	return &RunQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRun},
		inters: c.Interceptors(),
	}
}

// Get returns a Run entity by its id.
func (c *RunClient) Get(ctx context.Context, id uuid.UUID) (*Run, error) {
	return c.Query().Where(run.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RunClient) GetX(ctx context.Context, id uuid.UUID) *Run {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RunClient) Hooks() []Hook {
	return c.hooks.Run
}

// Interceptors returns the client interceptors.
func (c *RunClient) Interceptors() []Interceptor {
	return c.inters.Run
}

func (c *RunClient) mutate(ctx context.Context, m *RunMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RunCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RunUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RunDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Run mutation op: %q", m.Op())
	}
}

// RunStepClient is a client for the RunStep schema.
type RunStepClient struct {
	config
}

// NewRunStepClient returns a client for the RunStep from the given config.
func NewRunStepClient(c config) *RunStepClient {
	return &RunStepClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `runstep.Hooks(f(g(h())))`.
func (c *RunStepClient) Use(hooks ...Hook) {
	c.hooks.RunStep = append(c.hooks.RunStep, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `runstep.Intercept(f(g(h())))`.
func (c *RunStepClient) Intercept(interceptors ...Interceptor) {
	c.inters.RunStep = append(c.inters.RunStep, interceptors...)
}

// Create returns a builder for creating a RunStep entity.
func (c *RunStepClient) Create() *RunStepCreate {
	mutation := newRunStepMutation(c.config, OpCreate)
	return &RunStepCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RunStep entities.
func (c *RunStepClient) CreateBulk(builders ...*RunStepCreate) *RunStepCreateBulk {
	return &RunStepCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RunStepClient) MapCreateBulk(slice any, setFunc func(*RunStepCreate, int)) *RunStepCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RunStepCreateBulk{err: fmt.Errorf("calling to RunStepClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RunStepCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RunStepCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RunStep.
func (c *RunStepClient) Update() *RunStepUpdate {
	mutation := newRunStepMutation(c.config, OpUpdate)
	return &RunStepUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RunStepClient) UpdateOne(rs *RunStep) *RunStepUpdateOne {
	mutation := newRunStepMutation(c.config, OpUpdateOne, withRunStep(rs))
	return &RunStepUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RunStepClient) UpdateOneID(id uuid.UUID) *RunStepUpdateOne {
	mutation := newRunStepMutation(c.config, OpUpdateOne, withRunStepID(id))
	return &RunStepUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RunStep.
func (c *RunStepClient) Delete() *RunStepDelete {
	mutation := newRunStepMutation(c.config, OpDelete)
	return &RunStepDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RunStepClient) DeleteOne(rs *RunStep) *RunStepDeleteOne {
	return c.DeleteOneID(rs.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RunStepClient) DeleteOneID(id uuid.UUID) *RunStepDeleteOne {
	builder := c.Delete().Where(runstep.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RunStepDeleteOne{builder}
}

// Query returns a query builder for RunStep.
func (c *RunStepClient) Query() *RunStepQuery {
	return &RunStepQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRunStep},
		inters: c.Interceptors(),
	}
}

// Get returns a RunStep entity by its id.
func (c *RunStepClient) Get(ctx context.Context, id uuid.UUID) (*RunStep, error) {
	return c.Query().Where(runstep.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RunStepClient) GetX(ctx context.Context, id uuid.UUID) *RunStep {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RunStepClient) Hooks() []Hook {
	return c.hooks.RunStep
}

// Interceptors returns the client interceptors.
func (c *RunStepClient) Interceptors() []Interceptor {
	return c.inters.RunStep
}

func (c *RunStepClient) mutate(ctx context.Context, m *RunStepMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RunStepCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RunStepUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RunStepUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RunStepDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RunStep mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ConcurrencyToken, EventLog, InviteToken, Run, RunStep, User []ent.Hook
	}
	inters struct {
		ConcurrencyToken, EventLog, InviteToken, Run, RunStep, User []ent.Interceptor
	}
)
