// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/kanpon/data-governance/internal/storage/ent/assetedge"
	"github.com/kanpon/data-governance/internal/storage/ent/assetmetadata"
	"github.com/kanpon/data-governance/internal/storage/ent/assetversion"
	"github.com/kanpon/data-governance/internal/storage/ent/backfill"
	"github.com/kanpon/data-governance/internal/storage/ent/columnedge"
	"github.com/kanpon/data-governance/internal/storage/ent/concurrencytoken"
	"github.com/kanpon/data-governance/internal/storage/ent/eventlog"
	"github.com/kanpon/data-governance/internal/storage/ent/invitetoken"
	"github.com/kanpon/data-governance/internal/storage/ent/run"
	"github.com/kanpon/data-governance/internal/storage/ent/runstep"
	"github.com/kanpon/data-governance/internal/storage/ent/schedule"
	"github.com/kanpon/data-governance/internal/storage/ent/schemachange"
	"github.com/kanpon/data-governance/internal/storage/ent/schemaversion"
	"github.com/kanpon/data-governance/internal/storage/ent/sensor"
	"github.com/kanpon/data-governance/internal/storage/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AssetEdge is the client for interacting with the AssetEdge builders.
	AssetEdge *AssetEdgeClient
	// AssetMetadata is the client for interacting with the AssetMetadata builders.
	AssetMetadata *AssetMetadataClient
	// AssetVersion is the client for interacting with the AssetVersion builders.
	AssetVersion *AssetVersionClient
	// Backfill is the client for interacting with the Backfill builders.
	Backfill *BackfillClient
	// ColumnEdge is the client for interacting with the ColumnEdge builders.
	ColumnEdge *ColumnEdgeClient
	// ConcurrencyToken is the client for interacting with the ConcurrencyToken builders.
	ConcurrencyToken *ConcurrencyTokenClient
	// EventLog is the client for interacting with the EventLog builders.
	EventLog *EventLogClient
	// InviteToken is the client for interacting with the InviteToken builders.
	InviteToken *InviteTokenClient
	// Run is the client for interacting with the Run builders.
	Run *RunClient
	// RunStep is the client for interacting with the RunStep builders.
	RunStep *RunStepClient
	// Schedule is the client for interacting with the Schedule builders.
	Schedule *ScheduleClient
	// SchemaChange is the client for interacting with the SchemaChange builders.
	SchemaChange *SchemaChangeClient
	// SchemaVersion is the client for interacting with the SchemaVersion builders.
	SchemaVersion *SchemaVersionClient
	// Sensor is the client for interacting with the Sensor builders.
	Sensor *SensorClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AssetEdge = NewAssetEdgeClient(c.config)
	c.AssetMetadata = NewAssetMetadataClient(c.config)
	c.AssetVersion = NewAssetVersionClient(c.config)
	c.Backfill = NewBackfillClient(c.config)
	c.ColumnEdge = NewColumnEdgeClient(c.config)
	c.ConcurrencyToken = NewConcurrencyTokenClient(c.config)
	c.EventLog = NewEventLogClient(c.config)
	c.InviteToken = NewInviteTokenClient(c.config)
	c.Run = NewRunClient(c.config)
	c.RunStep = NewRunStepClient(c.config)
	c.Schedule = NewScheduleClient(c.config)
	c.SchemaChange = NewSchemaChangeClient(c.config)
	c.SchemaVersion = NewSchemaVersionClient(c.config)
	c.Sensor = NewSensorClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		AssetEdge:        NewAssetEdgeClient(cfg),
		AssetMetadata:    NewAssetMetadataClient(cfg),
		AssetVersion:     NewAssetVersionClient(cfg),
		Backfill:         NewBackfillClient(cfg),
		ColumnEdge:       NewColumnEdgeClient(cfg),
		ConcurrencyToken: NewConcurrencyTokenClient(cfg),
		EventLog:         NewEventLogClient(cfg),
		InviteToken:      NewInviteTokenClient(cfg),
		Run:              NewRunClient(cfg),
		RunStep:          NewRunStepClient(cfg),
		Schedule:         NewScheduleClient(cfg),
		SchemaChange:     NewSchemaChangeClient(cfg),
		SchemaVersion:    NewSchemaVersionClient(cfg),
		Sensor:           NewSensorClient(cfg),
		User:             NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		AssetEdge:        NewAssetEdgeClient(cfg),
		AssetMetadata:    NewAssetMetadataClient(cfg),
		AssetVersion:     NewAssetVersionClient(cfg),
		Backfill:         NewBackfillClient(cfg),
		ColumnEdge:       NewColumnEdgeClient(cfg),
		ConcurrencyToken: NewConcurrencyTokenClient(cfg),
		EventLog:         NewEventLogClient(cfg),
		InviteToken:      NewInviteTokenClient(cfg),
		Run:              NewRunClient(cfg),
		RunStep:          NewRunStepClient(cfg),
		Schedule:         NewScheduleClient(cfg),
		SchemaChange:     NewSchemaChangeClient(cfg),
		SchemaVersion:    NewSchemaVersionClient(cfg),
		Sensor:           NewSensorClient(cfg),
		User:             NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AssetEdge.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AssetEdge, c.AssetMetadata, c.AssetVersion, c.Backfill, c.ColumnEdge,
		c.ConcurrencyToken, c.EventLog, c.InviteToken, c.Run, c.RunStep, c.Schedule,
		c.SchemaChange, c.SchemaVersion, c.Sensor, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AssetEdge, c.AssetMetadata, c.AssetVersion, c.Backfill, c.ColumnEdge,
		c.ConcurrencyToken, c.EventLog, c.InviteToken, c.Run, c.RunStep, c.Schedule,
		c.SchemaChange, c.SchemaVersion, c.Sensor, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AssetEdgeMutation:
		return c.AssetEdge.mutate(ctx, m)
	case *AssetMetadataMutation:
		return c.AssetMetadata.mutate(ctx, m)
	case *AssetVersionMutation:
		return c.AssetVersion.mutate(ctx, m)
	case *BackfillMutation:
		return c.Backfill.mutate(ctx, m)
	case *ColumnEdgeMutation:
		return c.ColumnEdge.mutate(ctx, m)
	case *ConcurrencyTokenMutation:
		return c.ConcurrencyToken.mutate(ctx, m)
	case *EventLogMutation:
		return c.EventLog.mutate(ctx, m)
	case *InviteTokenMutation:
		return c.InviteToken.mutate(ctx, m)
	case *RunMutation:
		return c.Run.mutate(ctx, m)
	case *RunStepMutation:
		return c.RunStep.mutate(ctx, m)
	case *ScheduleMutation:
		return c.Schedule.mutate(ctx, m)
	case *SchemaChangeMutation:
		return c.SchemaChange.mutate(ctx, m)
	case *SchemaVersionMutation:
		return c.SchemaVersion.mutate(ctx, m)
	case *SensorMutation:
		return c.Sensor.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AssetEdgeClient is a client for the AssetEdge schema.
type AssetEdgeClient struct {
	config
}

// NewAssetEdgeClient returns a client for the AssetEdge from the given config.
func NewAssetEdgeClient(c config) *AssetEdgeClient {
	return &AssetEdgeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `assetedge.Hooks(f(g(h())))`.
func (c *AssetEdgeClient) Use(hooks ...Hook) {
	c.hooks.AssetEdge = append(c.hooks.AssetEdge, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `assetedge.Intercept(f(g(h())))`.
func (c *AssetEdgeClient) Intercept(interceptors ...Interceptor) {
	c.inters.AssetEdge = append(c.inters.AssetEdge, interceptors...)
}

// Create returns a builder for creating a AssetEdge entity.
func (c *AssetEdgeClient) Create() *AssetEdgeCreate {
	mutation := newAssetEdgeMutation(c.config, OpCreate)
	return &AssetEdgeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AssetEdge entities.
func (c *AssetEdgeClient) CreateBulk(builders ...*AssetEdgeCreate) *AssetEdgeCreateBulk {
	return &AssetEdgeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AssetEdgeClient) MapCreateBulk(slice any, setFunc func(*AssetEdgeCreate, int)) *AssetEdgeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AssetEdgeCreateBulk{err: fmt.Errorf("calling to AssetEdgeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AssetEdgeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AssetEdgeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AssetEdge.
func (c *AssetEdgeClient) Update() *AssetEdgeUpdate {
	mutation := newAssetEdgeMutation(c.config, OpUpdate)
	return &AssetEdgeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AssetEdgeClient) UpdateOne(ae *AssetEdge) *AssetEdgeUpdateOne {
	mutation := newAssetEdgeMutation(c.config, OpUpdateOne, withAssetEdge(ae))
	return &AssetEdgeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AssetEdgeClient) UpdateOneID(id uuid.UUID) *AssetEdgeUpdateOne {
	mutation := newAssetEdgeMutation(c.config, OpUpdateOne, withAssetEdgeID(id))
	return &AssetEdgeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AssetEdge.
func (c *AssetEdgeClient) Delete() *AssetEdgeDelete {
	mutation := newAssetEdgeMutation(c.config, OpDelete)
	return &AssetEdgeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AssetEdgeClient) DeleteOne(ae *AssetEdge) *AssetEdgeDeleteOne {
	return c.DeleteOneID(ae.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AssetEdgeClient) DeleteOneID(id uuid.UUID) *AssetEdgeDeleteOne {
	builder := c.Delete().Where(assetedge.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AssetEdgeDeleteOne{builder}
}

// Query returns a query builder for AssetEdge.
func (c *AssetEdgeClient) Query() *AssetEdgeQuery {
	return &AssetEdgeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAssetEdge},
		inters: c.Interceptors(),
	}
}

// Get returns a AssetEdge entity by its id.
func (c *AssetEdgeClient) Get(ctx context.Context, id uuid.UUID) (*AssetEdge, error) {
	return c.Query().Where(assetedge.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AssetEdgeClient) GetX(ctx context.Context, id uuid.UUID) *AssetEdge {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AssetEdgeClient) Hooks() []Hook {
	return c.hooks.AssetEdge
}

// Interceptors returns the client interceptors.
func (c *AssetEdgeClient) Interceptors() []Interceptor {
	return c.inters.AssetEdge
}

func (c *AssetEdgeClient) mutate(ctx context.Context, m *AssetEdgeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AssetEdgeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AssetEdgeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AssetEdgeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AssetEdgeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AssetEdge mutation op: %q", m.Op())
	}
}

// AssetMetadataClient is a client for the AssetMetadata schema.
type AssetMetadataClient struct {
	config
}

// NewAssetMetadataClient returns a client for the AssetMetadata from the given config.
func NewAssetMetadataClient(c config) *AssetMetadataClient {
	return &AssetMetadataClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `assetmetadata.Hooks(f(g(h())))`.
func (c *AssetMetadataClient) Use(hooks ...Hook) {
	c.hooks.AssetMetadata = append(c.hooks.AssetMetadata, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `assetmetadata.Intercept(f(g(h())))`.
func (c *AssetMetadataClient) Intercept(interceptors ...Interceptor) {
	c.inters.AssetMetadata = append(c.inters.AssetMetadata, interceptors...)
}

// Create returns a builder for creating a AssetMetadata entity.
func (c *AssetMetadataClient) Create() *AssetMetadataCreate {
	mutation := newAssetMetadataMutation(c.config, OpCreate)
	return &AssetMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AssetMetadata entities.
func (c *AssetMetadataClient) CreateBulk(builders ...*AssetMetadataCreate) *AssetMetadataCreateBulk {
	return &AssetMetadataCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AssetMetadataClient) MapCreateBulk(slice any, setFunc func(*AssetMetadataCreate, int)) *AssetMetadataCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AssetMetadataCreateBulk{err: fmt.Errorf("calling to AssetMetadataClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AssetMetadataCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AssetMetadataCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AssetMetadata.
func (c *AssetMetadataClient) Update() *AssetMetadataUpdate {
	mutation := newAssetMetadataMutation(c.config, OpUpdate)
	return &AssetMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AssetMetadataClient) UpdateOne(am *AssetMetadata) *AssetMetadataUpdateOne {
	mutation := newAssetMetadataMutation(c.config, OpUpdateOne, withAssetMetadata(am))
	return &AssetMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AssetMetadataClient) UpdateOneID(id uuid.UUID) *AssetMetadataUpdateOne {
	mutation := newAssetMetadataMutation(c.config, OpUpdateOne, withAssetMetadataID(id))
	return &AssetMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AssetMetadata.
func (c *AssetMetadataClient) Delete() *AssetMetadataDelete {
	mutation := newAssetMetadataMutation(c.config, OpDelete)
	return &AssetMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AssetMetadataClient) DeleteOne(am *AssetMetadata) *AssetMetadataDeleteOne {
	return c.DeleteOneID(am.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AssetMetadataClient) DeleteOneID(id uuid.UUID) *AssetMetadataDeleteOne {
	builder := c.Delete().Where(assetmetadata.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AssetMetadataDeleteOne{builder}
}

// Query returns a query builder for AssetMetadata.
func (c *AssetMetadataClient) Query() *AssetMetadataQuery {
	return &AssetMetadataQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAssetMetadata},
		inters: c.Interceptors(),
	}
}

// Get returns a AssetMetadata entity by its id.
func (c *AssetMetadataClient) Get(ctx context.Context, id uuid.UUID) (*AssetMetadata, error) {
	return c.Query().Where(assetmetadata.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AssetMetadataClient) GetX(ctx context.Context, id uuid.UUID) *AssetMetadata {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AssetMetadataClient) Hooks() []Hook {
	return c.hooks.AssetMetadata
}

// Interceptors returns the client interceptors.
func (c *AssetMetadataClient) Interceptors() []Interceptor {
	return c.inters.AssetMetadata
}

func (c *AssetMetadataClient) mutate(ctx context.Context, m *AssetMetadataMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AssetMetadataCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AssetMetadataUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AssetMetadataUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AssetMetadataDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AssetMetadata mutation op: %q", m.Op())
	}
}

// AssetVersionClient is a client for the AssetVersion schema.
type AssetVersionClient struct {
	config
}

// NewAssetVersionClient returns a client for the AssetVersion from the given config.
func NewAssetVersionClient(c config) *AssetVersionClient {
	return &AssetVersionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `assetversion.Hooks(f(g(h())))`.
func (c *AssetVersionClient) Use(hooks ...Hook) {
	c.hooks.AssetVersion = append(c.hooks.AssetVersion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `assetversion.Intercept(f(g(h())))`.
func (c *AssetVersionClient) Intercept(interceptors ...Interceptor) {
	c.inters.AssetVersion = append(c.inters.AssetVersion, interceptors...)
}

// Create returns a builder for creating a AssetVersion entity.
func (c *AssetVersionClient) Create() *AssetVersionCreate {
	mutation := newAssetVersionMutation(c.config, OpCreate)
	return &AssetVersionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AssetVersion entities.
func (c *AssetVersionClient) CreateBulk(builders ...*AssetVersionCreate) *AssetVersionCreateBulk {
	return &AssetVersionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AssetVersionClient) MapCreateBulk(slice any, setFunc func(*AssetVersionCreate, int)) *AssetVersionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AssetVersionCreateBulk{err: fmt.Errorf("calling to AssetVersionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AssetVersionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AssetVersionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AssetVersion.
func (c *AssetVersionClient) Update() *AssetVersionUpdate {
	mutation := newAssetVersionMutation(c.config, OpUpdate)
	return &AssetVersionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AssetVersionClient) UpdateOne(av *AssetVersion) *AssetVersionUpdateOne {
	mutation := newAssetVersionMutation(c.config, OpUpdateOne, withAssetVersion(av))
	return &AssetVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AssetVersionClient) UpdateOneID(id uuid.UUID) *AssetVersionUpdateOne {
	mutation := newAssetVersionMutation(c.config, OpUpdateOne, withAssetVersionID(id))
	return &AssetVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AssetVersion.
func (c *AssetVersionClient) Delete() *AssetVersionDelete {
	mutation := newAssetVersionMutation(c.config, OpDelete)
	return &AssetVersionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AssetVersionClient) DeleteOne(av *AssetVersion) *AssetVersionDeleteOne {
	return c.DeleteOneID(av.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AssetVersionClient) DeleteOneID(id uuid.UUID) *AssetVersionDeleteOne {
	builder := c.Delete().Where(assetversion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AssetVersionDeleteOne{builder}
}

// Query returns a query builder for AssetVersion.
func (c *AssetVersionClient) Query() *AssetVersionQuery {
	return &AssetVersionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAssetVersion},
		inters: c.Interceptors(),
	}
}

// Get returns a AssetVersion entity by its id.
func (c *AssetVersionClient) Get(ctx context.Context, id uuid.UUID) (*AssetVersion, error) {
	return c.Query().Where(assetversion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AssetVersionClient) GetX(ctx context.Context, id uuid.UUID) *AssetVersion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AssetVersionClient) Hooks() []Hook {
	return c.hooks.AssetVersion
}

// Interceptors returns the client interceptors.
func (c *AssetVersionClient) Interceptors() []Interceptor {
	return c.inters.AssetVersion
}

func (c *AssetVersionClient) mutate(ctx context.Context, m *AssetVersionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AssetVersionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AssetVersionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AssetVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AssetVersionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AssetVersion mutation op: %q", m.Op())
	}
}

// BackfillClient is a client for the Backfill schema.
type BackfillClient struct {
	config
}

// NewBackfillClient returns a client for the Backfill from the given config.
func NewBackfillClient(c config) *BackfillClient {
	return &BackfillClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `backfill.Hooks(f(g(h())))`.
func (c *BackfillClient) Use(hooks ...Hook) {
	c.hooks.Backfill = append(c.hooks.Backfill, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `backfill.Intercept(f(g(h())))`.
func (c *BackfillClient) Intercept(interceptors ...Interceptor) {
	c.inters.Backfill = append(c.inters.Backfill, interceptors...)
}

// Create returns a builder for creating a Backfill entity.
func (c *BackfillClient) Create() *BackfillCreate {
	mutation := newBackfillMutation(c.config, OpCreate)
	return &BackfillCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Backfill entities.
func (c *BackfillClient) CreateBulk(builders ...*BackfillCreate) *BackfillCreateBulk {
	return &BackfillCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BackfillClient) MapCreateBulk(slice any, setFunc func(*BackfillCreate, int)) *BackfillCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BackfillCreateBulk{err: fmt.Errorf("calling to BackfillClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BackfillCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BackfillCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Backfill.
func (c *BackfillClient) Update() *BackfillUpdate {
	mutation := newBackfillMutation(c.config, OpUpdate)
	return &BackfillUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BackfillClient) UpdateOne(b *Backfill) *BackfillUpdateOne {
	mutation := newBackfillMutation(c.config, OpUpdateOne, withBackfill(b))
	return &BackfillUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BackfillClient) UpdateOneID(id uuid.UUID) *BackfillUpdateOne {
	mutation := newBackfillMutation(c.config, OpUpdateOne, withBackfillID(id))
	return &BackfillUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Backfill.
func (c *BackfillClient) Delete() *BackfillDelete {
	mutation := newBackfillMutation(c.config, OpDelete)
	return &BackfillDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BackfillClient) DeleteOne(b *Backfill) *BackfillDeleteOne {
	return c.DeleteOneID(b.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BackfillClient) DeleteOneID(id uuid.UUID) *BackfillDeleteOne {
	builder := c.Delete().Where(backfill.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BackfillDeleteOne{builder}
}

// Query returns a query builder for Backfill.
func (c *BackfillClient) Query() *BackfillQuery {
	return &BackfillQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBackfill},
		inters: c.Interceptors(),
	}
}

// Get returns a Backfill entity by its id.
func (c *BackfillClient) Get(ctx context.Context, id uuid.UUID) (*Backfill, error) {
	return c.Query().Where(backfill.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BackfillClient) GetX(ctx context.Context, id uuid.UUID) *Backfill {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BackfillClient) Hooks() []Hook {
	return c.hooks.Backfill
}

// Interceptors returns the client interceptors.
func (c *BackfillClient) Interceptors() []Interceptor {
	return c.inters.Backfill
}

func (c *BackfillClient) mutate(ctx context.Context, m *BackfillMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BackfillCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BackfillUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BackfillUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BackfillDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Backfill mutation op: %q", m.Op())
	}
}

// ColumnEdgeClient is a client for the ColumnEdge schema.
type ColumnEdgeClient struct {
	config
}

// NewColumnEdgeClient returns a client for the ColumnEdge from the given config.
func NewColumnEdgeClient(c config) *ColumnEdgeClient {
	return &ColumnEdgeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `columnedge.Hooks(f(g(h())))`.
func (c *ColumnEdgeClient) Use(hooks ...Hook) {
	c.hooks.ColumnEdge = append(c.hooks.ColumnEdge, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `columnedge.Intercept(f(g(h())))`.
func (c *ColumnEdgeClient) Intercept(interceptors ...Interceptor) {
	c.inters.ColumnEdge = append(c.inters.ColumnEdge, interceptors...)
}

// Create returns a builder for creating a ColumnEdge entity.
func (c *ColumnEdgeClient) Create() *ColumnEdgeCreate {
	mutation := newColumnEdgeMutation(c.config, OpCreate)
	return &ColumnEdgeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ColumnEdge entities.
func (c *ColumnEdgeClient) CreateBulk(builders ...*ColumnEdgeCreate) *ColumnEdgeCreateBulk {
	return &ColumnEdgeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ColumnEdgeClient) MapCreateBulk(slice any, setFunc func(*ColumnEdgeCreate, int)) *ColumnEdgeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ColumnEdgeCreateBulk{err: fmt.Errorf("calling to ColumnEdgeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ColumnEdgeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ColumnEdgeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ColumnEdge.
func (c *ColumnEdgeClient) Update() *ColumnEdgeUpdate {
	mutation := newColumnEdgeMutation(c.config, OpUpdate)
	return &ColumnEdgeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ColumnEdgeClient) UpdateOne(ce *ColumnEdge) *ColumnEdgeUpdateOne {
	mutation := newColumnEdgeMutation(c.config, OpUpdateOne, withColumnEdge(ce))
	return &ColumnEdgeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ColumnEdgeClient) UpdateOneID(id uuid.UUID) *ColumnEdgeUpdateOne {
	mutation := newColumnEdgeMutation(c.config, OpUpdateOne, withColumnEdgeID(id))
	return &ColumnEdgeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ColumnEdge.
func (c *ColumnEdgeClient) Delete() *ColumnEdgeDelete {
	mutation := newColumnEdgeMutation(c.config, OpDelete)
	return &ColumnEdgeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ColumnEdgeClient) DeleteOne(ce *ColumnEdge) *ColumnEdgeDeleteOne {
	return c.DeleteOneID(ce.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ColumnEdgeClient) DeleteOneID(id uuid.UUID) *ColumnEdgeDeleteOne {
	builder := c.Delete().Where(columnedge.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ColumnEdgeDeleteOne{builder}
}

// Query returns a query builder for ColumnEdge.
func (c *ColumnEdgeClient) Query() *ColumnEdgeQuery {
	return &ColumnEdgeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeColumnEdge},
		inters: c.Interceptors(),
	}
}

// Get returns a ColumnEdge entity by its id.
func (c *ColumnEdgeClient) Get(ctx context.Context, id uuid.UUID) (*ColumnEdge, error) {
	return c.Query().Where(columnedge.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ColumnEdgeClient) GetX(ctx context.Context, id uuid.UUID) *ColumnEdge {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ColumnEdgeClient) Hooks() []Hook {
	return c.hooks.ColumnEdge
}

// Interceptors returns the client interceptors.
func (c *ColumnEdgeClient) Interceptors() []Interceptor {
	return c.inters.ColumnEdge
}

func (c *ColumnEdgeClient) mutate(ctx context.Context, m *ColumnEdgeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ColumnEdgeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ColumnEdgeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ColumnEdgeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ColumnEdgeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ColumnEdge mutation op: %q", m.Op())
	}
}

// ConcurrencyTokenClient is a client for the ConcurrencyToken schema.
type ConcurrencyTokenClient struct {
	config
}

// NewConcurrencyTokenClient returns a client for the ConcurrencyToken from the given config.
func NewConcurrencyTokenClient(c config) *ConcurrencyTokenClient {
	return &ConcurrencyTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `concurrencytoken.Hooks(f(g(h())))`.
func (c *ConcurrencyTokenClient) Use(hooks ...Hook) {
	c.hooks.ConcurrencyToken = append(c.hooks.ConcurrencyToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `concurrencytoken.Intercept(f(g(h())))`.
func (c *ConcurrencyTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.ConcurrencyToken = append(c.inters.ConcurrencyToken, interceptors...)
}

// Create returns a builder for creating a ConcurrencyToken entity.
func (c *ConcurrencyTokenClient) Create() *ConcurrencyTokenCreate {
	mutation := newConcurrencyTokenMutation(c.config, OpCreate)
	return &ConcurrencyTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ConcurrencyToken entities.
func (c *ConcurrencyTokenClient) CreateBulk(builders ...*ConcurrencyTokenCreate) *ConcurrencyTokenCreateBulk {
	return &ConcurrencyTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ConcurrencyTokenClient) MapCreateBulk(slice any, setFunc func(*ConcurrencyTokenCreate, int)) *ConcurrencyTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ConcurrencyTokenCreateBulk{err: fmt.Errorf("calling to ConcurrencyTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ConcurrencyTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ConcurrencyTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ConcurrencyToken.
func (c *ConcurrencyTokenClient) Update() *ConcurrencyTokenUpdate {
	mutation := newConcurrencyTokenMutation(c.config, OpUpdate)
	return &ConcurrencyTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ConcurrencyTokenClient) UpdateOne(ct *ConcurrencyToken) *ConcurrencyTokenUpdateOne {
	mutation := newConcurrencyTokenMutation(c.config, OpUpdateOne, withConcurrencyToken(ct))
	return &ConcurrencyTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ConcurrencyTokenClient) UpdateOneID(id uuid.UUID) *ConcurrencyTokenUpdateOne {
	mutation := newConcurrencyTokenMutation(c.config, OpUpdateOne, withConcurrencyTokenID(id))
	return &ConcurrencyTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ConcurrencyToken.
func (c *ConcurrencyTokenClient) Delete() *ConcurrencyTokenDelete {
	mutation := newConcurrencyTokenMutation(c.config, OpDelete)
	return &ConcurrencyTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ConcurrencyTokenClient) DeleteOne(ct *ConcurrencyToken) *ConcurrencyTokenDeleteOne {
	return c.DeleteOneID(ct.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ConcurrencyTokenClient) DeleteOneID(id uuid.UUID) *ConcurrencyTokenDeleteOne {
	builder := c.Delete().Where(concurrencytoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ConcurrencyTokenDeleteOne{builder}
}

// Query returns a query builder for ConcurrencyToken.
func (c *ConcurrencyTokenClient) Query() *ConcurrencyTokenQuery {
	return &ConcurrencyTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeConcurrencyToken},
		inters: c.Interceptors(),
	}
}

// Get returns a ConcurrencyToken entity by its id.
func (c *ConcurrencyTokenClient) Get(ctx context.Context, id uuid.UUID) (*ConcurrencyToken, error) {
	return c.Query().Where(concurrencytoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ConcurrencyTokenClient) GetX(ctx context.Context, id uuid.UUID) *ConcurrencyToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ConcurrencyTokenClient) Hooks() []Hook {
	return c.hooks.ConcurrencyToken
}

// Interceptors returns the client interceptors.
func (c *ConcurrencyTokenClient) Interceptors() []Interceptor {
	return c.inters.ConcurrencyToken
}

func (c *ConcurrencyTokenClient) mutate(ctx context.Context, m *ConcurrencyTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ConcurrencyTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ConcurrencyTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ConcurrencyTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ConcurrencyTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ConcurrencyToken mutation op: %q", m.Op())
	}
}

// EventLogClient is a client for the EventLog schema.
type EventLogClient struct {
	config
}

// NewEventLogClient returns a client for the EventLog from the given config.
func NewEventLogClient(c config) *EventLogClient {
	return &EventLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `eventlog.Hooks(f(g(h())))`.
func (c *EventLogClient) Use(hooks ...Hook) {
	c.hooks.EventLog = append(c.hooks.EventLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `eventlog.Intercept(f(g(h())))`.
func (c *EventLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.EventLog = append(c.inters.EventLog, interceptors...)
}

// Create returns a builder for creating a EventLog entity.
func (c *EventLogClient) Create() *EventLogCreate {
	mutation := newEventLogMutation(c.config, OpCreate)
	return &EventLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EventLog entities.
func (c *EventLogClient) CreateBulk(builders ...*EventLogCreate) *EventLogCreateBulk {
	return &EventLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EventLogClient) MapCreateBulk(slice any, setFunc func(*EventLogCreate, int)) *EventLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EventLogCreateBulk{err: fmt.Errorf("calling to EventLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EventLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EventLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EventLog.
func (c *EventLogClient) Update() *EventLogUpdate {
	mutation := newEventLogMutation(c.config, OpUpdate)
	return &EventLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EventLogClient) UpdateOne(el *EventLog) *EventLogUpdateOne {
	mutation := newEventLogMutation(c.config, OpUpdateOne, withEventLog(el))
	return &EventLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EventLogClient) UpdateOneID(id uuid.UUID) *EventLogUpdateOne {
	mutation := newEventLogMutation(c.config, OpUpdateOne, withEventLogID(id))
	return &EventLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EventLog.
func (c *EventLogClient) Delete() *EventLogDelete {
	mutation := newEventLogMutation(c.config, OpDelete)
	return &EventLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EventLogClient) DeleteOne(el *EventLog) *EventLogDeleteOne {
	return c.DeleteOneID(el.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EventLogClient) DeleteOneID(id uuid.UUID) *EventLogDeleteOne {
	builder := c.Delete().Where(eventlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EventLogDeleteOne{builder}
}

// Query returns a query builder for EventLog.
func (c *EventLogClient) Query() *EventLogQuery {
	return &EventLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEventLog},
		inters: c.Interceptors(),
	}
}

// Get returns a EventLog entity by its id.
func (c *EventLogClient) Get(ctx context.Context, id uuid.UUID) (*EventLog, error) {
	return c.Query().Where(eventlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EventLogClient) GetX(ctx context.Context, id uuid.UUID) *EventLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EventLogClient) Hooks() []Hook {
	return c.hooks.EventLog
}

// Interceptors returns the client interceptors.
func (c *EventLogClient) Interceptors() []Interceptor {
	return c.inters.EventLog
}

func (c *EventLogClient) mutate(ctx context.Context, m *EventLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EventLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EventLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EventLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EventLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EventLog mutation op: %q", m.Op())
	}
}

// InviteTokenClient is a client for the InviteToken schema.
type InviteTokenClient struct {
	config
}

// NewInviteTokenClient returns a client for the InviteToken from the given config.
func NewInviteTokenClient(c config) *InviteTokenClient {
	return &InviteTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `invitetoken.Hooks(f(g(h())))`.
func (c *InviteTokenClient) Use(hooks ...Hook) {
	c.hooks.InviteToken = append(c.hooks.InviteToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `invitetoken.Intercept(f(g(h())))`.
func (c *InviteTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.InviteToken = append(c.inters.InviteToken, interceptors...)
}

// Create returns a builder for creating a InviteToken entity.
func (c *InviteTokenClient) Create() *InviteTokenCreate {
	mutation := newInviteTokenMutation(c.config, OpCreate)
	return &InviteTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of InviteToken entities.
func (c *InviteTokenClient) CreateBulk(builders ...*InviteTokenCreate) *InviteTokenCreateBulk {
	return &InviteTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InviteTokenClient) MapCreateBulk(slice any, setFunc func(*InviteTokenCreate, int)) *InviteTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InviteTokenCreateBulk{err: fmt.Errorf("calling to InviteTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InviteTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InviteTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for InviteToken.
func (c *InviteTokenClient) Update() *InviteTokenUpdate {
	mutation := newInviteTokenMutation(c.config, OpUpdate)
	return &InviteTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InviteTokenClient) UpdateOne(it *InviteToken) *InviteTokenUpdateOne {
	mutation := newInviteTokenMutation(c.config, OpUpdateOne, withInviteToken(it))
	return &InviteTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InviteTokenClient) UpdateOneID(id uuid.UUID) *InviteTokenUpdateOne {
	mutation := newInviteTokenMutation(c.config, OpUpdateOne, withInviteTokenID(id))
	return &InviteTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for InviteToken.
func (c *InviteTokenClient) Delete() *InviteTokenDelete {
	mutation := newInviteTokenMutation(c.config, OpDelete)
	return &InviteTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InviteTokenClient) DeleteOne(it *InviteToken) *InviteTokenDeleteOne {
	return c.DeleteOneID(it.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InviteTokenClient) DeleteOneID(id uuid.UUID) *InviteTokenDeleteOne {
	builder := c.Delete().Where(invitetoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InviteTokenDeleteOne{builder}
}

// Query returns a query builder for InviteToken.
func (c *InviteTokenClient) Query() *InviteTokenQuery {
	return &InviteTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInviteToken},
		inters: c.Interceptors(),
	}
}

// Get returns a InviteToken entity by its id.
func (c *InviteTokenClient) Get(ctx context.Context, id uuid.UUID) (*InviteToken, error) {
	return c.Query().Where(invitetoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InviteTokenClient) GetX(ctx context.Context, id uuid.UUID) *InviteToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *InviteTokenClient) Hooks() []Hook {
	return c.hooks.InviteToken
}

// Interceptors returns the client interceptors.
func (c *InviteTokenClient) Interceptors() []Interceptor {
	return c.inters.InviteToken
}

func (c *InviteTokenClient) mutate(ctx context.Context, m *InviteTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InviteTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InviteTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InviteTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InviteTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown InviteToken mutation op: %q", m.Op())
	}
}

// RunClient is a client for the Run schema.
type RunClient struct {
	config
}

// NewRunClient returns a client for the Run from the given config.
func NewRunClient(c config) *RunClient {
	return &RunClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `run.Hooks(f(g(h())))`.
func (c *RunClient) Use(hooks ...Hook) {
	c.hooks.Run = append(c.hooks.Run, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `run.Intercept(f(g(h())))`.
func (c *RunClient) Intercept(interceptors ...Interceptor) {
	c.inters.Run = append(c.inters.Run, interceptors...)
}

// Create returns a builder for creating a Run entity.
func (c *RunClient) Create() *RunCreate {
	mutation := newRunMutation(c.config, OpCreate)
	return &RunCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Run entities.
func (c *RunClient) CreateBulk(builders ...*RunCreate) *RunCreateBulk {
	return &RunCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RunClient) MapCreateBulk(slice any, setFunc func(*RunCreate, int)) *RunCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RunCreateBulk{err: fmt.Errorf("calling to RunClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RunCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RunCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Run.
func (c *RunClient) Update() *RunUpdate {
	mutation := newRunMutation(c.config, OpUpdate)
	return &RunUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RunClient) UpdateOne(r *Run) *RunUpdateOne {
	mutation := newRunMutation(c.config, OpUpdateOne, withRun(r))
	return &RunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RunClient) UpdateOneID(id uuid.UUID) *RunUpdateOne {
	mutation := newRunMutation(c.config, OpUpdateOne, withRunID(id))
	return &RunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Run.
func (c *RunClient) Delete() *RunDelete {
	mutation := newRunMutation(c.config, OpDelete)
	return &RunDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RunClient) DeleteOne(r *Run) *RunDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RunClient) DeleteOneID(id uuid.UUID) *RunDeleteOne {
	builder := c.Delete().Where(run.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RunDeleteOne{builder}
}

// Query returns a query builder for Run.
func (c *RunClient) Query() *RunQuery {
	return &RunQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRun},
		inters: c.Interceptors(),
	}
}

// Get returns a Run entity by its id.
func (c *RunClient) Get(ctx context.Context, id uuid.UUID) (*Run, error) {
	return c.Query().Where(run.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RunClient) GetX(ctx context.Context, id uuid.UUID) *Run {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RunClient) Hooks() []Hook {
	return c.hooks.Run
}

// Interceptors returns the client interceptors.
func (c *RunClient) Interceptors() []Interceptor {
	return c.inters.Run
}

func (c *RunClient) mutate(ctx context.Context, m *RunMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RunCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RunUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RunDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Run mutation op: %q", m.Op())
	}
}

// RunStepClient is a client for the RunStep schema.
type RunStepClient struct {
	config
}

// NewRunStepClient returns a client for the RunStep from the given config.
func NewRunStepClient(c config) *RunStepClient {
	return &RunStepClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `runstep.Hooks(f(g(h())))`.
func (c *RunStepClient) Use(hooks ...Hook) {
	c.hooks.RunStep = append(c.hooks.RunStep, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `runstep.Intercept(f(g(h())))`.
func (c *RunStepClient) Intercept(interceptors ...Interceptor) {
	c.inters.RunStep = append(c.inters.RunStep, interceptors...)
}

// Create returns a builder for creating a RunStep entity.
func (c *RunStepClient) Create() *RunStepCreate {
	mutation := newRunStepMutation(c.config, OpCreate)
	return &RunStepCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RunStep entities.
func (c *RunStepClient) CreateBulk(builders ...*RunStepCreate) *RunStepCreateBulk {
	return &RunStepCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RunStepClient) MapCreateBulk(slice any, setFunc func(*RunStepCreate, int)) *RunStepCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RunStepCreateBulk{err: fmt.Errorf("calling to RunStepClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RunStepCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RunStepCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RunStep.
func (c *RunStepClient) Update() *RunStepUpdate {
	mutation := newRunStepMutation(c.config, OpUpdate)
	return &RunStepUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RunStepClient) UpdateOne(rs *RunStep) *RunStepUpdateOne {
	mutation := newRunStepMutation(c.config, OpUpdateOne, withRunStep(rs))
	return &RunStepUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RunStepClient) UpdateOneID(id uuid.UUID) *RunStepUpdateOne {
	mutation := newRunStepMutation(c.config, OpUpdateOne, withRunStepID(id))
	return &RunStepUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RunStep.
func (c *RunStepClient) Delete() *RunStepDelete {
	mutation := newRunStepMutation(c.config, OpDelete)
	return &RunStepDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RunStepClient) DeleteOne(rs *RunStep) *RunStepDeleteOne {
	return c.DeleteOneID(rs.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RunStepClient) DeleteOneID(id uuid.UUID) *RunStepDeleteOne {
	builder := c.Delete().Where(runstep.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RunStepDeleteOne{builder}
}

// Query returns a query builder for RunStep.
func (c *RunStepClient) Query() *RunStepQuery {
	return &RunStepQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRunStep},
		inters: c.Interceptors(),
	}
}

// Get returns a RunStep entity by its id.
func (c *RunStepClient) Get(ctx context.Context, id uuid.UUID) (*RunStep, error) {
	return c.Query().Where(runstep.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RunStepClient) GetX(ctx context.Context, id uuid.UUID) *RunStep {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RunStepClient) Hooks() []Hook {
	return c.hooks.RunStep
}

// Interceptors returns the client interceptors.
func (c *RunStepClient) Interceptors() []Interceptor {
	return c.inters.RunStep
}

func (c *RunStepClient) mutate(ctx context.Context, m *RunStepMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RunStepCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RunStepUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RunStepUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RunStepDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RunStep mutation op: %q", m.Op())
	}
}

// ScheduleClient is a client for the Schedule schema.
type ScheduleClient struct {
	config
}

// NewScheduleClient returns a client for the Schedule from the given config.
func NewScheduleClient(c config) *ScheduleClient {
	return &ScheduleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `schedule.Hooks(f(g(h())))`.
func (c *ScheduleClient) Use(hooks ...Hook) {
	c.hooks.Schedule = append(c.hooks.Schedule, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `schedule.Intercept(f(g(h())))`.
func (c *ScheduleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Schedule = append(c.inters.Schedule, interceptors...)
}

// Create returns a builder for creating a Schedule entity.
func (c *ScheduleClient) Create() *ScheduleCreate {
	mutation := newScheduleMutation(c.config, OpCreate)
	return &ScheduleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Schedule entities.
func (c *ScheduleClient) CreateBulk(builders ...*ScheduleCreate) *ScheduleCreateBulk {
	return &ScheduleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ScheduleClient) MapCreateBulk(slice any, setFunc func(*ScheduleCreate, int)) *ScheduleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ScheduleCreateBulk{err: fmt.Errorf("calling to ScheduleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ScheduleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ScheduleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Schedule.
func (c *ScheduleClient) Update() *ScheduleUpdate {
	mutation := newScheduleMutation(c.config, OpUpdate)
	return &ScheduleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ScheduleClient) UpdateOne(s *Schedule) *ScheduleUpdateOne {
	mutation := newScheduleMutation(c.config, OpUpdateOne, withSchedule(s))
	return &ScheduleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ScheduleClient) UpdateOneID(id uuid.UUID) *ScheduleUpdateOne {
	mutation := newScheduleMutation(c.config, OpUpdateOne, withScheduleID(id))
	return &ScheduleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Schedule.
func (c *ScheduleClient) Delete() *ScheduleDelete {
	mutation := newScheduleMutation(c.config, OpDelete)
	return &ScheduleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ScheduleClient) DeleteOne(s *Schedule) *ScheduleDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ScheduleClient) DeleteOneID(id uuid.UUID) *ScheduleDeleteOne {
	builder := c.Delete().Where(schedule.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ScheduleDeleteOne{builder}
}

// Query returns a query builder for Schedule.
func (c *ScheduleClient) Query() *ScheduleQuery {
	return &ScheduleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSchedule},
		inters: c.Interceptors(),
	}
}

// Get returns a Schedule entity by its id.
func (c *ScheduleClient) Get(ctx context.Context, id uuid.UUID) (*Schedule, error) {
	return c.Query().Where(schedule.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ScheduleClient) GetX(ctx context.Context, id uuid.UUID) *Schedule {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ScheduleClient) Hooks() []Hook {
	return c.hooks.Schedule
}

// Interceptors returns the client interceptors.
func (c *ScheduleClient) Interceptors() []Interceptor {
	return c.inters.Schedule
}

func (c *ScheduleClient) mutate(ctx context.Context, m *ScheduleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ScheduleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ScheduleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ScheduleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ScheduleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Schedule mutation op: %q", m.Op())
	}
}

// SchemaChangeClient is a client for the SchemaChange schema.
type SchemaChangeClient struct {
	config
}

// NewSchemaChangeClient returns a client for the SchemaChange from the given config.
func NewSchemaChangeClient(c config) *SchemaChangeClient {
	return &SchemaChangeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `schemachange.Hooks(f(g(h())))`.
func (c *SchemaChangeClient) Use(hooks ...Hook) {
	c.hooks.SchemaChange = append(c.hooks.SchemaChange, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `schemachange.Intercept(f(g(h())))`.
func (c *SchemaChangeClient) Intercept(interceptors ...Interceptor) {
	c.inters.SchemaChange = append(c.inters.SchemaChange, interceptors...)
}

// Create returns a builder for creating a SchemaChange entity.
func (c *SchemaChangeClient) Create() *SchemaChangeCreate {
	mutation := newSchemaChangeMutation(c.config, OpCreate)
	return &SchemaChangeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SchemaChange entities.
func (c *SchemaChangeClient) CreateBulk(builders ...*SchemaChangeCreate) *SchemaChangeCreateBulk {
	return &SchemaChangeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SchemaChangeClient) MapCreateBulk(slice any, setFunc func(*SchemaChangeCreate, int)) *SchemaChangeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SchemaChangeCreateBulk{err: fmt.Errorf("calling to SchemaChangeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SchemaChangeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SchemaChangeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SchemaChange.
func (c *SchemaChangeClient) Update() *SchemaChangeUpdate {
	mutation := newSchemaChangeMutation(c.config, OpUpdate)
	return &SchemaChangeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SchemaChangeClient) UpdateOne(sc *SchemaChange) *SchemaChangeUpdateOne {
	mutation := newSchemaChangeMutation(c.config, OpUpdateOne, withSchemaChange(sc))
	return &SchemaChangeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SchemaChangeClient) UpdateOneID(id uuid.UUID) *SchemaChangeUpdateOne {
	mutation := newSchemaChangeMutation(c.config, OpUpdateOne, withSchemaChangeID(id))
	return &SchemaChangeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SchemaChange.
func (c *SchemaChangeClient) Delete() *SchemaChangeDelete {
	mutation := newSchemaChangeMutation(c.config, OpDelete)
	return &SchemaChangeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SchemaChangeClient) DeleteOne(sc *SchemaChange) *SchemaChangeDeleteOne {
	return c.DeleteOneID(sc.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SchemaChangeClient) DeleteOneID(id uuid.UUID) *SchemaChangeDeleteOne {
	builder := c.Delete().Where(schemachange.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SchemaChangeDeleteOne{builder}
}

// Query returns a query builder for SchemaChange.
func (c *SchemaChangeClient) Query() *SchemaChangeQuery {
	return &SchemaChangeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSchemaChange},
		inters: c.Interceptors(),
	}
}

// Get returns a SchemaChange entity by its id.
func (c *SchemaChangeClient) Get(ctx context.Context, id uuid.UUID) (*SchemaChange, error) {
	return c.Query().Where(schemachange.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SchemaChangeClient) GetX(ctx context.Context, id uuid.UUID) *SchemaChange {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SchemaChangeClient) Hooks() []Hook {
	return c.hooks.SchemaChange
}

// Interceptors returns the client interceptors.
func (c *SchemaChangeClient) Interceptors() []Interceptor {
	return c.inters.SchemaChange
}

func (c *SchemaChangeClient) mutate(ctx context.Context, m *SchemaChangeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SchemaChangeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SchemaChangeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SchemaChangeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SchemaChangeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SchemaChange mutation op: %q", m.Op())
	}
}

// SchemaVersionClient is a client for the SchemaVersion schema.
type SchemaVersionClient struct {
	config
}

// NewSchemaVersionClient returns a client for the SchemaVersion from the given config.
func NewSchemaVersionClient(c config) *SchemaVersionClient {
	return &SchemaVersionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `schemaversion.Hooks(f(g(h())))`.
func (c *SchemaVersionClient) Use(hooks ...Hook) {
	c.hooks.SchemaVersion = append(c.hooks.SchemaVersion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `schemaversion.Intercept(f(g(h())))`.
func (c *SchemaVersionClient) Intercept(interceptors ...Interceptor) {
	c.inters.SchemaVersion = append(c.inters.SchemaVersion, interceptors...)
}

// Create returns a builder for creating a SchemaVersion entity.
func (c *SchemaVersionClient) Create() *SchemaVersionCreate {
	mutation := newSchemaVersionMutation(c.config, OpCreate)
	return &SchemaVersionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SchemaVersion entities.
func (c *SchemaVersionClient) CreateBulk(builders ...*SchemaVersionCreate) *SchemaVersionCreateBulk {
	return &SchemaVersionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SchemaVersionClient) MapCreateBulk(slice any, setFunc func(*SchemaVersionCreate, int)) *SchemaVersionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SchemaVersionCreateBulk{err: fmt.Errorf("calling to SchemaVersionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SchemaVersionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SchemaVersionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SchemaVersion.
func (c *SchemaVersionClient) Update() *SchemaVersionUpdate {
	mutation := newSchemaVersionMutation(c.config, OpUpdate)
	return &SchemaVersionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SchemaVersionClient) UpdateOne(sv *SchemaVersion) *SchemaVersionUpdateOne {
	mutation := newSchemaVersionMutation(c.config, OpUpdateOne, withSchemaVersion(sv))
	return &SchemaVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SchemaVersionClient) UpdateOneID(id uuid.UUID) *SchemaVersionUpdateOne {
	mutation := newSchemaVersionMutation(c.config, OpUpdateOne, withSchemaVersionID(id))
	return &SchemaVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SchemaVersion.
func (c *SchemaVersionClient) Delete() *SchemaVersionDelete {
	mutation := newSchemaVersionMutation(c.config, OpDelete)
	return &SchemaVersionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SchemaVersionClient) DeleteOne(sv *SchemaVersion) *SchemaVersionDeleteOne {
	return c.DeleteOneID(sv.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SchemaVersionClient) DeleteOneID(id uuid.UUID) *SchemaVersionDeleteOne {
	builder := c.Delete().Where(schemaversion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SchemaVersionDeleteOne{builder}
}

// Query returns a query builder for SchemaVersion.
func (c *SchemaVersionClient) Query() *SchemaVersionQuery {
	return &SchemaVersionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSchemaVersion},
		inters: c.Interceptors(),
	}
}

// Get returns a SchemaVersion entity by its id.
func (c *SchemaVersionClient) Get(ctx context.Context, id uuid.UUID) (*SchemaVersion, error) {
	return c.Query().Where(schemaversion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SchemaVersionClient) GetX(ctx context.Context, id uuid.UUID) *SchemaVersion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SchemaVersionClient) Hooks() []Hook {
	return c.hooks.SchemaVersion
}

// Interceptors returns the client interceptors.
func (c *SchemaVersionClient) Interceptors() []Interceptor {
	return c.inters.SchemaVersion
}

func (c *SchemaVersionClient) mutate(ctx context.Context, m *SchemaVersionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SchemaVersionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SchemaVersionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SchemaVersionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SchemaVersionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SchemaVersion mutation op: %q", m.Op())
	}
}

// SensorClient is a client for the Sensor schema.
type SensorClient struct {
	config
}

// NewSensorClient returns a client for the Sensor from the given config.
func NewSensorClient(c config) *SensorClient {
	return &SensorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sensor.Hooks(f(g(h())))`.
func (c *SensorClient) Use(hooks ...Hook) {
	c.hooks.Sensor = append(c.hooks.Sensor, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sensor.Intercept(f(g(h())))`.
func (c *SensorClient) Intercept(interceptors ...Interceptor) {
	c.inters.Sensor = append(c.inters.Sensor, interceptors...)
}

// Create returns a builder for creating a Sensor entity.
func (c *SensorClient) Create() *SensorCreate {
	mutation := newSensorMutation(c.config, OpCreate)
	return &SensorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Sensor entities.
func (c *SensorClient) CreateBulk(builders ...*SensorCreate) *SensorCreateBulk {
	return &SensorCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SensorClient) MapCreateBulk(slice any, setFunc func(*SensorCreate, int)) *SensorCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SensorCreateBulk{err: fmt.Errorf("calling to SensorClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SensorCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SensorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Sensor.
func (c *SensorClient) Update() *SensorUpdate {
	mutation := newSensorMutation(c.config, OpUpdate)
	return &SensorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SensorClient) UpdateOne(s *Sensor) *SensorUpdateOne {
	mutation := newSensorMutation(c.config, OpUpdateOne, withSensor(s))
	return &SensorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SensorClient) UpdateOneID(id uuid.UUID) *SensorUpdateOne {
	mutation := newSensorMutation(c.config, OpUpdateOne, withSensorID(id))
	return &SensorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Sensor.
func (c *SensorClient) Delete() *SensorDelete {
	mutation := newSensorMutation(c.config, OpDelete)
	return &SensorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SensorClient) DeleteOne(s *Sensor) *SensorDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SensorClient) DeleteOneID(id uuid.UUID) *SensorDeleteOne {
	builder := c.Delete().Where(sensor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SensorDeleteOne{builder}
}

// Query returns a query builder for Sensor.
func (c *SensorClient) Query() *SensorQuery {
	return &SensorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSensor},
		inters: c.Interceptors(),
	}
}

// Get returns a Sensor entity by its id.
func (c *SensorClient) Get(ctx context.Context, id uuid.UUID) (*Sensor, error) {
	return c.Query().Where(sensor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SensorClient) GetX(ctx context.Context, id uuid.UUID) *Sensor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SensorClient) Hooks() []Hook {
	return c.hooks.Sensor
}

// Interceptors returns the client interceptors.
func (c *SensorClient) Interceptors() []Interceptor {
	return c.inters.Sensor
}

func (c *SensorClient) mutate(ctx context.Context, m *SensorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SensorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SensorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SensorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SensorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Sensor mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AssetEdge, AssetMetadata, AssetVersion, Backfill, ColumnEdge, ConcurrencyToken,
		EventLog, InviteToken, Run, RunStep, Schedule, SchemaChange, SchemaVersion,
		Sensor, User []ent.Hook
	}
	inters struct {
		AssetEdge, AssetMetadata, AssetVersion, Backfill, ColumnEdge, ConcurrencyToken,
		EventLog, InviteToken, Run, RunStep, Schedule, SchemaChange, SchemaVersion,
		Sensor, User []ent.Interceptor
	}
)
