// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/columnedge"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
)

// ColumnEdgeQuery is the builder for querying ColumnEdge entities.
type ColumnEdgeQuery struct {
	config
	ctx        *QueryContext
	order      []columnedge.OrderOption
	inters     []Interceptor
	predicates []predicate.ColumnEdge
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ColumnEdgeQuery builder.
func (ceq *ColumnEdgeQuery) Where(ps ...predicate.ColumnEdge) *ColumnEdgeQuery {
	ceq.predicates = append(ceq.predicates, ps...)
	return ceq
}

// Limit the number of records to be returned by this query.
func (ceq *ColumnEdgeQuery) Limit(limit int) *ColumnEdgeQuery {
	ceq.ctx.Limit = &limit
	return ceq
}

// Offset to start from.
func (ceq *ColumnEdgeQuery) Offset(offset int) *ColumnEdgeQuery {
	ceq.ctx.Offset = &offset
	return ceq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ceq *ColumnEdgeQuery) Unique(unique bool) *ColumnEdgeQuery {
	ceq.ctx.Unique = &unique
	return ceq
}

// Order specifies how the records should be ordered.
func (ceq *ColumnEdgeQuery) Order(o ...columnedge.OrderOption) *ColumnEdgeQuery {
	ceq.order = append(ceq.order, o...)
	return ceq
}

// First returns the first ColumnEdge entity from the query.
// Returns a *NotFoundError when no ColumnEdge was found.
func (ceq *ColumnEdgeQuery) First(ctx context.Context) (*ColumnEdge, error) {
	nodes, err := ceq.Limit(1).All(setContextOp(ctx, ceq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{columnedge.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ceq *ColumnEdgeQuery) FirstX(ctx context.Context) *ColumnEdge {
	node, err := ceq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ColumnEdge ID from the query.
// Returns a *NotFoundError when no ColumnEdge ID was found.
func (ceq *ColumnEdgeQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ceq.Limit(1).IDs(setContextOp(ctx, ceq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{columnedge.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ceq *ColumnEdgeQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ceq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ColumnEdge entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ColumnEdge entity is found.
// Returns a *NotFoundError when no ColumnEdge entities are found.
func (ceq *ColumnEdgeQuery) Only(ctx context.Context) (*ColumnEdge, error) {
	nodes, err := ceq.Limit(2).All(setContextOp(ctx, ceq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{columnedge.Label}
	default:
		return nil, &NotSingularError{columnedge.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ceq *ColumnEdgeQuery) OnlyX(ctx context.Context) *ColumnEdge {
	node, err := ceq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ColumnEdge ID in the query.
// Returns a *NotSingularError when more than one ColumnEdge ID is found.
// Returns a *NotFoundError when no entities are found.
func (ceq *ColumnEdgeQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ceq.Limit(2).IDs(setContextOp(ctx, ceq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{columnedge.Label}
	default:
		err = &NotSingularError{columnedge.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ceq *ColumnEdgeQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ceq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ColumnEdges.
func (ceq *ColumnEdgeQuery) All(ctx context.Context) ([]*ColumnEdge, error) {
	ctx = setContextOp(ctx, ceq.ctx, ent.OpQueryAll)
	if err := ceq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ColumnEdge, *ColumnEdgeQuery]()
	return withInterceptors[[]*ColumnEdge](ctx, ceq, qr, ceq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ceq *ColumnEdgeQuery) AllX(ctx context.Context) []*ColumnEdge {
	nodes, err := ceq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ColumnEdge IDs.
func (ceq *ColumnEdgeQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if ceq.ctx.Unique == nil && ceq.path != nil {
		ceq.Unique(true)
	}
	ctx = setContextOp(ctx, ceq.ctx, ent.OpQueryIDs)
	if err = ceq.Select(columnedge.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ceq *ColumnEdgeQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ceq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ceq *ColumnEdgeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ceq.ctx, ent.OpQueryCount)
	if err := ceq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ceq, querierCount[*ColumnEdgeQuery](), ceq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ceq *ColumnEdgeQuery) CountX(ctx context.Context) int {
	count, err := ceq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ceq *ColumnEdgeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ceq.ctx, ent.OpQueryExist)
	switch _, err := ceq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ceq *ColumnEdgeQuery) ExistX(ctx context.Context) bool {
	exist, err := ceq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ColumnEdgeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ceq *ColumnEdgeQuery) Clone() *ColumnEdgeQuery {
	if ceq == nil {
		return nil
	}
	return &ColumnEdgeQuery{
		config:     ceq.config,
		ctx:        ceq.ctx.Clone(),
		order:      append([]columnedge.OrderOption{}, ceq.order...),
		inters:     append([]Interceptor{}, ceq.inters...),
		predicates: append([]predicate.ColumnEdge{}, ceq.predicates...),
		// clone intermediate query.
		sql:  ceq.sql.Clone(),
		path: ceq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FromAsset string `json:"from_asset,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ColumnEdge.Query().
//		GroupBy(columnedge.FieldFromAsset).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ceq *ColumnEdgeQuery) GroupBy(field string, fields ...string) *ColumnEdgeGroupBy {
	ceq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ColumnEdgeGroupBy{build: ceq}
	grbuild.flds = &ceq.ctx.Fields
	grbuild.label = columnedge.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FromAsset string `json:"from_asset,omitempty"`
//	}
//
//	client.ColumnEdge.Query().
//		Select(columnedge.FieldFromAsset).
//		Scan(ctx, &v)
func (ceq *ColumnEdgeQuery) Select(fields ...string) *ColumnEdgeSelect {
	ceq.ctx.Fields = append(ceq.ctx.Fields, fields...)
	sbuild := &ColumnEdgeSelect{ColumnEdgeQuery: ceq}
	sbuild.label = columnedge.Label
	sbuild.flds, sbuild.scan = &ceq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ColumnEdgeSelect configured with the given aggregations.
func (ceq *ColumnEdgeQuery) Aggregate(fns ...AggregateFunc) *ColumnEdgeSelect {
	return ceq.Select().Aggregate(fns...)
}

func (ceq *ColumnEdgeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ceq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ceq); err != nil {
				return err
			}
		}
	}
	for _, f := range ceq.ctx.Fields {
		if !columnedge.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ceq.path != nil {
		prev, err := ceq.path(ctx)
		if err != nil {
			return err
		}
		ceq.sql = prev
	}
	return nil
}

func (ceq *ColumnEdgeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ColumnEdge, error) {
	var (
		nodes = []*ColumnEdge{}
		_spec = ceq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ColumnEdge).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ColumnEdge{config: ceq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ceq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ceq *ColumnEdgeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ceq.querySpec()
	_spec.Node.Columns = ceq.ctx.Fields
	if len(ceq.ctx.Fields) > 0 {
		_spec.Unique = ceq.ctx.Unique != nil && *ceq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ceq.driver, _spec)
}

func (ceq *ColumnEdgeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(columnedge.Table, columnedge.Columns, sqlgraph.NewFieldSpec(columnedge.FieldID, field.TypeUUID))
	_spec.From = ceq.sql
	if unique := ceq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ceq.path != nil {
		_spec.Unique = true
	}
	if fields := ceq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, columnedge.FieldID)
		for i := range fields {
			if fields[i] != columnedge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ceq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ceq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ceq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ceq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ceq *ColumnEdgeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ceq.driver.Dialect())
	t1 := builder.Table(columnedge.Table)
	columns := ceq.ctx.Fields
	if len(columns) == 0 {
		columns = columnedge.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ceq.sql != nil {
		selector = ceq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ceq.ctx.Unique != nil && *ceq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ceq.predicates {
		p(selector)
	}
	for _, p := range ceq.order {
		p(selector)
	}
	if offset := ceq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ceq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ColumnEdgeGroupBy is the group-by builder for ColumnEdge entities.
type ColumnEdgeGroupBy struct {
	selector
	build *ColumnEdgeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cegb *ColumnEdgeGroupBy) Aggregate(fns ...AggregateFunc) *ColumnEdgeGroupBy {
	cegb.fns = append(cegb.fns, fns...)
	return cegb
}

// Scan applies the selector query and scans the result into the given value.
func (cegb *ColumnEdgeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cegb.build.ctx, ent.OpQueryGroupBy)
	if err := cegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ColumnEdgeQuery, *ColumnEdgeGroupBy](ctx, cegb.build, cegb, cegb.build.inters, v)
}

func (cegb *ColumnEdgeGroupBy) sqlScan(ctx context.Context, root *ColumnEdgeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cegb.fns))
	for _, fn := range cegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cegb.flds)+len(cegb.fns))
		for _, f := range *cegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ColumnEdgeSelect is the builder for selecting fields of ColumnEdge entities.
type ColumnEdgeSelect struct {
	*ColumnEdgeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ces *ColumnEdgeSelect) Aggregate(fns ...AggregateFunc) *ColumnEdgeSelect {
	ces.fns = append(ces.fns, fns...)
	return ces
}

// Scan applies the selector query and scans the result into the given value.
func (ces *ColumnEdgeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ces.ctx, ent.OpQuerySelect)
	if err := ces.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ColumnEdgeQuery, *ColumnEdgeSelect](ctx, ces.ColumnEdgeQuery, ces, ces.inters, v)
}

func (ces *ColumnEdgeSelect) sqlScan(ctx context.Context, root *ColumnEdgeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ces.fns))
	for _, fn := range ces.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ces.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ces.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
