// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/columnedge"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
)

// ColumnEdgeUpdate is the builder for updating ColumnEdge entities.
type ColumnEdgeUpdate struct {
	config
	hooks    []Hook
	mutation *ColumnEdgeMutation
}

// Where appends a list predicates to the ColumnEdgeUpdate builder.
func (ceu *ColumnEdgeUpdate) Where(ps ...predicate.ColumnEdge) *ColumnEdgeUpdate {
	ceu.mutation.Where(ps...)
	return ceu
}

// SetCodeHashLatest sets the "code_hash_latest" field.
func (ceu *ColumnEdgeUpdate) SetCodeHashLatest(s string) *ColumnEdgeUpdate {
	ceu.mutation.SetCodeHashLatest(s)
	return ceu
}

// SetNillableCodeHashLatest sets the "code_hash_latest" field if the given value is not nil.
func (ceu *ColumnEdgeUpdate) SetNillableCodeHashLatest(s *string) *ColumnEdgeUpdate {
	if s != nil {
		ceu.SetCodeHashLatest(*s)
	}
	return ceu
}

// SetLastSeenRunID sets the "last_seen_run_id" field.
func (ceu *ColumnEdgeUpdate) SetLastSeenRunID(u uuid.UUID) *ColumnEdgeUpdate {
	ceu.mutation.SetLastSeenRunID(u)
	return ceu
}

// SetNillableLastSeenRunID sets the "last_seen_run_id" field if the given value is not nil.
func (ceu *ColumnEdgeUpdate) SetNillableLastSeenRunID(u *uuid.UUID) *ColumnEdgeUpdate {
	if u != nil {
		ceu.SetLastSeenRunID(*u)
	}
	return ceu
}

// SetLastSeenAt sets the "last_seen_at" field.
func (ceu *ColumnEdgeUpdate) SetLastSeenAt(t time.Time) *ColumnEdgeUpdate {
	ceu.mutation.SetLastSeenAt(t)
	return ceu
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (ceu *ColumnEdgeUpdate) SetNillableLastSeenAt(t *time.Time) *ColumnEdgeUpdate {
	if t != nil {
		ceu.SetLastSeenAt(*t)
	}
	return ceu
}

// SetSupersededAt sets the "superseded_at" field.
func (ceu *ColumnEdgeUpdate) SetSupersededAt(t time.Time) *ColumnEdgeUpdate {
	ceu.mutation.SetSupersededAt(t)
	return ceu
}

// SetNillableSupersededAt sets the "superseded_at" field if the given value is not nil.
func (ceu *ColumnEdgeUpdate) SetNillableSupersededAt(t *time.Time) *ColumnEdgeUpdate {
	if t != nil {
		ceu.SetSupersededAt(*t)
	}
	return ceu
}

// ClearSupersededAt clears the value of the "superseded_at" field.
func (ceu *ColumnEdgeUpdate) ClearSupersededAt() *ColumnEdgeUpdate {
	ceu.mutation.ClearSupersededAt()
	return ceu
}

// SetPartitionKey sets the "partition_key" field.
func (ceu *ColumnEdgeUpdate) SetPartitionKey(s string) *ColumnEdgeUpdate {
	ceu.mutation.SetPartitionKey(s)
	return ceu
}

// SetNillablePartitionKey sets the "partition_key" field if the given value is not nil.
func (ceu *ColumnEdgeUpdate) SetNillablePartitionKey(s *string) *ColumnEdgeUpdate {
	if s != nil {
		ceu.SetPartitionKey(*s)
	}
	return ceu
}

// ClearPartitionKey clears the value of the "partition_key" field.
func (ceu *ColumnEdgeUpdate) ClearPartitionKey() *ColumnEdgeUpdate {
	ceu.mutation.ClearPartitionKey()
	return ceu
}

// Mutation returns the ColumnEdgeMutation object of the builder.
func (ceu *ColumnEdgeUpdate) Mutation() *ColumnEdgeMutation {
	return ceu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ceu *ColumnEdgeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ceu.sqlSave, ceu.mutation, ceu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ceu *ColumnEdgeUpdate) SaveX(ctx context.Context) int {
	affected, err := ceu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ceu *ColumnEdgeUpdate) Exec(ctx context.Context) error {
	_, err := ceu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ceu *ColumnEdgeUpdate) ExecX(ctx context.Context) {
	if err := ceu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ceu *ColumnEdgeUpdate) check() error {
	if v, ok := ceu.mutation.CodeHashLatest(); ok {
		if err := columnedge.CodeHashLatestValidator(v); err != nil {
			return &ValidationError{Name: "code_hash_latest", err: fmt.Errorf(`ent: validator failed for field "ColumnEdge.code_hash_latest": %w`, err)}
		}
	}
	if v, ok := ceu.mutation.PartitionKey(); ok {
		if err := columnedge.PartitionKeyValidator(v); err != nil {
			return &ValidationError{Name: "partition_key", err: fmt.Errorf(`ent: validator failed for field "ColumnEdge.partition_key": %w`, err)}
		}
	}
	return nil
}

func (ceu *ColumnEdgeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ceu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(columnedge.Table, columnedge.Columns, sqlgraph.NewFieldSpec(columnedge.FieldID, field.TypeUUID))
	if ps := ceu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ceu.mutation.CodeHashLatest(); ok {
		_spec.SetField(columnedge.FieldCodeHashLatest, field.TypeString, value)
	}
	if value, ok := ceu.mutation.LastSeenRunID(); ok {
		_spec.SetField(columnedge.FieldLastSeenRunID, field.TypeUUID, value)
	}
	if value, ok := ceu.mutation.LastSeenAt(); ok {
		_spec.SetField(columnedge.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := ceu.mutation.SupersededAt(); ok {
		_spec.SetField(columnedge.FieldSupersededAt, field.TypeTime, value)
	}
	if ceu.mutation.SupersededAtCleared() {
		_spec.ClearField(columnedge.FieldSupersededAt, field.TypeTime)
	}
	if value, ok := ceu.mutation.PartitionKey(); ok {
		_spec.SetField(columnedge.FieldPartitionKey, field.TypeString, value)
	}
	if ceu.mutation.PartitionKeyCleared() {
		_spec.ClearField(columnedge.FieldPartitionKey, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ceu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{columnedge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ceu.mutation.done = true
	return n, nil
}

// ColumnEdgeUpdateOne is the builder for updating a single ColumnEdge entity.
type ColumnEdgeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ColumnEdgeMutation
}

// SetCodeHashLatest sets the "code_hash_latest" field.
func (ceuo *ColumnEdgeUpdateOne) SetCodeHashLatest(s string) *ColumnEdgeUpdateOne {
	ceuo.mutation.SetCodeHashLatest(s)
	return ceuo
}

// SetNillableCodeHashLatest sets the "code_hash_latest" field if the given value is not nil.
func (ceuo *ColumnEdgeUpdateOne) SetNillableCodeHashLatest(s *string) *ColumnEdgeUpdateOne {
	if s != nil {
		ceuo.SetCodeHashLatest(*s)
	}
	return ceuo
}

// SetLastSeenRunID sets the "last_seen_run_id" field.
func (ceuo *ColumnEdgeUpdateOne) SetLastSeenRunID(u uuid.UUID) *ColumnEdgeUpdateOne {
	ceuo.mutation.SetLastSeenRunID(u)
	return ceuo
}

// SetNillableLastSeenRunID sets the "last_seen_run_id" field if the given value is not nil.
func (ceuo *ColumnEdgeUpdateOne) SetNillableLastSeenRunID(u *uuid.UUID) *ColumnEdgeUpdateOne {
	if u != nil {
		ceuo.SetLastSeenRunID(*u)
	}
	return ceuo
}

// SetLastSeenAt sets the "last_seen_at" field.
func (ceuo *ColumnEdgeUpdateOne) SetLastSeenAt(t time.Time) *ColumnEdgeUpdateOne {
	ceuo.mutation.SetLastSeenAt(t)
	return ceuo
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (ceuo *ColumnEdgeUpdateOne) SetNillableLastSeenAt(t *time.Time) *ColumnEdgeUpdateOne {
	if t != nil {
		ceuo.SetLastSeenAt(*t)
	}
	return ceuo
}

// SetSupersededAt sets the "superseded_at" field.
func (ceuo *ColumnEdgeUpdateOne) SetSupersededAt(t time.Time) *ColumnEdgeUpdateOne {
	ceuo.mutation.SetSupersededAt(t)
	return ceuo
}

// SetNillableSupersededAt sets the "superseded_at" field if the given value is not nil.
func (ceuo *ColumnEdgeUpdateOne) SetNillableSupersededAt(t *time.Time) *ColumnEdgeUpdateOne {
	if t != nil {
		ceuo.SetSupersededAt(*t)
	}
	return ceuo
}

// ClearSupersededAt clears the value of the "superseded_at" field.
func (ceuo *ColumnEdgeUpdateOne) ClearSupersededAt() *ColumnEdgeUpdateOne {
	ceuo.mutation.ClearSupersededAt()
	return ceuo
}

// SetPartitionKey sets the "partition_key" field.
func (ceuo *ColumnEdgeUpdateOne) SetPartitionKey(s string) *ColumnEdgeUpdateOne {
	ceuo.mutation.SetPartitionKey(s)
	return ceuo
}

// SetNillablePartitionKey sets the "partition_key" field if the given value is not nil.
func (ceuo *ColumnEdgeUpdateOne) SetNillablePartitionKey(s *string) *ColumnEdgeUpdateOne {
	if s != nil {
		ceuo.SetPartitionKey(*s)
	}
	return ceuo
}

// ClearPartitionKey clears the value of the "partition_key" field.
func (ceuo *ColumnEdgeUpdateOne) ClearPartitionKey() *ColumnEdgeUpdateOne {
	ceuo.mutation.ClearPartitionKey()
	return ceuo
}

// Mutation returns the ColumnEdgeMutation object of the builder.
func (ceuo *ColumnEdgeUpdateOne) Mutation() *ColumnEdgeMutation {
	return ceuo.mutation
}

// Where appends a list predicates to the ColumnEdgeUpdate builder.
func (ceuo *ColumnEdgeUpdateOne) Where(ps ...predicate.ColumnEdge) *ColumnEdgeUpdateOne {
	ceuo.mutation.Where(ps...)
	return ceuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ceuo *ColumnEdgeUpdateOne) Select(field string, fields ...string) *ColumnEdgeUpdateOne {
	ceuo.fields = append([]string{field}, fields...)
	return ceuo
}

// Save executes the query and returns the updated ColumnEdge entity.
func (ceuo *ColumnEdgeUpdateOne) Save(ctx context.Context) (*ColumnEdge, error) {
	return withHooks(ctx, ceuo.sqlSave, ceuo.mutation, ceuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ceuo *ColumnEdgeUpdateOne) SaveX(ctx context.Context) *ColumnEdge {
	node, err := ceuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ceuo *ColumnEdgeUpdateOne) Exec(ctx context.Context) error {
	_, err := ceuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ceuo *ColumnEdgeUpdateOne) ExecX(ctx context.Context) {
	if err := ceuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ceuo *ColumnEdgeUpdateOne) check() error {
	if v, ok := ceuo.mutation.CodeHashLatest(); ok {
		if err := columnedge.CodeHashLatestValidator(v); err != nil {
			return &ValidationError{Name: "code_hash_latest", err: fmt.Errorf(`ent: validator failed for field "ColumnEdge.code_hash_latest": %w`, err)}
		}
	}
	if v, ok := ceuo.mutation.PartitionKey(); ok {
		if err := columnedge.PartitionKeyValidator(v); err != nil {
			return &ValidationError{Name: "partition_key", err: fmt.Errorf(`ent: validator failed for field "ColumnEdge.partition_key": %w`, err)}
		}
	}
	return nil
}

func (ceuo *ColumnEdgeUpdateOne) sqlSave(ctx context.Context) (_node *ColumnEdge, err error) {
	if err := ceuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(columnedge.Table, columnedge.Columns, sqlgraph.NewFieldSpec(columnedge.FieldID, field.TypeUUID))
	id, ok := ceuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ColumnEdge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ceuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, columnedge.FieldID)
		for _, f := range fields {
			if !columnedge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != columnedge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ceuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ceuo.mutation.CodeHashLatest(); ok {
		_spec.SetField(columnedge.FieldCodeHashLatest, field.TypeString, value)
	}
	if value, ok := ceuo.mutation.LastSeenRunID(); ok {
		_spec.SetField(columnedge.FieldLastSeenRunID, field.TypeUUID, value)
	}
	if value, ok := ceuo.mutation.LastSeenAt(); ok {
		_spec.SetField(columnedge.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := ceuo.mutation.SupersededAt(); ok {
		_spec.SetField(columnedge.FieldSupersededAt, field.TypeTime, value)
	}
	if ceuo.mutation.SupersededAtCleared() {
		_spec.ClearField(columnedge.FieldSupersededAt, field.TypeTime)
	}
	if value, ok := ceuo.mutation.PartitionKey(); ok {
		_spec.SetField(columnedge.FieldPartitionKey, field.TypeString, value)
	}
	if ceuo.mutation.PartitionKeyCleared() {
		_spec.ClearField(columnedge.FieldPartitionKey, field.TypeString)
	}
	_node = &ColumnEdge{config: ceuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ceuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{columnedge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ceuo.mutation.done = true
	return _node, nil
}
