// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kanpon/data-governance/internal/storage/ent/columnedge"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
)

// ColumnEdgeDelete is the builder for deleting a ColumnEdge entity.
type ColumnEdgeDelete struct {
	config
	hooks    []Hook
	mutation *ColumnEdgeMutation
}

// Where appends a list predicates to the ColumnEdgeDelete builder.
func (ced *ColumnEdgeDelete) Where(ps ...predicate.ColumnEdge) *ColumnEdgeDelete {
	ced.mutation.Where(ps...)
	return ced
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ced *ColumnEdgeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ced.sqlExec, ced.mutation, ced.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ced *ColumnEdgeDelete) ExecX(ctx context.Context) int {
	n, err := ced.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ced *ColumnEdgeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(columnedge.Table, sqlgraph.NewFieldSpec(columnedge.FieldID, field.TypeUUID))
	if ps := ced.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ced.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ced.mutation.done = true
	return affected, err
}

// ColumnEdgeDeleteOne is the builder for deleting a single ColumnEdge entity.
type ColumnEdgeDeleteOne struct {
	ced *ColumnEdgeDelete
}

// Where appends a list predicates to the ColumnEdgeDelete builder.
func (cedo *ColumnEdgeDeleteOne) Where(ps ...predicate.ColumnEdge) *ColumnEdgeDeleteOne {
	cedo.ced.mutation.Where(ps...)
	return cedo
}

// Exec executes the deletion query.
func (cedo *ColumnEdgeDeleteOne) Exec(ctx context.Context) error {
	n, err := cedo.ced.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{columnedge.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cedo *ColumnEdgeDeleteOne) ExecX(ctx context.Context) {
	if err := cedo.Exec(ctx); err != nil {
		panic(err)
	}
}
