// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kanpon/data-governance/internal/storage/ent/concurrencytoken"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
)

// ConcurrencyTokenUpdate is the builder for updating ConcurrencyToken entities.
type ConcurrencyTokenUpdate struct {
	config
	hooks    []Hook
	mutation *ConcurrencyTokenMutation
}

// Where appends a list predicates to the ConcurrencyTokenUpdate builder.
func (ctu *ConcurrencyTokenUpdate) Where(ps ...predicate.ConcurrencyToken) *ConcurrencyTokenUpdate {
	ctu.mutation.Where(ps...)
	return ctu
}

// Mutation returns the ConcurrencyTokenMutation object of the builder.
func (ctu *ConcurrencyTokenUpdate) Mutation() *ConcurrencyTokenMutation {
	return ctu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ctu *ConcurrencyTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ctu.sqlSave, ctu.mutation, ctu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ctu *ConcurrencyTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := ctu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ctu *ConcurrencyTokenUpdate) Exec(ctx context.Context) error {
	_, err := ctu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctu *ConcurrencyTokenUpdate) ExecX(ctx context.Context) {
	if err := ctu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ctu *ConcurrencyTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(concurrencytoken.Table, concurrencytoken.Columns, sqlgraph.NewFieldSpec(concurrencytoken.FieldID, field.TypeUUID))
	if ps := ctu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ctu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{concurrencytoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ctu.mutation.done = true
	return n, nil
}

// ConcurrencyTokenUpdateOne is the builder for updating a single ConcurrencyToken entity.
type ConcurrencyTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConcurrencyTokenMutation
}

// Mutation returns the ConcurrencyTokenMutation object of the builder.
func (ctuo *ConcurrencyTokenUpdateOne) Mutation() *ConcurrencyTokenMutation {
	return ctuo.mutation
}

// Where appends a list predicates to the ConcurrencyTokenUpdate builder.
func (ctuo *ConcurrencyTokenUpdateOne) Where(ps ...predicate.ConcurrencyToken) *ConcurrencyTokenUpdateOne {
	ctuo.mutation.Where(ps...)
	return ctuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ctuo *ConcurrencyTokenUpdateOne) Select(field string, fields ...string) *ConcurrencyTokenUpdateOne {
	ctuo.fields = append([]string{field}, fields...)
	return ctuo
}

// Save executes the query and returns the updated ConcurrencyToken entity.
func (ctuo *ConcurrencyTokenUpdateOne) Save(ctx context.Context) (*ConcurrencyToken, error) {
	return withHooks(ctx, ctuo.sqlSave, ctuo.mutation, ctuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ctuo *ConcurrencyTokenUpdateOne) SaveX(ctx context.Context) *ConcurrencyToken {
	node, err := ctuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ctuo *ConcurrencyTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := ctuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctuo *ConcurrencyTokenUpdateOne) ExecX(ctx context.Context) {
	if err := ctuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ctuo *ConcurrencyTokenUpdateOne) sqlSave(ctx context.Context) (_node *ConcurrencyToken, err error) {
	_spec := sqlgraph.NewUpdateSpec(concurrencytoken.Table, concurrencytoken.Columns, sqlgraph.NewFieldSpec(concurrencytoken.FieldID, field.TypeUUID))
	id, ok := ctuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConcurrencyToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ctuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, concurrencytoken.FieldID)
		for _, f := range fields {
			if !concurrencytoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != concurrencytoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ctuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ConcurrencyToken{config: ctuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ctuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{concurrencytoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ctuo.mutation.done = true
	return _node, nil
}
