// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/concurrencytoken"
)

// ConcurrencyToken is the model entity for the ConcurrencyToken schema.
type ConcurrencyToken struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID uuid.UUID `json:"run_id,omitempty"`
	// AssetName holds the value of the "asset_name" field.
	AssetName string `json:"asset_name,omitempty"`
	// ResourceTag holds the value of the "resource_tag" field.
	ResourceTag string `json:"resource_tag,omitempty"`
	// Weight holds the value of the "weight" field.
	Weight int `json:"weight,omitempty"`
	// AcquiredAt holds the value of the "acquired_at" field.
	AcquiredAt   time.Time `json:"acquired_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConcurrencyToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case concurrencytoken.FieldWeight:
			values[i] = new(sql.NullInt64)
		case concurrencytoken.FieldAssetName, concurrencytoken.FieldResourceTag:
			values[i] = new(sql.NullString)
		case concurrencytoken.FieldAcquiredAt:
			values[i] = new(sql.NullTime)
		case concurrencytoken.FieldID, concurrencytoken.FieldRunID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConcurrencyToken fields.
func (ct *ConcurrencyToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case concurrencytoken.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ct.ID = *value
			}
		case concurrencytoken.FieldRunID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value != nil {
				ct.RunID = *value
			}
		case concurrencytoken.FieldAssetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_name", values[i])
			} else if value.Valid {
				ct.AssetName = value.String
			}
		case concurrencytoken.FieldResourceTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_tag", values[i])
			} else if value.Valid {
				ct.ResourceTag = value.String
			}
		case concurrencytoken.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				ct.Weight = int(value.Int64)
			}
		case concurrencytoken.FieldAcquiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field acquired_at", values[i])
			} else if value.Valid {
				ct.AcquiredAt = value.Time
			}
		default:
			ct.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConcurrencyToken.
// This includes values selected through modifiers, order, etc.
func (ct *ConcurrencyToken) Value(name string) (ent.Value, error) {
	return ct.selectValues.Get(name)
}

// Update returns a builder for updating this ConcurrencyToken.
// Note that you need to call ConcurrencyToken.Unwrap() before calling this method if this ConcurrencyToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (ct *ConcurrencyToken) Update() *ConcurrencyTokenUpdateOne {
	return NewConcurrencyTokenClient(ct.config).UpdateOne(ct)
}

// Unwrap unwraps the ConcurrencyToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ct *ConcurrencyToken) Unwrap() *ConcurrencyToken {
	_tx, ok := ct.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConcurrencyToken is not a transactional entity")
	}
	ct.config.driver = _tx.drv
	return ct
}

// String implements the fmt.Stringer.
func (ct *ConcurrencyToken) String() string {
	var builder strings.Builder
	builder.WriteString("ConcurrencyToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ct.ID))
	builder.WriteString("run_id=")
	builder.WriteString(fmt.Sprintf("%v", ct.RunID))
	builder.WriteString(", ")
	builder.WriteString("asset_name=")
	builder.WriteString(ct.AssetName)
	builder.WriteString(", ")
	builder.WriteString("resource_tag=")
	builder.WriteString(ct.ResourceTag)
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", ct.Weight))
	builder.WriteString(", ")
	builder.WriteString("acquired_at=")
	builder.WriteString(ct.AcquiredAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ConcurrencyTokens is a parsable slice of ConcurrencyToken.
type ConcurrencyTokens []*ConcurrencyToken
