// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/invitetoken"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
)

// InviteTokenUpdate is the builder for updating InviteToken entities.
type InviteTokenUpdate struct {
	config
	hooks    []Hook
	mutation *InviteTokenMutation
}

// Where appends a list predicates to the InviteTokenUpdate builder.
func (itu *InviteTokenUpdate) Where(ps ...predicate.InviteToken) *InviteTokenUpdate {
	itu.mutation.Where(ps...)
	return itu
}

// SetTokenHash sets the "token_hash" field.
func (itu *InviteTokenUpdate) SetTokenHash(s string) *InviteTokenUpdate {
	itu.mutation.SetTokenHash(s)
	return itu
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (itu *InviteTokenUpdate) SetNillableTokenHash(s *string) *InviteTokenUpdate {
	if s != nil {
		itu.SetTokenHash(*s)
	}
	return itu
}

// SetEmail sets the "email" field.
func (itu *InviteTokenUpdate) SetEmail(s string) *InviteTokenUpdate {
	itu.mutation.SetEmail(s)
	return itu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (itu *InviteTokenUpdate) SetNillableEmail(s *string) *InviteTokenUpdate {
	if s != nil {
		itu.SetEmail(*s)
	}
	return itu
}

// SetInvitedBy sets the "invited_by" field.
func (itu *InviteTokenUpdate) SetInvitedBy(u uuid.UUID) *InviteTokenUpdate {
	itu.mutation.SetInvitedBy(u)
	return itu
}

// SetNillableInvitedBy sets the "invited_by" field if the given value is not nil.
func (itu *InviteTokenUpdate) SetNillableInvitedBy(u *uuid.UUID) *InviteTokenUpdate {
	if u != nil {
		itu.SetInvitedBy(*u)
	}
	return itu
}

// SetExpiresAt sets the "expires_at" field.
func (itu *InviteTokenUpdate) SetExpiresAt(t time.Time) *InviteTokenUpdate {
	itu.mutation.SetExpiresAt(t)
	return itu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (itu *InviteTokenUpdate) SetNillableExpiresAt(t *time.Time) *InviteTokenUpdate {
	if t != nil {
		itu.SetExpiresAt(*t)
	}
	return itu
}

// SetAcceptedAt sets the "accepted_at" field.
func (itu *InviteTokenUpdate) SetAcceptedAt(t time.Time) *InviteTokenUpdate {
	itu.mutation.SetAcceptedAt(t)
	return itu
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (itu *InviteTokenUpdate) SetNillableAcceptedAt(t *time.Time) *InviteTokenUpdate {
	if t != nil {
		itu.SetAcceptedAt(*t)
	}
	return itu
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (itu *InviteTokenUpdate) ClearAcceptedAt() *InviteTokenUpdate {
	itu.mutation.ClearAcceptedAt()
	return itu
}

// Mutation returns the InviteTokenMutation object of the builder.
func (itu *InviteTokenUpdate) Mutation() *InviteTokenMutation {
	return itu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (itu *InviteTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, itu.sqlSave, itu.mutation, itu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (itu *InviteTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := itu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (itu *InviteTokenUpdate) Exec(ctx context.Context) error {
	_, err := itu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (itu *InviteTokenUpdate) ExecX(ctx context.Context) {
	if err := itu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (itu *InviteTokenUpdate) check() error {
	if v, ok := itu.mutation.TokenHash(); ok {
		if err := invitetoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "InviteToken.token_hash": %w`, err)}
		}
	}
	if v, ok := itu.mutation.Email(); ok {
		if err := invitetoken.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InviteToken.email": %w`, err)}
		}
	}
	return nil
}

func (itu *InviteTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := itu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitetoken.Table, invitetoken.Columns, sqlgraph.NewFieldSpec(invitetoken.FieldID, field.TypeUUID))
	if ps := itu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := itu.mutation.TokenHash(); ok {
		_spec.SetField(invitetoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := itu.mutation.Email(); ok {
		_spec.SetField(invitetoken.FieldEmail, field.TypeString, value)
	}
	if value, ok := itu.mutation.InvitedBy(); ok {
		_spec.SetField(invitetoken.FieldInvitedBy, field.TypeUUID, value)
	}
	if value, ok := itu.mutation.ExpiresAt(); ok {
		_spec.SetField(invitetoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := itu.mutation.AcceptedAt(); ok {
		_spec.SetField(invitetoken.FieldAcceptedAt, field.TypeTime, value)
	}
	if itu.mutation.AcceptedAtCleared() {
		_spec.ClearField(invitetoken.FieldAcceptedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, itu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitetoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	itu.mutation.done = true
	return n, nil
}

// InviteTokenUpdateOne is the builder for updating a single InviteToken entity.
type InviteTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InviteTokenMutation
}

// SetTokenHash sets the "token_hash" field.
func (ituo *InviteTokenUpdateOne) SetTokenHash(s string) *InviteTokenUpdateOne {
	ituo.mutation.SetTokenHash(s)
	return ituo
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (ituo *InviteTokenUpdateOne) SetNillableTokenHash(s *string) *InviteTokenUpdateOne {
	if s != nil {
		ituo.SetTokenHash(*s)
	}
	return ituo
}

// SetEmail sets the "email" field.
func (ituo *InviteTokenUpdateOne) SetEmail(s string) *InviteTokenUpdateOne {
	ituo.mutation.SetEmail(s)
	return ituo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (ituo *InviteTokenUpdateOne) SetNillableEmail(s *string) *InviteTokenUpdateOne {
	if s != nil {
		ituo.SetEmail(*s)
	}
	return ituo
}

// SetInvitedBy sets the "invited_by" field.
func (ituo *InviteTokenUpdateOne) SetInvitedBy(u uuid.UUID) *InviteTokenUpdateOne {
	ituo.mutation.SetInvitedBy(u)
	return ituo
}

// SetNillableInvitedBy sets the "invited_by" field if the given value is not nil.
func (ituo *InviteTokenUpdateOne) SetNillableInvitedBy(u *uuid.UUID) *InviteTokenUpdateOne {
	if u != nil {
		ituo.SetInvitedBy(*u)
	}
	return ituo
}

// SetExpiresAt sets the "expires_at" field.
func (ituo *InviteTokenUpdateOne) SetExpiresAt(t time.Time) *InviteTokenUpdateOne {
	ituo.mutation.SetExpiresAt(t)
	return ituo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (ituo *InviteTokenUpdateOne) SetNillableExpiresAt(t *time.Time) *InviteTokenUpdateOne {
	if t != nil {
		ituo.SetExpiresAt(*t)
	}
	return ituo
}

// SetAcceptedAt sets the "accepted_at" field.
func (ituo *InviteTokenUpdateOne) SetAcceptedAt(t time.Time) *InviteTokenUpdateOne {
	ituo.mutation.SetAcceptedAt(t)
	return ituo
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (ituo *InviteTokenUpdateOne) SetNillableAcceptedAt(t *time.Time) *InviteTokenUpdateOne {
	if t != nil {
		ituo.SetAcceptedAt(*t)
	}
	return ituo
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (ituo *InviteTokenUpdateOne) ClearAcceptedAt() *InviteTokenUpdateOne {
	ituo.mutation.ClearAcceptedAt()
	return ituo
}

// Mutation returns the InviteTokenMutation object of the builder.
func (ituo *InviteTokenUpdateOne) Mutation() *InviteTokenMutation {
	return ituo.mutation
}

// Where appends a list predicates to the InviteTokenUpdate builder.
func (ituo *InviteTokenUpdateOne) Where(ps ...predicate.InviteToken) *InviteTokenUpdateOne {
	ituo.mutation.Where(ps...)
	return ituo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ituo *InviteTokenUpdateOne) Select(field string, fields ...string) *InviteTokenUpdateOne {
	ituo.fields = append([]string{field}, fields...)
	return ituo
}

// Save executes the query and returns the updated InviteToken entity.
func (ituo *InviteTokenUpdateOne) Save(ctx context.Context) (*InviteToken, error) {
	return withHooks(ctx, ituo.sqlSave, ituo.mutation, ituo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ituo *InviteTokenUpdateOne) SaveX(ctx context.Context) *InviteToken {
	node, err := ituo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ituo *InviteTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := ituo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ituo *InviteTokenUpdateOne) ExecX(ctx context.Context) {
	if err := ituo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ituo *InviteTokenUpdateOne) check() error {
	if v, ok := ituo.mutation.TokenHash(); ok {
		if err := invitetoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "InviteToken.token_hash": %w`, err)}
		}
	}
	if v, ok := ituo.mutation.Email(); ok {
		if err := invitetoken.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InviteToken.email": %w`, err)}
		}
	}
	return nil
}

func (ituo *InviteTokenUpdateOne) sqlSave(ctx context.Context) (_node *InviteToken, err error) {
	if err := ituo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitetoken.Table, invitetoken.Columns, sqlgraph.NewFieldSpec(invitetoken.FieldID, field.TypeUUID))
	id, ok := ituo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InviteToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ituo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitetoken.FieldID)
		for _, f := range fields {
			if !invitetoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invitetoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ituo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ituo.mutation.TokenHash(); ok {
		_spec.SetField(invitetoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := ituo.mutation.Email(); ok {
		_spec.SetField(invitetoken.FieldEmail, field.TypeString, value)
	}
	if value, ok := ituo.mutation.InvitedBy(); ok {
		_spec.SetField(invitetoken.FieldInvitedBy, field.TypeUUID, value)
	}
	if value, ok := ituo.mutation.ExpiresAt(); ok {
		_spec.SetField(invitetoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := ituo.mutation.AcceptedAt(); ok {
		_spec.SetField(invitetoken.FieldAcceptedAt, field.TypeTime, value)
	}
	if ituo.mutation.AcceptedAtCleared() {
		_spec.ClearField(invitetoken.FieldAcceptedAt, field.TypeTime)
	}
	_node = &InviteToken{config: ituo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ituo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitetoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ituo.mutation.done = true
	return _node, nil
}
