// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/run"
)

// Run is the model entity for the Run schema.
type Run struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// AssetName holds the value of the "asset_name" field.
	AssetName string `json:"asset_name,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// Trigger holds the value of the "trigger" field.
	Trigger string `json:"trigger,omitempty"`
	// TriggeredBy holds the value of the "triggered_by" field.
	TriggeredBy *uuid.UUID `json:"triggered_by,omitempty"`
	// ClaimedBy holds the value of the "claimed_by" field.
	ClaimedBy string `json:"claimed_by,omitempty"`
	// QueuedAt holds the value of the "queued_at" field.
	QueuedAt time.Time `json:"queued_at,omitempty"`
	// ClaimedAt holds the value of the "claimed_at" field.
	ClaimedAt *time.Time `json:"claimed_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// LastHeartbeat holds the value of the "last_heartbeat" field.
	LastHeartbeat *time.Time `json:"last_heartbeat,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// PartitionKey holds the value of the "partition_key" field.
	PartitionKey string `json:"partition_key,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority string `json:"priority,omitempty"`
	// BackfillID holds the value of the "backfill_id" field.
	BackfillID   *uuid.UUID `json:"backfill_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Run) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case run.FieldTriggeredBy, run.FieldBackfillID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case run.FieldMetadata:
			values[i] = new([]byte)
		case run.FieldAssetName, run.FieldState, run.FieldTrigger, run.FieldClaimedBy, run.FieldErrorMessage, run.FieldPartitionKey, run.FieldPriority:
			values[i] = new(sql.NullString)
		case run.FieldQueuedAt, run.FieldClaimedAt, run.FieldStartedAt, run.FieldFinishedAt, run.FieldLastHeartbeat:
			values[i] = new(sql.NullTime)
		case run.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Run fields.
func (r *Run) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case run.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				r.ID = *value
			}
		case run.FieldAssetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_name", values[i])
			} else if value.Valid {
				r.AssetName = value.String
			}
		case run.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				r.State = value.String
			}
		case run.FieldTrigger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger", values[i])
			} else if value.Valid {
				r.Trigger = value.String
			}
		case run.FieldTriggeredBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field triggered_by", values[i])
			} else if value.Valid {
				r.TriggeredBy = new(uuid.UUID)
				*r.TriggeredBy = *value.S.(*uuid.UUID)
			}
		case run.FieldClaimedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field claimed_by", values[i])
			} else if value.Valid {
				r.ClaimedBy = value.String
			}
		case run.FieldQueuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field queued_at", values[i])
			} else if value.Valid {
				r.QueuedAt = value.Time
			}
		case run.FieldClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field claimed_at", values[i])
			} else if value.Valid {
				r.ClaimedAt = new(time.Time)
				*r.ClaimedAt = value.Time
			}
		case run.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				r.StartedAt = new(time.Time)
				*r.StartedAt = value.Time
			}
		case run.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				r.FinishedAt = new(time.Time)
				*r.FinishedAt = value.Time
			}
		case run.FieldLastHeartbeat:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_heartbeat", values[i])
			} else if value.Valid {
				r.LastHeartbeat = new(time.Time)
				*r.LastHeartbeat = value.Time
			}
		case run.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				r.ErrorMessage = value.String
			}
		case run.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &r.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case run.FieldPartitionKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field partition_key", values[i])
			} else if value.Valid {
				r.PartitionKey = value.String
			}
		case run.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				r.Priority = value.String
			}
		case run.FieldBackfillID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field backfill_id", values[i])
			} else if value.Valid {
				r.BackfillID = new(uuid.UUID)
				*r.BackfillID = *value.S.(*uuid.UUID)
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Run.
// This includes values selected through modifiers, order, etc.
func (r *Run) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// Update returns a builder for updating this Run.
// Note that you need to call Run.Unwrap() before calling this method if this Run
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Run) Update() *RunUpdateOne {
	return NewRunClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Run entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Run) Unwrap() *Run {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Run is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Run) String() string {
	var builder strings.Builder
	builder.WriteString("Run(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("asset_name=")
	builder.WriteString(r.AssetName)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(r.State)
	builder.WriteString(", ")
	builder.WriteString("trigger=")
	builder.WriteString(r.Trigger)
	builder.WriteString(", ")
	if v := r.TriggeredBy; v != nil {
		builder.WriteString("triggered_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("claimed_by=")
	builder.WriteString(r.ClaimedBy)
	builder.WriteString(", ")
	builder.WriteString("queued_at=")
	builder.WriteString(r.QueuedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := r.ClaimedAt; v != nil {
		builder.WriteString("claimed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := r.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := r.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := r.LastHeartbeat; v != nil {
		builder.WriteString("last_heartbeat=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(r.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", r.Metadata))
	builder.WriteString(", ")
	builder.WriteString("partition_key=")
	builder.WriteString(r.PartitionKey)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(r.Priority)
	builder.WriteString(", ")
	if v := r.BackfillID; v != nil {
		builder.WriteString("backfill_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Runs is a parsable slice of Run.
type Runs []*Run
