// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
	"github.com/kanpon/data-governance/internal/storage/ent/runstep"
)

// RunStepUpdate is the builder for updating RunStep entities.
type RunStepUpdate struct {
	config
	hooks    []Hook
	mutation *RunStepMutation
}

// Where appends a list predicates to the RunStepUpdate builder.
func (rsu *RunStepUpdate) Where(ps ...predicate.RunStep) *RunStepUpdate {
	rsu.mutation.Where(ps...)
	return rsu
}

// SetState sets the "state" field.
func (rsu *RunStepUpdate) SetState(s string) *RunStepUpdate {
	rsu.mutation.SetState(s)
	return rsu
}

// SetNillableState sets the "state" field if the given value is not nil.
func (rsu *RunStepUpdate) SetNillableState(s *string) *RunStepUpdate {
	if s != nil {
		rsu.SetState(*s)
	}
	return rsu
}

// SetAttempt sets the "attempt" field.
func (rsu *RunStepUpdate) SetAttempt(i int) *RunStepUpdate {
	rsu.mutation.ResetAttempt()
	rsu.mutation.SetAttempt(i)
	return rsu
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (rsu *RunStepUpdate) SetNillableAttempt(i *int) *RunStepUpdate {
	if i != nil {
		rsu.SetAttempt(*i)
	}
	return rsu
}

// AddAttempt adds i to the "attempt" field.
func (rsu *RunStepUpdate) AddAttempt(i int) *RunStepUpdate {
	rsu.mutation.AddAttempt(i)
	return rsu
}

// SetStartedAt sets the "started_at" field.
func (rsu *RunStepUpdate) SetStartedAt(t time.Time) *RunStepUpdate {
	rsu.mutation.SetStartedAt(t)
	return rsu
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (rsu *RunStepUpdate) SetNillableStartedAt(t *time.Time) *RunStepUpdate {
	if t != nil {
		rsu.SetStartedAt(*t)
	}
	return rsu
}

// ClearStartedAt clears the value of the "started_at" field.
func (rsu *RunStepUpdate) ClearStartedAt() *RunStepUpdate {
	rsu.mutation.ClearStartedAt()
	return rsu
}

// SetFinishedAt sets the "finished_at" field.
func (rsu *RunStepUpdate) SetFinishedAt(t time.Time) *RunStepUpdate {
	rsu.mutation.SetFinishedAt(t)
	return rsu
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (rsu *RunStepUpdate) SetNillableFinishedAt(t *time.Time) *RunStepUpdate {
	if t != nil {
		rsu.SetFinishedAt(*t)
	}
	return rsu
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (rsu *RunStepUpdate) ClearFinishedAt() *RunStepUpdate {
	rsu.mutation.ClearFinishedAt()
	return rsu
}

// SetRowsWritten sets the "rows_written" field.
func (rsu *RunStepUpdate) SetRowsWritten(i int64) *RunStepUpdate {
	rsu.mutation.ResetRowsWritten()
	rsu.mutation.SetRowsWritten(i)
	return rsu
}

// SetNillableRowsWritten sets the "rows_written" field if the given value is not nil.
func (rsu *RunStepUpdate) SetNillableRowsWritten(i *int64) *RunStepUpdate {
	if i != nil {
		rsu.SetRowsWritten(*i)
	}
	return rsu
}

// AddRowsWritten adds i to the "rows_written" field.
func (rsu *RunStepUpdate) AddRowsWritten(i int64) *RunStepUpdate {
	rsu.mutation.AddRowsWritten(i)
	return rsu
}

// SetErrorMessage sets the "error_message" field.
func (rsu *RunStepUpdate) SetErrorMessage(s string) *RunStepUpdate {
	rsu.mutation.SetErrorMessage(s)
	return rsu
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (rsu *RunStepUpdate) SetNillableErrorMessage(s *string) *RunStepUpdate {
	if s != nil {
		rsu.SetErrorMessage(*s)
	}
	return rsu
}

// ClearErrorMessage clears the value of the "error_message" field.
func (rsu *RunStepUpdate) ClearErrorMessage() *RunStepUpdate {
	rsu.mutation.ClearErrorMessage()
	return rsu
}

// SetMetadata sets the "metadata" field.
func (rsu *RunStepUpdate) SetMetadata(m map[string]interface{}) *RunStepUpdate {
	rsu.mutation.SetMetadata(m)
	return rsu
}

// ClearMetadata clears the value of the "metadata" field.
func (rsu *RunStepUpdate) ClearMetadata() *RunStepUpdate {
	rsu.mutation.ClearMetadata()
	return rsu
}

// Mutation returns the RunStepMutation object of the builder.
func (rsu *RunStepUpdate) Mutation() *RunStepMutation {
	return rsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rsu *RunStepUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, rsu.sqlSave, rsu.mutation, rsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rsu *RunStepUpdate) SaveX(ctx context.Context) int {
	affected, err := rsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rsu *RunStepUpdate) Exec(ctx context.Context) error {
	_, err := rsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rsu *RunStepUpdate) ExecX(ctx context.Context) {
	if err := rsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rsu *RunStepUpdate) check() error {
	if v, ok := rsu.mutation.State(); ok {
		if err := runstep.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "RunStep.state": %w`, err)}
		}
	}
	return nil
}

func (rsu *RunStepUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := rsu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(runstep.Table, runstep.Columns, sqlgraph.NewFieldSpec(runstep.FieldID, field.TypeUUID))
	if ps := rsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rsu.mutation.State(); ok {
		_spec.SetField(runstep.FieldState, field.TypeString, value)
	}
	if value, ok := rsu.mutation.Attempt(); ok {
		_spec.SetField(runstep.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := rsu.mutation.AddedAttempt(); ok {
		_spec.AddField(runstep.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := rsu.mutation.StartedAt(); ok {
		_spec.SetField(runstep.FieldStartedAt, field.TypeTime, value)
	}
	if rsu.mutation.StartedAtCleared() {
		_spec.ClearField(runstep.FieldStartedAt, field.TypeTime)
	}
	if value, ok := rsu.mutation.FinishedAt(); ok {
		_spec.SetField(runstep.FieldFinishedAt, field.TypeTime, value)
	}
	if rsu.mutation.FinishedAtCleared() {
		_spec.ClearField(runstep.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := rsu.mutation.RowsWritten(); ok {
		_spec.SetField(runstep.FieldRowsWritten, field.TypeInt64, value)
	}
	if value, ok := rsu.mutation.AddedRowsWritten(); ok {
		_spec.AddField(runstep.FieldRowsWritten, field.TypeInt64, value)
	}
	if value, ok := rsu.mutation.ErrorMessage(); ok {
		_spec.SetField(runstep.FieldErrorMessage, field.TypeString, value)
	}
	if rsu.mutation.ErrorMessageCleared() {
		_spec.ClearField(runstep.FieldErrorMessage, field.TypeString)
	}
	if value, ok := rsu.mutation.Metadata(); ok {
		_spec.SetField(runstep.FieldMetadata, field.TypeJSON, value)
	}
	if rsu.mutation.MetadataCleared() {
		_spec.ClearField(runstep.FieldMetadata, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runstep.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rsu.mutation.done = true
	return n, nil
}

// RunStepUpdateOne is the builder for updating a single RunStep entity.
type RunStepUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RunStepMutation
}

// SetState sets the "state" field.
func (rsuo *RunStepUpdateOne) SetState(s string) *RunStepUpdateOne {
	rsuo.mutation.SetState(s)
	return rsuo
}

// SetNillableState sets the "state" field if the given value is not nil.
func (rsuo *RunStepUpdateOne) SetNillableState(s *string) *RunStepUpdateOne {
	if s != nil {
		rsuo.SetState(*s)
	}
	return rsuo
}

// SetAttempt sets the "attempt" field.
func (rsuo *RunStepUpdateOne) SetAttempt(i int) *RunStepUpdateOne {
	rsuo.mutation.ResetAttempt()
	rsuo.mutation.SetAttempt(i)
	return rsuo
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (rsuo *RunStepUpdateOne) SetNillableAttempt(i *int) *RunStepUpdateOne {
	if i != nil {
		rsuo.SetAttempt(*i)
	}
	return rsuo
}

// AddAttempt adds i to the "attempt" field.
func (rsuo *RunStepUpdateOne) AddAttempt(i int) *RunStepUpdateOne {
	rsuo.mutation.AddAttempt(i)
	return rsuo
}

// SetStartedAt sets the "started_at" field.
func (rsuo *RunStepUpdateOne) SetStartedAt(t time.Time) *RunStepUpdateOne {
	rsuo.mutation.SetStartedAt(t)
	return rsuo
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (rsuo *RunStepUpdateOne) SetNillableStartedAt(t *time.Time) *RunStepUpdateOne {
	if t != nil {
		rsuo.SetStartedAt(*t)
	}
	return rsuo
}

// ClearStartedAt clears the value of the "started_at" field.
func (rsuo *RunStepUpdateOne) ClearStartedAt() *RunStepUpdateOne {
	rsuo.mutation.ClearStartedAt()
	return rsuo
}

// SetFinishedAt sets the "finished_at" field.
func (rsuo *RunStepUpdateOne) SetFinishedAt(t time.Time) *RunStepUpdateOne {
	rsuo.mutation.SetFinishedAt(t)
	return rsuo
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (rsuo *RunStepUpdateOne) SetNillableFinishedAt(t *time.Time) *RunStepUpdateOne {
	if t != nil {
		rsuo.SetFinishedAt(*t)
	}
	return rsuo
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (rsuo *RunStepUpdateOne) ClearFinishedAt() *RunStepUpdateOne {
	rsuo.mutation.ClearFinishedAt()
	return rsuo
}

// SetRowsWritten sets the "rows_written" field.
func (rsuo *RunStepUpdateOne) SetRowsWritten(i int64) *RunStepUpdateOne {
	rsuo.mutation.ResetRowsWritten()
	rsuo.mutation.SetRowsWritten(i)
	return rsuo
}

// SetNillableRowsWritten sets the "rows_written" field if the given value is not nil.
func (rsuo *RunStepUpdateOne) SetNillableRowsWritten(i *int64) *RunStepUpdateOne {
	if i != nil {
		rsuo.SetRowsWritten(*i)
	}
	return rsuo
}

// AddRowsWritten adds i to the "rows_written" field.
func (rsuo *RunStepUpdateOne) AddRowsWritten(i int64) *RunStepUpdateOne {
	rsuo.mutation.AddRowsWritten(i)
	return rsuo
}

// SetErrorMessage sets the "error_message" field.
func (rsuo *RunStepUpdateOne) SetErrorMessage(s string) *RunStepUpdateOne {
	rsuo.mutation.SetErrorMessage(s)
	return rsuo
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (rsuo *RunStepUpdateOne) SetNillableErrorMessage(s *string) *RunStepUpdateOne {
	if s != nil {
		rsuo.SetErrorMessage(*s)
	}
	return rsuo
}

// ClearErrorMessage clears the value of the "error_message" field.
func (rsuo *RunStepUpdateOne) ClearErrorMessage() *RunStepUpdateOne {
	rsuo.mutation.ClearErrorMessage()
	return rsuo
}

// SetMetadata sets the "metadata" field.
func (rsuo *RunStepUpdateOne) SetMetadata(m map[string]interface{}) *RunStepUpdateOne {
	rsuo.mutation.SetMetadata(m)
	return rsuo
}

// ClearMetadata clears the value of the "metadata" field.
func (rsuo *RunStepUpdateOne) ClearMetadata() *RunStepUpdateOne {
	rsuo.mutation.ClearMetadata()
	return rsuo
}

// Mutation returns the RunStepMutation object of the builder.
func (rsuo *RunStepUpdateOne) Mutation() *RunStepMutation {
	return rsuo.mutation
}

// Where appends a list predicates to the RunStepUpdate builder.
func (rsuo *RunStepUpdateOne) Where(ps ...predicate.RunStep) *RunStepUpdateOne {
	rsuo.mutation.Where(ps...)
	return rsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rsuo *RunStepUpdateOne) Select(field string, fields ...string) *RunStepUpdateOne {
	rsuo.fields = append([]string{field}, fields...)
	return rsuo
}

// Save executes the query and returns the updated RunStep entity.
func (rsuo *RunStepUpdateOne) Save(ctx context.Context) (*RunStep, error) {
	return withHooks(ctx, rsuo.sqlSave, rsuo.mutation, rsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rsuo *RunStepUpdateOne) SaveX(ctx context.Context) *RunStep {
	node, err := rsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rsuo *RunStepUpdateOne) Exec(ctx context.Context) error {
	_, err := rsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rsuo *RunStepUpdateOne) ExecX(ctx context.Context) {
	if err := rsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rsuo *RunStepUpdateOne) check() error {
	if v, ok := rsuo.mutation.State(); ok {
		if err := runstep.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "RunStep.state": %w`, err)}
		}
	}
	return nil
}

func (rsuo *RunStepUpdateOne) sqlSave(ctx context.Context) (_node *RunStep, err error) {
	if err := rsuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(runstep.Table, runstep.Columns, sqlgraph.NewFieldSpec(runstep.FieldID, field.TypeUUID))
	id, ok := rsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RunStep.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, runstep.FieldID)
		for _, f := range fields {
			if !runstep.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != runstep.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rsuo.mutation.State(); ok {
		_spec.SetField(runstep.FieldState, field.TypeString, value)
	}
	if value, ok := rsuo.mutation.Attempt(); ok {
		_spec.SetField(runstep.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := rsuo.mutation.AddedAttempt(); ok {
		_spec.AddField(runstep.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := rsuo.mutation.StartedAt(); ok {
		_spec.SetField(runstep.FieldStartedAt, field.TypeTime, value)
	}
	if rsuo.mutation.StartedAtCleared() {
		_spec.ClearField(runstep.FieldStartedAt, field.TypeTime)
	}
	if value, ok := rsuo.mutation.FinishedAt(); ok {
		_spec.SetField(runstep.FieldFinishedAt, field.TypeTime, value)
	}
	if rsuo.mutation.FinishedAtCleared() {
		_spec.ClearField(runstep.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := rsuo.mutation.RowsWritten(); ok {
		_spec.SetField(runstep.FieldRowsWritten, field.TypeInt64, value)
	}
	if value, ok := rsuo.mutation.AddedRowsWritten(); ok {
		_spec.AddField(runstep.FieldRowsWritten, field.TypeInt64, value)
	}
	if value, ok := rsuo.mutation.ErrorMessage(); ok {
		_spec.SetField(runstep.FieldErrorMessage, field.TypeString, value)
	}
	if rsuo.mutation.ErrorMessageCleared() {
		_spec.ClearField(runstep.FieldErrorMessage, field.TypeString)
	}
	if value, ok := rsuo.mutation.Metadata(); ok {
		_spec.SetField(runstep.FieldMetadata, field.TypeJSON, value)
	}
	if rsuo.mutation.MetadataCleared() {
		_spec.ClearField(runstep.FieldMetadata, field.TypeJSON)
	}
	_node = &RunStep{config: rsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runstep.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rsuo.mutation.done = true
	return _node, nil
}
