// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/runstep"
)

// RunStep is the model entity for the RunStep schema.
type RunStep struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID uuid.UUID `json:"run_id,omitempty"`
	// AssetName holds the value of the "asset_name" field.
	AssetName string `json:"asset_name,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// Attempt holds the value of the "attempt" field.
	Attempt int `json:"attempt,omitempty"`
	// TopoOrder holds the value of the "topo_order" field.
	TopoOrder int `json:"topo_order,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// RowsWritten holds the value of the "rows_written" field.
	RowsWritten int64 `json:"rows_written,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata     map[string]interface{} `json:"metadata,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RunStep) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case runstep.FieldMetadata:
			values[i] = new([]byte)
		case runstep.FieldAttempt, runstep.FieldTopoOrder, runstep.FieldRowsWritten:
			values[i] = new(sql.NullInt64)
		case runstep.FieldAssetName, runstep.FieldState, runstep.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case runstep.FieldStartedAt, runstep.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		case runstep.FieldID, runstep.FieldRunID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RunStep fields.
func (rs *RunStep) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case runstep.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				rs.ID = *value
			}
		case runstep.FieldRunID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value != nil {
				rs.RunID = *value
			}
		case runstep.FieldAssetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_name", values[i])
			} else if value.Valid {
				rs.AssetName = value.String
			}
		case runstep.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				rs.State = value.String
			}
		case runstep.FieldAttempt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt", values[i])
			} else if value.Valid {
				rs.Attempt = int(value.Int64)
			}
		case runstep.FieldTopoOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field topo_order", values[i])
			} else if value.Valid {
				rs.TopoOrder = int(value.Int64)
			}
		case runstep.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				rs.StartedAt = new(time.Time)
				*rs.StartedAt = value.Time
			}
		case runstep.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				rs.FinishedAt = new(time.Time)
				*rs.FinishedAt = value.Time
			}
		case runstep.FieldRowsWritten:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rows_written", values[i])
			} else if value.Valid {
				rs.RowsWritten = value.Int64
			}
		case runstep.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				rs.ErrorMessage = value.String
			}
		case runstep.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rs.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			rs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RunStep.
// This includes values selected through modifiers, order, etc.
func (rs *RunStep) Value(name string) (ent.Value, error) {
	return rs.selectValues.Get(name)
}

// Update returns a builder for updating this RunStep.
// Note that you need to call RunStep.Unwrap() before calling this method if this RunStep
// was returned from a transaction, and the transaction was committed or rolled back.
func (rs *RunStep) Update() *RunStepUpdateOne {
	return NewRunStepClient(rs.config).UpdateOne(rs)
}

// Unwrap unwraps the RunStep entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rs *RunStep) Unwrap() *RunStep {
	_tx, ok := rs.config.driver.(*txDriver)
	if !ok {
		panic("ent: RunStep is not a transactional entity")
	}
	rs.config.driver = _tx.drv
	return rs
}

// String implements the fmt.Stringer.
func (rs *RunStep) String() string {
	var builder strings.Builder
	builder.WriteString("RunStep(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rs.ID))
	builder.WriteString("run_id=")
	builder.WriteString(fmt.Sprintf("%v", rs.RunID))
	builder.WriteString(", ")
	builder.WriteString("asset_name=")
	builder.WriteString(rs.AssetName)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(rs.State)
	builder.WriteString(", ")
	builder.WriteString("attempt=")
	builder.WriteString(fmt.Sprintf("%v", rs.Attempt))
	builder.WriteString(", ")
	builder.WriteString("topo_order=")
	builder.WriteString(fmt.Sprintf("%v", rs.TopoOrder))
	builder.WriteString(", ")
	if v := rs.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := rs.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("rows_written=")
	builder.WriteString(fmt.Sprintf("%v", rs.RowsWritten))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(rs.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", rs.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// RunSteps is a parsable slice of RunStep.
type RunSteps []*RunStep
