// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/eventlog"
	"github.com/kanpon/data-governance/internal/storage/ent/invitetoken"
	"github.com/kanpon/data-governance/internal/storage/ent/schema"
	"github.com/kanpon/data-governance/internal/storage/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventlogFields := schema.EventLog{}.Fields()
	_ = eventlogFields
	// eventlogDescOccurredAt is the schema descriptor for occurred_at field.
	eventlogDescOccurredAt := eventlogFields[1].Descriptor()
	// eventlog.DefaultOccurredAt holds the default value on creation for the occurred_at field.
	eventlog.DefaultOccurredAt = eventlogDescOccurredAt.Default.(func() time.Time)
	// eventlogDescEventType is the schema descriptor for event_type field.
	eventlogDescEventType := eventlogFields[2].Descriptor()
	// eventlog.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	eventlog.EventTypeValidator = func() func(string) error {
		validators := eventlogDescEventType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(event_type string) error {
			for _, fn := range fns {
				if err := fn(event_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventlogDescResourceType is the schema descriptor for resource_type field.
	eventlogDescResourceType := eventlogFields[4].Descriptor()
	// eventlog.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	eventlog.ResourceTypeValidator = func() func(string) error {
		validators := eventlogDescResourceType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource_type string) error {
			for _, fn := range fns {
				if err := fn(resource_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventlogDescResourceID is the schema descriptor for resource_id field.
	eventlogDescResourceID := eventlogFields[5].Descriptor()
	// eventlog.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	eventlog.ResourceIDValidator = func() func(string) error {
		validators := eventlogDescResourceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource_id string) error {
			for _, fn := range fns {
				if err := fn(resource_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventlogDescID is the schema descriptor for id field.
	eventlogDescID := eventlogFields[0].Descriptor()
	// eventlog.DefaultID holds the default value on creation for the id field.
	eventlog.DefaultID = eventlogDescID.Default.(func() uuid.UUID)
	invitetokenFields := schema.InviteToken{}.Fields()
	_ = invitetokenFields
	// invitetokenDescTokenHash is the schema descriptor for token_hash field.
	invitetokenDescTokenHash := invitetokenFields[1].Descriptor()
	// invitetoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	invitetoken.TokenHashValidator = func() func(string) error {
		validators := invitetokenDescTokenHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token_hash string) error {
			for _, fn := range fns {
				if err := fn(token_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// invitetokenDescEmail is the schema descriptor for email field.
	invitetokenDescEmail := invitetokenFields[2].Descriptor()
	// invitetoken.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	invitetoken.EmailValidator = func() func(string) error {
		validators := invitetokenDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// invitetokenDescCreatedAt is the schema descriptor for created_at field.
	invitetokenDescCreatedAt := invitetokenFields[6].Descriptor()
	// invitetoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	invitetoken.DefaultCreatedAt = invitetokenDescCreatedAt.Default.(func() time.Time)
	// invitetokenDescID is the schema descriptor for id field.
	invitetokenDescID := invitetokenFields[0].Descriptor()
	// invitetoken.DefaultID holds the default value on creation for the id field.
	invitetoken.DefaultID = invitetokenDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
