// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
	"github.com/kanpon/data-governance/internal/storage/ent/schemachange"
)

// SchemaChangeDelete is the builder for deleting a SchemaChange entity.
type SchemaChangeDelete struct {
	config
	hooks    []Hook
	mutation *SchemaChangeMutation
}

// Where appends a list predicates to the SchemaChangeDelete builder.
func (scd *SchemaChangeDelete) Where(ps ...predicate.SchemaChange) *SchemaChangeDelete {
	scd.mutation.Where(ps...)
	return scd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (scd *SchemaChangeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, scd.sqlExec, scd.mutation, scd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (scd *SchemaChangeDelete) ExecX(ctx context.Context) int {
	n, err := scd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (scd *SchemaChangeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(schemachange.Table, sqlgraph.NewFieldSpec(schemachange.FieldID, field.TypeUUID))
	if ps := scd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, scd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	scd.mutation.done = true
	return affected, err
}

// SchemaChangeDeleteOne is the builder for deleting a single SchemaChange entity.
type SchemaChangeDeleteOne struct {
	scd *SchemaChangeDelete
}

// Where appends a list predicates to the SchemaChangeDelete builder.
func (scdo *SchemaChangeDeleteOne) Where(ps ...predicate.SchemaChange) *SchemaChangeDeleteOne {
	scdo.scd.mutation.Where(ps...)
	return scdo
}

// Exec executes the deletion query.
func (scdo *SchemaChangeDeleteOne) Exec(ctx context.Context) error {
	n, err := scdo.scd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{schemachange.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (scdo *SchemaChangeDeleteOne) ExecX(ctx context.Context) {
	if err := scdo.Exec(ctx); err != nil {
		panic(err)
	}
}
