// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
	"github.com/kanpon/data-governance/internal/storage/ent/schemachange"
)

// SchemaChangeUpdate is the builder for updating SchemaChange entities.
type SchemaChangeUpdate struct {
	config
	hooks    []Hook
	mutation *SchemaChangeMutation
}

// Where appends a list predicates to the SchemaChangeUpdate builder.
func (scu *SchemaChangeUpdate) Where(ps ...predicate.SchemaChange) *SchemaChangeUpdate {
	scu.mutation.Where(ps...)
	return scu
}

// SetAcknowledgedAt sets the "acknowledged_at" field.
func (scu *SchemaChangeUpdate) SetAcknowledgedAt(t time.Time) *SchemaChangeUpdate {
	scu.mutation.SetAcknowledgedAt(t)
	return scu
}

// SetNillableAcknowledgedAt sets the "acknowledged_at" field if the given value is not nil.
func (scu *SchemaChangeUpdate) SetNillableAcknowledgedAt(t *time.Time) *SchemaChangeUpdate {
	if t != nil {
		scu.SetAcknowledgedAt(*t)
	}
	return scu
}

// ClearAcknowledgedAt clears the value of the "acknowledged_at" field.
func (scu *SchemaChangeUpdate) ClearAcknowledgedAt() *SchemaChangeUpdate {
	scu.mutation.ClearAcknowledgedAt()
	return scu
}

// SetAcknowledgedBy sets the "acknowledged_by" field.
func (scu *SchemaChangeUpdate) SetAcknowledgedBy(u uuid.UUID) *SchemaChangeUpdate {
	scu.mutation.SetAcknowledgedBy(u)
	return scu
}

// SetNillableAcknowledgedBy sets the "acknowledged_by" field if the given value is not nil.
func (scu *SchemaChangeUpdate) SetNillableAcknowledgedBy(u *uuid.UUID) *SchemaChangeUpdate {
	if u != nil {
		scu.SetAcknowledgedBy(*u)
	}
	return scu
}

// ClearAcknowledgedBy clears the value of the "acknowledged_by" field.
func (scu *SchemaChangeUpdate) ClearAcknowledgedBy() *SchemaChangeUpdate {
	scu.mutation.ClearAcknowledgedBy()
	return scu
}

// SetAcknowledgementReason sets the "acknowledgement_reason" field.
func (scu *SchemaChangeUpdate) SetAcknowledgementReason(s string) *SchemaChangeUpdate {
	scu.mutation.SetAcknowledgementReason(s)
	return scu
}

// SetNillableAcknowledgementReason sets the "acknowledgement_reason" field if the given value is not nil.
func (scu *SchemaChangeUpdate) SetNillableAcknowledgementReason(s *string) *SchemaChangeUpdate {
	if s != nil {
		scu.SetAcknowledgementReason(*s)
	}
	return scu
}

// ClearAcknowledgementReason clears the value of the "acknowledgement_reason" field.
func (scu *SchemaChangeUpdate) ClearAcknowledgementReason() *SchemaChangeUpdate {
	scu.mutation.ClearAcknowledgementReason()
	return scu
}

// Mutation returns the SchemaChangeMutation object of the builder.
func (scu *SchemaChangeUpdate) Mutation() *SchemaChangeMutation {
	return scu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (scu *SchemaChangeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, scu.sqlSave, scu.mutation, scu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (scu *SchemaChangeUpdate) SaveX(ctx context.Context) int {
	affected, err := scu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (scu *SchemaChangeUpdate) Exec(ctx context.Context) error {
	_, err := scu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scu *SchemaChangeUpdate) ExecX(ctx context.Context) {
	if err := scu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (scu *SchemaChangeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(schemachange.Table, schemachange.Columns, sqlgraph.NewFieldSpec(schemachange.FieldID, field.TypeUUID))
	if ps := scu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if scu.mutation.PrevVersionIDCleared() {
		_spec.ClearField(schemachange.FieldPrevVersionID, field.TypeUUID)
	}
	if scu.mutation.ColumnNameCleared() {
		_spec.ClearField(schemachange.FieldColumnName, field.TypeString)
	}
	if scu.mutation.PrevTypeCleared() {
		_spec.ClearField(schemachange.FieldPrevType, field.TypeString)
	}
	if scu.mutation.NewTypeCleared() {
		_spec.ClearField(schemachange.FieldNewType, field.TypeString)
	}
	if scu.mutation.PrevNullableCleared() {
		_spec.ClearField(schemachange.FieldPrevNullable, field.TypeBool)
	}
	if scu.mutation.NewNullableCleared() {
		_spec.ClearField(schemachange.FieldNewNullable, field.TypeBool)
	}
	if value, ok := scu.mutation.AcknowledgedAt(); ok {
		_spec.SetField(schemachange.FieldAcknowledgedAt, field.TypeTime, value)
	}
	if scu.mutation.AcknowledgedAtCleared() {
		_spec.ClearField(schemachange.FieldAcknowledgedAt, field.TypeTime)
	}
	if value, ok := scu.mutation.AcknowledgedBy(); ok {
		_spec.SetField(schemachange.FieldAcknowledgedBy, field.TypeUUID, value)
	}
	if scu.mutation.AcknowledgedByCleared() {
		_spec.ClearField(schemachange.FieldAcknowledgedBy, field.TypeUUID)
	}
	if value, ok := scu.mutation.AcknowledgementReason(); ok {
		_spec.SetField(schemachange.FieldAcknowledgementReason, field.TypeString, value)
	}
	if scu.mutation.AcknowledgementReasonCleared() {
		_spec.ClearField(schemachange.FieldAcknowledgementReason, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, scu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schemachange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	scu.mutation.done = true
	return n, nil
}

// SchemaChangeUpdateOne is the builder for updating a single SchemaChange entity.
type SchemaChangeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SchemaChangeMutation
}

// SetAcknowledgedAt sets the "acknowledged_at" field.
func (scuo *SchemaChangeUpdateOne) SetAcknowledgedAt(t time.Time) *SchemaChangeUpdateOne {
	scuo.mutation.SetAcknowledgedAt(t)
	return scuo
}

// SetNillableAcknowledgedAt sets the "acknowledged_at" field if the given value is not nil.
func (scuo *SchemaChangeUpdateOne) SetNillableAcknowledgedAt(t *time.Time) *SchemaChangeUpdateOne {
	if t != nil {
		scuo.SetAcknowledgedAt(*t)
	}
	return scuo
}

// ClearAcknowledgedAt clears the value of the "acknowledged_at" field.
func (scuo *SchemaChangeUpdateOne) ClearAcknowledgedAt() *SchemaChangeUpdateOne {
	scuo.mutation.ClearAcknowledgedAt()
	return scuo
}

// SetAcknowledgedBy sets the "acknowledged_by" field.
func (scuo *SchemaChangeUpdateOne) SetAcknowledgedBy(u uuid.UUID) *SchemaChangeUpdateOne {
	scuo.mutation.SetAcknowledgedBy(u)
	return scuo
}

// SetNillableAcknowledgedBy sets the "acknowledged_by" field if the given value is not nil.
func (scuo *SchemaChangeUpdateOne) SetNillableAcknowledgedBy(u *uuid.UUID) *SchemaChangeUpdateOne {
	if u != nil {
		scuo.SetAcknowledgedBy(*u)
	}
	return scuo
}

// ClearAcknowledgedBy clears the value of the "acknowledged_by" field.
func (scuo *SchemaChangeUpdateOne) ClearAcknowledgedBy() *SchemaChangeUpdateOne {
	scuo.mutation.ClearAcknowledgedBy()
	return scuo
}

// SetAcknowledgementReason sets the "acknowledgement_reason" field.
func (scuo *SchemaChangeUpdateOne) SetAcknowledgementReason(s string) *SchemaChangeUpdateOne {
	scuo.mutation.SetAcknowledgementReason(s)
	return scuo
}

// SetNillableAcknowledgementReason sets the "acknowledgement_reason" field if the given value is not nil.
func (scuo *SchemaChangeUpdateOne) SetNillableAcknowledgementReason(s *string) *SchemaChangeUpdateOne {
	if s != nil {
		scuo.SetAcknowledgementReason(*s)
	}
	return scuo
}

// ClearAcknowledgementReason clears the value of the "acknowledgement_reason" field.
func (scuo *SchemaChangeUpdateOne) ClearAcknowledgementReason() *SchemaChangeUpdateOne {
	scuo.mutation.ClearAcknowledgementReason()
	return scuo
}

// Mutation returns the SchemaChangeMutation object of the builder.
func (scuo *SchemaChangeUpdateOne) Mutation() *SchemaChangeMutation {
	return scuo.mutation
}

// Where appends a list predicates to the SchemaChangeUpdate builder.
func (scuo *SchemaChangeUpdateOne) Where(ps ...predicate.SchemaChange) *SchemaChangeUpdateOne {
	scuo.mutation.Where(ps...)
	return scuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (scuo *SchemaChangeUpdateOne) Select(field string, fields ...string) *SchemaChangeUpdateOne {
	scuo.fields = append([]string{field}, fields...)
	return scuo
}

// Save executes the query and returns the updated SchemaChange entity.
func (scuo *SchemaChangeUpdateOne) Save(ctx context.Context) (*SchemaChange, error) {
	return withHooks(ctx, scuo.sqlSave, scuo.mutation, scuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (scuo *SchemaChangeUpdateOne) SaveX(ctx context.Context) *SchemaChange {
	node, err := scuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (scuo *SchemaChangeUpdateOne) Exec(ctx context.Context) error {
	_, err := scuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scuo *SchemaChangeUpdateOne) ExecX(ctx context.Context) {
	if err := scuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (scuo *SchemaChangeUpdateOne) sqlSave(ctx context.Context) (_node *SchemaChange, err error) {
	_spec := sqlgraph.NewUpdateSpec(schemachange.Table, schemachange.Columns, sqlgraph.NewFieldSpec(schemachange.FieldID, field.TypeUUID))
	id, ok := scuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SchemaChange.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := scuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schemachange.FieldID)
		for _, f := range fields {
			if !schemachange.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schemachange.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := scuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if scuo.mutation.PrevVersionIDCleared() {
		_spec.ClearField(schemachange.FieldPrevVersionID, field.TypeUUID)
	}
	if scuo.mutation.ColumnNameCleared() {
		_spec.ClearField(schemachange.FieldColumnName, field.TypeString)
	}
	if scuo.mutation.PrevTypeCleared() {
		_spec.ClearField(schemachange.FieldPrevType, field.TypeString)
	}
	if scuo.mutation.NewTypeCleared() {
		_spec.ClearField(schemachange.FieldNewType, field.TypeString)
	}
	if scuo.mutation.PrevNullableCleared() {
		_spec.ClearField(schemachange.FieldPrevNullable, field.TypeBool)
	}
	if scuo.mutation.NewNullableCleared() {
		_spec.ClearField(schemachange.FieldNewNullable, field.TypeBool)
	}
	if value, ok := scuo.mutation.AcknowledgedAt(); ok {
		_spec.SetField(schemachange.FieldAcknowledgedAt, field.TypeTime, value)
	}
	if scuo.mutation.AcknowledgedAtCleared() {
		_spec.ClearField(schemachange.FieldAcknowledgedAt, field.TypeTime)
	}
	if value, ok := scuo.mutation.AcknowledgedBy(); ok {
		_spec.SetField(schemachange.FieldAcknowledgedBy, field.TypeUUID, value)
	}
	if scuo.mutation.AcknowledgedByCleared() {
		_spec.ClearField(schemachange.FieldAcknowledgedBy, field.TypeUUID)
	}
	if value, ok := scuo.mutation.AcknowledgementReason(); ok {
		_spec.SetField(schemachange.FieldAcknowledgementReason, field.TypeString, value)
	}
	if scuo.mutation.AcknowledgementReasonCleared() {
		_spec.ClearField(schemachange.FieldAcknowledgementReason, field.TypeString)
	}
	_node = &SchemaChange{config: scuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, scuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schemachange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	scuo.mutation.done = true
	return _node, nil
}
