// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/schemachange"
)

// SchemaChange is the model entity for the SchemaChange schema.
type SchemaChange struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Asset holds the value of the "asset" field.
	Asset string `json:"asset,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID uuid.UUID `json:"run_id,omitempty"`
	// CodeHash holds the value of the "code_hash" field.
	CodeHash string `json:"code_hash,omitempty"`
	// PrevVersionID holds the value of the "prev_version_id" field.
	PrevVersionID *uuid.UUID `json:"prev_version_id,omitempty"`
	// NewVersionID holds the value of the "new_version_id" field.
	NewVersionID uuid.UUID `json:"new_version_id,omitempty"`
	// ChangeType holds the value of the "change_type" field.
	ChangeType string `json:"change_type,omitempty"`
	// ColumnName holds the value of the "column_name" field.
	ColumnName string `json:"column_name,omitempty"`
	// PrevType holds the value of the "prev_type" field.
	PrevType string `json:"prev_type,omitempty"`
	// NewType holds the value of the "new_type" field.
	NewType string `json:"new_type,omitempty"`
	// PrevNullable holds the value of the "prev_nullable" field.
	PrevNullable *bool `json:"prev_nullable,omitempty"`
	// NewNullable holds the value of the "new_nullable" field.
	NewNullable *bool `json:"new_nullable,omitempty"`
	// IsBreaking holds the value of the "is_breaking" field.
	IsBreaking bool `json:"is_breaking,omitempty"`
	// ObservedAt holds the value of the "observed_at" field.
	ObservedAt time.Time `json:"observed_at,omitempty"`
	// AcknowledgedAt holds the value of the "acknowledged_at" field.
	AcknowledgedAt *time.Time `json:"acknowledged_at,omitempty"`
	// AcknowledgedBy holds the value of the "acknowledged_by" field.
	AcknowledgedBy *uuid.UUID `json:"acknowledged_by,omitempty"`
	// AcknowledgementReason holds the value of the "acknowledgement_reason" field.
	AcknowledgementReason string `json:"acknowledgement_reason,omitempty"`
	selectValues          sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SchemaChange) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case schemachange.FieldPrevVersionID, schemachange.FieldAcknowledgedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case schemachange.FieldPrevNullable, schemachange.FieldNewNullable, schemachange.FieldIsBreaking:
			values[i] = new(sql.NullBool)
		case schemachange.FieldAsset, schemachange.FieldCodeHash, schemachange.FieldChangeType, schemachange.FieldColumnName, schemachange.FieldPrevType, schemachange.FieldNewType, schemachange.FieldAcknowledgementReason:
			values[i] = new(sql.NullString)
		case schemachange.FieldObservedAt, schemachange.FieldAcknowledgedAt:
			values[i] = new(sql.NullTime)
		case schemachange.FieldID, schemachange.FieldRunID, schemachange.FieldNewVersionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SchemaChange fields.
func (sc *SchemaChange) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case schemachange.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				sc.ID = *value
			}
		case schemachange.FieldAsset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset", values[i])
			} else if value.Valid {
				sc.Asset = value.String
			}
		case schemachange.FieldRunID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value != nil {
				sc.RunID = *value
			}
		case schemachange.FieldCodeHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_hash", values[i])
			} else if value.Valid {
				sc.CodeHash = value.String
			}
		case schemachange.FieldPrevVersionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field prev_version_id", values[i])
			} else if value.Valid {
				sc.PrevVersionID = new(uuid.UUID)
				*sc.PrevVersionID = *value.S.(*uuid.UUID)
			}
		case schemachange.FieldNewVersionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field new_version_id", values[i])
			} else if value != nil {
				sc.NewVersionID = *value
			}
		case schemachange.FieldChangeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_type", values[i])
			} else if value.Valid {
				sc.ChangeType = value.String
			}
		case schemachange.FieldColumnName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field column_name", values[i])
			} else if value.Valid {
				sc.ColumnName = value.String
			}
		case schemachange.FieldPrevType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prev_type", values[i])
			} else if value.Valid {
				sc.PrevType = value.String
			}
		case schemachange.FieldNewType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field new_type", values[i])
			} else if value.Valid {
				sc.NewType = value.String
			}
		case schemachange.FieldPrevNullable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field prev_nullable", values[i])
			} else if value.Valid {
				sc.PrevNullable = new(bool)
				*sc.PrevNullable = value.Bool
			}
		case schemachange.FieldNewNullable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field new_nullable", values[i])
			} else if value.Valid {
				sc.NewNullable = new(bool)
				*sc.NewNullable = value.Bool
			}
		case schemachange.FieldIsBreaking:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_breaking", values[i])
			} else if value.Valid {
				sc.IsBreaking = value.Bool
			}
		case schemachange.FieldObservedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field observed_at", values[i])
			} else if value.Valid {
				sc.ObservedAt = value.Time
			}
		case schemachange.FieldAcknowledgedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field acknowledged_at", values[i])
			} else if value.Valid {
				sc.AcknowledgedAt = new(time.Time)
				*sc.AcknowledgedAt = value.Time
			}
		case schemachange.FieldAcknowledgedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field acknowledged_by", values[i])
			} else if value.Valid {
				sc.AcknowledgedBy = new(uuid.UUID)
				*sc.AcknowledgedBy = *value.S.(*uuid.UUID)
			}
		case schemachange.FieldAcknowledgementReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field acknowledgement_reason", values[i])
			} else if value.Valid {
				sc.AcknowledgementReason = value.String
			}
		default:
			sc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SchemaChange.
// This includes values selected through modifiers, order, etc.
func (sc *SchemaChange) Value(name string) (ent.Value, error) {
	return sc.selectValues.Get(name)
}

// Update returns a builder for updating this SchemaChange.
// Note that you need to call SchemaChange.Unwrap() before calling this method if this SchemaChange
// was returned from a transaction, and the transaction was committed or rolled back.
func (sc *SchemaChange) Update() *SchemaChangeUpdateOne {
	return NewSchemaChangeClient(sc.config).UpdateOne(sc)
}

// Unwrap unwraps the SchemaChange entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sc *SchemaChange) Unwrap() *SchemaChange {
	_tx, ok := sc.config.driver.(*txDriver)
	if !ok {
		panic("ent: SchemaChange is not a transactional entity")
	}
	sc.config.driver = _tx.drv
	return sc
}

// String implements the fmt.Stringer.
func (sc *SchemaChange) String() string {
	var builder strings.Builder
	builder.WriteString("SchemaChange(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sc.ID))
	builder.WriteString("asset=")
	builder.WriteString(sc.Asset)
	builder.WriteString(", ")
	builder.WriteString("run_id=")
	builder.WriteString(fmt.Sprintf("%v", sc.RunID))
	builder.WriteString(", ")
	builder.WriteString("code_hash=")
	builder.WriteString(sc.CodeHash)
	builder.WriteString(", ")
	if v := sc.PrevVersionID; v != nil {
		builder.WriteString("prev_version_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("new_version_id=")
	builder.WriteString(fmt.Sprintf("%v", sc.NewVersionID))
	builder.WriteString(", ")
	builder.WriteString("change_type=")
	builder.WriteString(sc.ChangeType)
	builder.WriteString(", ")
	builder.WriteString("column_name=")
	builder.WriteString(sc.ColumnName)
	builder.WriteString(", ")
	builder.WriteString("prev_type=")
	builder.WriteString(sc.PrevType)
	builder.WriteString(", ")
	builder.WriteString("new_type=")
	builder.WriteString(sc.NewType)
	builder.WriteString(", ")
	if v := sc.PrevNullable; v != nil {
		builder.WriteString("prev_nullable=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := sc.NewNullable; v != nil {
		builder.WriteString("new_nullable=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_breaking=")
	builder.WriteString(fmt.Sprintf("%v", sc.IsBreaking))
	builder.WriteString(", ")
	builder.WriteString("observed_at=")
	builder.WriteString(sc.ObservedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := sc.AcknowledgedAt; v != nil {
		builder.WriteString("acknowledged_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := sc.AcknowledgedBy; v != nil {
		builder.WriteString("acknowledged_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("acknowledgement_reason=")
	builder.WriteString(sc.AcknowledgementReason)
	builder.WriteByte(')')
	return builder.String()
}

// SchemaChanges is a parsable slice of SchemaChange.
type SchemaChanges []*SchemaChange
