// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
	"github.com/kanpon/data-governance/internal/storage/ent/sensor"
)

// SensorUpdate is the builder for updating Sensor entities.
type SensorUpdate struct {
	config
	hooks    []Hook
	mutation *SensorMutation
}

// Where appends a list predicates to the SensorUpdate builder.
func (su *SensorUpdate) Where(ps ...predicate.Sensor) *SensorUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetMinIntervalSeconds sets the "min_interval_seconds" field.
func (su *SensorUpdate) SetMinIntervalSeconds(i int64) *SensorUpdate {
	su.mutation.ResetMinIntervalSeconds()
	su.mutation.SetMinIntervalSeconds(i)
	return su
}

// SetNillableMinIntervalSeconds sets the "min_interval_seconds" field if the given value is not nil.
func (su *SensorUpdate) SetNillableMinIntervalSeconds(i *int64) *SensorUpdate {
	if i != nil {
		su.SetMinIntervalSeconds(*i)
	}
	return su
}

// AddMinIntervalSeconds adds i to the "min_interval_seconds" field.
func (su *SensorUpdate) AddMinIntervalSeconds(i int64) *SensorUpdate {
	su.mutation.AddMinIntervalSeconds(i)
	return su
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (su *SensorUpdate) SetLastEvaluatedAt(t time.Time) *SensorUpdate {
	su.mutation.SetLastEvaluatedAt(t)
	return su
}

// SetNillableLastEvaluatedAt sets the "last_evaluated_at" field if the given value is not nil.
func (su *SensorUpdate) SetNillableLastEvaluatedAt(t *time.Time) *SensorUpdate {
	if t != nil {
		su.SetLastEvaluatedAt(*t)
	}
	return su
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (su *SensorUpdate) ClearLastEvaluatedAt() *SensorUpdate {
	su.mutation.ClearLastEvaluatedAt()
	return su
}

// SetLastFiredAt sets the "last_fired_at" field.
func (su *SensorUpdate) SetLastFiredAt(t time.Time) *SensorUpdate {
	su.mutation.SetLastFiredAt(t)
	return su
}

// SetNillableLastFiredAt sets the "last_fired_at" field if the given value is not nil.
func (su *SensorUpdate) SetNillableLastFiredAt(t *time.Time) *SensorUpdate {
	if t != nil {
		su.SetLastFiredAt(*t)
	}
	return su
}

// ClearLastFiredAt clears the value of the "last_fired_at" field.
func (su *SensorUpdate) ClearLastFiredAt() *SensorUpdate {
	su.mutation.ClearLastFiredAt()
	return su
}

// SetLastRunKey sets the "last_run_key" field.
func (su *SensorUpdate) SetLastRunKey(s string) *SensorUpdate {
	su.mutation.SetLastRunKey(s)
	return su
}

// SetNillableLastRunKey sets the "last_run_key" field if the given value is not nil.
func (su *SensorUpdate) SetNillableLastRunKey(s *string) *SensorUpdate {
	if s != nil {
		su.SetLastRunKey(*s)
	}
	return su
}

// ClearLastRunKey clears the value of the "last_run_key" field.
func (su *SensorUpdate) ClearLastRunKey() *SensorUpdate {
	su.mutation.ClearLastRunKey()
	return su
}

// SetCooldownUntil sets the "cooldown_until" field.
func (su *SensorUpdate) SetCooldownUntil(t time.Time) *SensorUpdate {
	su.mutation.SetCooldownUntil(t)
	return su
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (su *SensorUpdate) SetNillableCooldownUntil(t *time.Time) *SensorUpdate {
	if t != nil {
		su.SetCooldownUntil(*t)
	}
	return su
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (su *SensorUpdate) ClearCooldownUntil() *SensorUpdate {
	su.mutation.ClearCooldownUntil()
	return su
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (su *SensorUpdate) SetConsecutiveFailures(i int) *SensorUpdate {
	su.mutation.ResetConsecutiveFailures()
	su.mutation.SetConsecutiveFailures(i)
	return su
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (su *SensorUpdate) SetNillableConsecutiveFailures(i *int) *SensorUpdate {
	if i != nil {
		su.SetConsecutiveFailures(*i)
	}
	return su
}

// AddConsecutiveFailures adds i to the "consecutive_failures" field.
func (su *SensorUpdate) AddConsecutiveFailures(i int) *SensorUpdate {
	su.mutation.AddConsecutiveFailures(i)
	return su
}

// SetDisabledAt sets the "disabled_at" field.
func (su *SensorUpdate) SetDisabledAt(t time.Time) *SensorUpdate {
	su.mutation.SetDisabledAt(t)
	return su
}

// SetNillableDisabledAt sets the "disabled_at" field if the given value is not nil.
func (su *SensorUpdate) SetNillableDisabledAt(t *time.Time) *SensorUpdate {
	if t != nil {
		su.SetDisabledAt(*t)
	}
	return su
}

// ClearDisabledAt clears the value of the "disabled_at" field.
func (su *SensorUpdate) ClearDisabledAt() *SensorUpdate {
	su.mutation.ClearDisabledAt()
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SensorUpdate) SetUpdatedAt(t time.Time) *SensorUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// Mutation returns the SensorMutation object of the builder.
func (su *SensorUpdate) Mutation() *SensorMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SensorUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SensorUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SensorUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SensorUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SensorUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := sensor.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SensorUpdate) check() error {
	if v, ok := su.mutation.LastRunKey(); ok {
		if err := sensor.LastRunKeyValidator(v); err != nil {
			return &ValidationError{Name: "last_run_key", err: fmt.Errorf(`ent: validator failed for field "Sensor.last_run_key": %w`, err)}
		}
	}
	return nil
}

func (su *SensorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(sensor.Table, sensor.Columns, sqlgraph.NewFieldSpec(sensor.FieldID, field.TypeUUID))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.MinIntervalSeconds(); ok {
		_spec.SetField(sensor.FieldMinIntervalSeconds, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedMinIntervalSeconds(); ok {
		_spec.AddField(sensor.FieldMinIntervalSeconds, field.TypeInt64, value)
	}
	if value, ok := su.mutation.LastEvaluatedAt(); ok {
		_spec.SetField(sensor.FieldLastEvaluatedAt, field.TypeTime, value)
	}
	if su.mutation.LastEvaluatedAtCleared() {
		_spec.ClearField(sensor.FieldLastEvaluatedAt, field.TypeTime)
	}
	if value, ok := su.mutation.LastFiredAt(); ok {
		_spec.SetField(sensor.FieldLastFiredAt, field.TypeTime, value)
	}
	if su.mutation.LastFiredAtCleared() {
		_spec.ClearField(sensor.FieldLastFiredAt, field.TypeTime)
	}
	if value, ok := su.mutation.LastRunKey(); ok {
		_spec.SetField(sensor.FieldLastRunKey, field.TypeString, value)
	}
	if su.mutation.LastRunKeyCleared() {
		_spec.ClearField(sensor.FieldLastRunKey, field.TypeString)
	}
	if value, ok := su.mutation.CooldownUntil(); ok {
		_spec.SetField(sensor.FieldCooldownUntil, field.TypeTime, value)
	}
	if su.mutation.CooldownUntilCleared() {
		_spec.ClearField(sensor.FieldCooldownUntil, field.TypeTime)
	}
	if value, ok := su.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(sensor.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(sensor.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := su.mutation.DisabledAt(); ok {
		_spec.SetField(sensor.FieldDisabledAt, field.TypeTime, value)
	}
	if su.mutation.DisabledAtCleared() {
		_spec.ClearField(sensor.FieldDisabledAt, field.TypeTime)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(sensor.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sensor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SensorUpdateOne is the builder for updating a single Sensor entity.
type SensorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SensorMutation
}

// SetMinIntervalSeconds sets the "min_interval_seconds" field.
func (suo *SensorUpdateOne) SetMinIntervalSeconds(i int64) *SensorUpdateOne {
	suo.mutation.ResetMinIntervalSeconds()
	suo.mutation.SetMinIntervalSeconds(i)
	return suo
}

// SetNillableMinIntervalSeconds sets the "min_interval_seconds" field if the given value is not nil.
func (suo *SensorUpdateOne) SetNillableMinIntervalSeconds(i *int64) *SensorUpdateOne {
	if i != nil {
		suo.SetMinIntervalSeconds(*i)
	}
	return suo
}

// AddMinIntervalSeconds adds i to the "min_interval_seconds" field.
func (suo *SensorUpdateOne) AddMinIntervalSeconds(i int64) *SensorUpdateOne {
	suo.mutation.AddMinIntervalSeconds(i)
	return suo
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (suo *SensorUpdateOne) SetLastEvaluatedAt(t time.Time) *SensorUpdateOne {
	suo.mutation.SetLastEvaluatedAt(t)
	return suo
}

// SetNillableLastEvaluatedAt sets the "last_evaluated_at" field if the given value is not nil.
func (suo *SensorUpdateOne) SetNillableLastEvaluatedAt(t *time.Time) *SensorUpdateOne {
	if t != nil {
		suo.SetLastEvaluatedAt(*t)
	}
	return suo
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (suo *SensorUpdateOne) ClearLastEvaluatedAt() *SensorUpdateOne {
	suo.mutation.ClearLastEvaluatedAt()
	return suo
}

// SetLastFiredAt sets the "last_fired_at" field.
func (suo *SensorUpdateOne) SetLastFiredAt(t time.Time) *SensorUpdateOne {
	suo.mutation.SetLastFiredAt(t)
	return suo
}

// SetNillableLastFiredAt sets the "last_fired_at" field if the given value is not nil.
func (suo *SensorUpdateOne) SetNillableLastFiredAt(t *time.Time) *SensorUpdateOne {
	if t != nil {
		suo.SetLastFiredAt(*t)
	}
	return suo
}

// ClearLastFiredAt clears the value of the "last_fired_at" field.
func (suo *SensorUpdateOne) ClearLastFiredAt() *SensorUpdateOne {
	suo.mutation.ClearLastFiredAt()
	return suo
}

// SetLastRunKey sets the "last_run_key" field.
func (suo *SensorUpdateOne) SetLastRunKey(s string) *SensorUpdateOne {
	suo.mutation.SetLastRunKey(s)
	return suo
}

// SetNillableLastRunKey sets the "last_run_key" field if the given value is not nil.
func (suo *SensorUpdateOne) SetNillableLastRunKey(s *string) *SensorUpdateOne {
	if s != nil {
		suo.SetLastRunKey(*s)
	}
	return suo
}

// ClearLastRunKey clears the value of the "last_run_key" field.
func (suo *SensorUpdateOne) ClearLastRunKey() *SensorUpdateOne {
	suo.mutation.ClearLastRunKey()
	return suo
}

// SetCooldownUntil sets the "cooldown_until" field.
func (suo *SensorUpdateOne) SetCooldownUntil(t time.Time) *SensorUpdateOne {
	suo.mutation.SetCooldownUntil(t)
	return suo
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (suo *SensorUpdateOne) SetNillableCooldownUntil(t *time.Time) *SensorUpdateOne {
	if t != nil {
		suo.SetCooldownUntil(*t)
	}
	return suo
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (suo *SensorUpdateOne) ClearCooldownUntil() *SensorUpdateOne {
	suo.mutation.ClearCooldownUntil()
	return suo
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (suo *SensorUpdateOne) SetConsecutiveFailures(i int) *SensorUpdateOne {
	suo.mutation.ResetConsecutiveFailures()
	suo.mutation.SetConsecutiveFailures(i)
	return suo
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (suo *SensorUpdateOne) SetNillableConsecutiveFailures(i *int) *SensorUpdateOne {
	if i != nil {
		suo.SetConsecutiveFailures(*i)
	}
	return suo
}

// AddConsecutiveFailures adds i to the "consecutive_failures" field.
func (suo *SensorUpdateOne) AddConsecutiveFailures(i int) *SensorUpdateOne {
	suo.mutation.AddConsecutiveFailures(i)
	return suo
}

// SetDisabledAt sets the "disabled_at" field.
func (suo *SensorUpdateOne) SetDisabledAt(t time.Time) *SensorUpdateOne {
	suo.mutation.SetDisabledAt(t)
	return suo
}

// SetNillableDisabledAt sets the "disabled_at" field if the given value is not nil.
func (suo *SensorUpdateOne) SetNillableDisabledAt(t *time.Time) *SensorUpdateOne {
	if t != nil {
		suo.SetDisabledAt(*t)
	}
	return suo
}

// ClearDisabledAt clears the value of the "disabled_at" field.
func (suo *SensorUpdateOne) ClearDisabledAt() *SensorUpdateOne {
	suo.mutation.ClearDisabledAt()
	return suo
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SensorUpdateOne) SetUpdatedAt(t time.Time) *SensorUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// Mutation returns the SensorMutation object of the builder.
func (suo *SensorUpdateOne) Mutation() *SensorMutation {
	return suo.mutation
}

// Where appends a list predicates to the SensorUpdate builder.
func (suo *SensorUpdateOne) Where(ps ...predicate.Sensor) *SensorUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SensorUpdateOne) Select(field string, fields ...string) *SensorUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Sensor entity.
func (suo *SensorUpdateOne) Save(ctx context.Context) (*Sensor, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SensorUpdateOne) SaveX(ctx context.Context) *Sensor {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SensorUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SensorUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SensorUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := sensor.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SensorUpdateOne) check() error {
	if v, ok := suo.mutation.LastRunKey(); ok {
		if err := sensor.LastRunKeyValidator(v); err != nil {
			return &ValidationError{Name: "last_run_key", err: fmt.Errorf(`ent: validator failed for field "Sensor.last_run_key": %w`, err)}
		}
	}
	return nil
}

func (suo *SensorUpdateOne) sqlSave(ctx context.Context) (_node *Sensor, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sensor.Table, sensor.Columns, sqlgraph.NewFieldSpec(sensor.FieldID, field.TypeUUID))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sensor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sensor.FieldID)
		for _, f := range fields {
			if !sensor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sensor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.MinIntervalSeconds(); ok {
		_spec.SetField(sensor.FieldMinIntervalSeconds, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedMinIntervalSeconds(); ok {
		_spec.AddField(sensor.FieldMinIntervalSeconds, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.LastEvaluatedAt(); ok {
		_spec.SetField(sensor.FieldLastEvaluatedAt, field.TypeTime, value)
	}
	if suo.mutation.LastEvaluatedAtCleared() {
		_spec.ClearField(sensor.FieldLastEvaluatedAt, field.TypeTime)
	}
	if value, ok := suo.mutation.LastFiredAt(); ok {
		_spec.SetField(sensor.FieldLastFiredAt, field.TypeTime, value)
	}
	if suo.mutation.LastFiredAtCleared() {
		_spec.ClearField(sensor.FieldLastFiredAt, field.TypeTime)
	}
	if value, ok := suo.mutation.LastRunKey(); ok {
		_spec.SetField(sensor.FieldLastRunKey, field.TypeString, value)
	}
	if suo.mutation.LastRunKeyCleared() {
		_spec.ClearField(sensor.FieldLastRunKey, field.TypeString)
	}
	if value, ok := suo.mutation.CooldownUntil(); ok {
		_spec.SetField(sensor.FieldCooldownUntil, field.TypeTime, value)
	}
	if suo.mutation.CooldownUntilCleared() {
		_spec.ClearField(sensor.FieldCooldownUntil, field.TypeTime)
	}
	if value, ok := suo.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(sensor.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(sensor.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := suo.mutation.DisabledAt(); ok {
		_spec.SetField(sensor.FieldDisabledAt, field.TypeTime, value)
	}
	if suo.mutation.DisabledAtCleared() {
		_spec.ClearField(sensor.FieldDisabledAt, field.TypeTime)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(sensor.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Sensor{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sensor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
