// Package snowflake_test provides unit-style tests using go-sqlmock to verify
// the SQL strings generated by the Snowflake connector.
//
// EMULATOR DECISION (D-CLAUDE-DISCRETION / T-02-05-04):
//
// The Snowflake Go ecosystem has no production-grade in-process emulator
// (verified at planning time — see .planning/phases/02-execution-engine/02-CONTEXT.md).
//
// This default test file uses DATA-DOG/go-sqlmock to prove:
//   - The Schema() method generates a SELECT against information_schema.columns
//     with the correct SCHEMA and TABLE parameters.
//   - The Read() method generates SELECT * FROM "DB"."SCHEMA"."TABLE" LIMIT N.
//   - The Write() method generates a parameterized INSERT.
//   - Ping() returns ConnectorName="snowflake" and APIVersion=connector.APIVersion.
//
// What this does NOT prove: round-trip data correctness against a real Snowflake
// account. That is validated by the nightly real-credentials job (see
// snowflake_real_creds_test.go) which runs only when SNOWFLAKE_DSN is set.
//
// The mock test is the source of truth for SQL correctness; the nightly job is
// the source of truth for end-to-end Snowflake behavior (T-02-05-04 mitigation).
package snowflake_test

import (
	"context"
	"regexp"
	"testing"

	sqlmock "github.com/DATA-DOG/go-sqlmock"

	"github.com/kanpon/data-governance/internal/connector"
	"github.com/kanpon/data-governance/internal/connector/firstparty/snowflake"
)

// TestSnowflake_CompileTimeAssertion verifies that Snowflake satisfies connector.Connector.
func TestSnowflake_CompileTimeAssertion(t *testing.T) {
	var _ connector.Connector = (*snowflake.Snowflake)(nil)
}

// TestSnowflake_Factory_MissingDSN verifies the factory returns ErrMissingDSN.
func TestSnowflake_Factory_MissingDSN(t *testing.T) {
	_, err := snowflake.Factory(map[string]interface{}{})
	if err == nil {
		t.Fatal("expected error for missing DSN, got nil")
	}
}

// TestSnowflake_Ping verifies Ping() returns ConnectorName="snowflake" and the correct APIVersion.
func TestSnowflake_Ping(t *testing.T) {
	// MonitorPingsOption must be enabled to use ExpectPing.
	db, mock, err := sqlmock.New(sqlmock.MonitorPingsOption(true))
	if err != nil {
		t.Fatalf("sqlmock.New: %v", err)
	}
	defer db.Close()

	// Expect a ping call (PingContext calls DB.PingContext which calls driver.Ping).
	mock.ExpectPing()

	c := snowflake.NewFromDB(db)
	resp, err := c.Ping(context.Background(), connector.PingRequest{})
	if err != nil {
		t.Fatalf("Ping: %v", err)
	}
	if resp.ConnectorName != "snowflake" {
		t.Errorf("ConnectorName = %q, want %q", resp.ConnectorName, "snowflake")
	}
	if resp.APIVersion != connector.APIVersion {
		t.Errorf("APIVersion = %q, want %q", resp.APIVersion, connector.APIVersion)
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("unfulfilled expectations: %v", err)
	}
}

// TestSnowflake_Schema verifies Schema() issues a SELECT against information_schema.columns
// with the correct SCHEMA and TABLE parameters derived from the asset identifier.
func TestSnowflake_Schema(t *testing.T) {
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("sqlmock.New: %v", err)
	}
	defer db.Close()

	rows := sqlmock.NewRows([]string{"column_name", "data_type", "is_nullable"}).
		AddRow("ID", "NUMBER", "NO").
		AddRow("EMAIL", "VARCHAR", "YES")

	// Schema query uses ? placeholders; expect SCHEMA and TABLE args.
	mock.ExpectQuery(regexp.QuoteMeta("SELECT column_name, data_type, is_nullable")).
		WithArgs("MYSCHEMA", "MYTABLE").
		WillReturnRows(rows)

	c := snowflake.NewFromDB(db)
	resp, err := c.Schema(context.Background(), connector.SchemaRequest{
		Asset: connector.AssetRef{Identifier: "MYDB.MYSCHEMA.MYTABLE"},
	})
	if err != nil {
		t.Fatalf("Schema: %v", err)
	}
	if len(resp.Columns) != 2 {
		t.Errorf("columns = %d, want 2", len(resp.Columns))
	}
	if resp.Columns[0].Name != "ID" {
		t.Errorf("first column = %q, want %q", resp.Columns[0].Name, "ID")
	}
	if resp.Columns[0].Nullable {
		t.Errorf("ID should be NOT NULL")
	}
	if !resp.Columns[1].Nullable {
		t.Errorf("EMAIL should be nullable")
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("unfulfilled expectations: %v", err)
	}
}

// TestSnowflake_Read verifies Read() generates SELECT * FROM "DB"."SCHEMA"."TABLE" LIMIT N.
func TestSnowflake_Read(t *testing.T) {
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("sqlmock.New: %v", err)
	}
	defer db.Close()

	rows := sqlmock.NewRows([]string{"id", "email"}).
		AddRow(int64(1), "alice@example.com").
		AddRow(int64(2), "bob@example.com")

	// Expect SELECT * FROM "MYDB"."MYSCHEMA"."MYTABLE" LIMIT 10
	mock.ExpectQuery(regexp.QuoteMeta(`SELECT * FROM "MYDB"."MYSCHEMA"."MYTABLE" LIMIT 10`)).
		WillReturnRows(rows)

	c := snowflake.NewFromDB(db)
	resp, err := c.Read(context.Background(), connector.ReadRequest{
		Asset: connector.AssetRef{Identifier: "MYDB.MYSCHEMA.MYTABLE"},
		Limit: 10,
	})
	if err != nil {
		t.Fatalf("Read: %v", err)
	}
	if len(resp.Rows) != 2 {
		t.Errorf("rows = %d, want 2", len(resp.Rows))
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("unfulfilled expectations: %v", err)
	}
}

// TestSnowflake_Write verifies Write() generates a parameterized INSERT statement.
func TestSnowflake_Write(t *testing.T) {
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("sqlmock.New: %v", err)
	}
	defer db.Close()

	// Expect any INSERT INTO "..." (...) VALUES (?,?)
	mock.ExpectExec(regexp.QuoteMeta(`INSERT INTO "MYDB"."MYSCHEMA"."MYTABLE"`)).
		WithArgs(int64(1), "alice@example.com").
		WillReturnResult(sqlmock.NewResult(1, 1))

	c := snowflake.NewFromDB(db)
	resp, err := c.Write(context.Background(), connector.WriteRequest{
		Asset: connector.AssetRef{Identifier: "MYDB.MYSCHEMA.MYTABLE"},
		Rows: []connector.Row{
			{Fields: map[string]any{"id": int64(1), "email": "alice@example.com"}},
		},
	})
	if err != nil {
		t.Fatalf("Write: %v", err)
	}
	if resp.RowsWritten != 1 {
		t.Errorf("RowsWritten = %d, want 1", resp.RowsWritten)
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("unfulfilled expectations: %v", err)
	}
}

// TestSnowflake_APIVersion verifies APIVersion() returns the correct value.
// APIVersion() does not touch the DB, so no expectations needed.
func TestSnowflake_APIVersion(t *testing.T) {
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("sqlmock.New: %v", err)
	}
	mock.ExpectClose()
	defer db.Close()

	c := snowflake.NewFromDB(db)
	if got := c.APIVersion(); got != connector.APIVersion {
		t.Errorf("APIVersion() = %q, want %q", got, connector.APIVersion)
	}
}

// TestSnowflake_Close_Idempotent verifies double-close is safe.
func TestSnowflake_Close_Idempotent(t *testing.T) {
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("sqlmock.New: %v", err)
	}
	// Expect the close call from the first Close().
	mock.ExpectClose()

	c := snowflake.NewFromDB(db)
	if err := c.Close(); err != nil {
		t.Fatalf("first Close: %v", err)
	}
	// Second close is a no-op (closed guard in snowflake.go) — no new DB call.
	if err := c.Close(); err != nil {
		t.Fatalf("second Close: %v", err)
	}
}
