// Code generated by ent, DO NOT EDIT.

package assetmetadata

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanpon/data-governance/internal/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLTE(FieldID, id))
}

// Asset applies equality check predicate on the "asset" field. It's identical to AssetEQ.
func Asset(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldAsset, v))
}

// ColumnName applies equality check predicate on the "column_name" field. It's identical to ColumnNameEQ.
func ColumnName(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldColumnName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldDescription, v))
}

// Owner applies equality check predicate on the "owner" field. It's identical to OwnerEQ.
func Owner(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldOwner, v))
}

// SetBy applies equality check predicate on the "set_by" field. It's identical to SetByEQ.
func SetBy(v uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldSetBy, v))
}

// SetAt applies equality check predicate on the "set_at" field. It's identical to SetAtEQ.
func SetAt(v time.Time) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldSetAt, v))
}

// AssetEQ applies the EQ predicate on the "asset" field.
func AssetEQ(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldAsset, v))
}

// AssetNEQ applies the NEQ predicate on the "asset" field.
func AssetNEQ(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNEQ(FieldAsset, v))
}

// AssetIn applies the In predicate on the "asset" field.
func AssetIn(vs ...string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldIn(FieldAsset, vs...))
}

// AssetNotIn applies the NotIn predicate on the "asset" field.
func AssetNotIn(vs ...string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNotIn(FieldAsset, vs...))
}

// AssetGT applies the GT predicate on the "asset" field.
func AssetGT(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGT(FieldAsset, v))
}

// AssetGTE applies the GTE predicate on the "asset" field.
func AssetGTE(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGTE(FieldAsset, v))
}

// AssetLT applies the LT predicate on the "asset" field.
func AssetLT(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLT(FieldAsset, v))
}

// AssetLTE applies the LTE predicate on the "asset" field.
func AssetLTE(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLTE(FieldAsset, v))
}

// AssetContains applies the Contains predicate on the "asset" field.
func AssetContains(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldContains(FieldAsset, v))
}

// AssetHasPrefix applies the HasPrefix predicate on the "asset" field.
func AssetHasPrefix(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldHasPrefix(FieldAsset, v))
}

// AssetHasSuffix applies the HasSuffix predicate on the "asset" field.
func AssetHasSuffix(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldHasSuffix(FieldAsset, v))
}

// AssetEqualFold applies the EqualFold predicate on the "asset" field.
func AssetEqualFold(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEqualFold(FieldAsset, v))
}

// AssetContainsFold applies the ContainsFold predicate on the "asset" field.
func AssetContainsFold(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldContainsFold(FieldAsset, v))
}

// ColumnNameEQ applies the EQ predicate on the "column_name" field.
func ColumnNameEQ(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldColumnName, v))
}

// ColumnNameNEQ applies the NEQ predicate on the "column_name" field.
func ColumnNameNEQ(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNEQ(FieldColumnName, v))
}

// ColumnNameIn applies the In predicate on the "column_name" field.
func ColumnNameIn(vs ...string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldIn(FieldColumnName, vs...))
}

// ColumnNameNotIn applies the NotIn predicate on the "column_name" field.
func ColumnNameNotIn(vs ...string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNotIn(FieldColumnName, vs...))
}

// ColumnNameGT applies the GT predicate on the "column_name" field.
func ColumnNameGT(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGT(FieldColumnName, v))
}

// ColumnNameGTE applies the GTE predicate on the "column_name" field.
func ColumnNameGTE(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGTE(FieldColumnName, v))
}

// ColumnNameLT applies the LT predicate on the "column_name" field.
func ColumnNameLT(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLT(FieldColumnName, v))
}

// ColumnNameLTE applies the LTE predicate on the "column_name" field.
func ColumnNameLTE(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLTE(FieldColumnName, v))
}

// ColumnNameContains applies the Contains predicate on the "column_name" field.
func ColumnNameContains(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldContains(FieldColumnName, v))
}

// ColumnNameHasPrefix applies the HasPrefix predicate on the "column_name" field.
func ColumnNameHasPrefix(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldHasPrefix(FieldColumnName, v))
}

// ColumnNameHasSuffix applies the HasSuffix predicate on the "column_name" field.
func ColumnNameHasSuffix(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldHasSuffix(FieldColumnName, v))
}

// ColumnNameIsNil applies the IsNil predicate on the "column_name" field.
func ColumnNameIsNil() predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldIsNull(FieldColumnName))
}

// ColumnNameNotNil applies the NotNil predicate on the "column_name" field.
func ColumnNameNotNil() predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNotNull(FieldColumnName))
}

// ColumnNameEqualFold applies the EqualFold predicate on the "column_name" field.
func ColumnNameEqualFold(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEqualFold(FieldColumnName, v))
}

// ColumnNameContainsFold applies the ContainsFold predicate on the "column_name" field.
func ColumnNameContainsFold(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldContainsFold(FieldColumnName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldContainsFold(FieldDescription, v))
}

// OwnerEQ applies the EQ predicate on the "owner" field.
func OwnerEQ(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldOwner, v))
}

// OwnerNEQ applies the NEQ predicate on the "owner" field.
func OwnerNEQ(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNEQ(FieldOwner, v))
}

// OwnerIn applies the In predicate on the "owner" field.
func OwnerIn(vs ...string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldIn(FieldOwner, vs...))
}

// OwnerNotIn applies the NotIn predicate on the "owner" field.
func OwnerNotIn(vs ...string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNotIn(FieldOwner, vs...))
}

// OwnerGT applies the GT predicate on the "owner" field.
func OwnerGT(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGT(FieldOwner, v))
}

// OwnerGTE applies the GTE predicate on the "owner" field.
func OwnerGTE(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGTE(FieldOwner, v))
}

// OwnerLT applies the LT predicate on the "owner" field.
func OwnerLT(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLT(FieldOwner, v))
}

// OwnerLTE applies the LTE predicate on the "owner" field.
func OwnerLTE(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLTE(FieldOwner, v))
}

// OwnerContains applies the Contains predicate on the "owner" field.
func OwnerContains(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldContains(FieldOwner, v))
}

// OwnerHasPrefix applies the HasPrefix predicate on the "owner" field.
func OwnerHasPrefix(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldHasPrefix(FieldOwner, v))
}

// OwnerHasSuffix applies the HasSuffix predicate on the "owner" field.
func OwnerHasSuffix(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldHasSuffix(FieldOwner, v))
}

// OwnerIsNil applies the IsNil predicate on the "owner" field.
func OwnerIsNil() predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldIsNull(FieldOwner))
}

// OwnerNotNil applies the NotNil predicate on the "owner" field.
func OwnerNotNil() predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNotNull(FieldOwner))
}

// OwnerEqualFold applies the EqualFold predicate on the "owner" field.
func OwnerEqualFold(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEqualFold(FieldOwner, v))
}

// OwnerContainsFold applies the ContainsFold predicate on the "owner" field.
func OwnerContainsFold(v string) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldContainsFold(FieldOwner, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNotNull(FieldTags))
}

// SetByEQ applies the EQ predicate on the "set_by" field.
func SetByEQ(v uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldSetBy, v))
}

// SetByNEQ applies the NEQ predicate on the "set_by" field.
func SetByNEQ(v uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNEQ(FieldSetBy, v))
}

// SetByIn applies the In predicate on the "set_by" field.
func SetByIn(vs ...uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldIn(FieldSetBy, vs...))
}

// SetByNotIn applies the NotIn predicate on the "set_by" field.
func SetByNotIn(vs ...uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNotIn(FieldSetBy, vs...))
}

// SetByGT applies the GT predicate on the "set_by" field.
func SetByGT(v uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGT(FieldSetBy, v))
}

// SetByGTE applies the GTE predicate on the "set_by" field.
func SetByGTE(v uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGTE(FieldSetBy, v))
}

// SetByLT applies the LT predicate on the "set_by" field.
func SetByLT(v uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLT(FieldSetBy, v))
}

// SetByLTE applies the LTE predicate on the "set_by" field.
func SetByLTE(v uuid.UUID) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLTE(FieldSetBy, v))
}

// SetAtEQ applies the EQ predicate on the "set_at" field.
func SetAtEQ(v time.Time) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldEQ(FieldSetAt, v))
}

// SetAtNEQ applies the NEQ predicate on the "set_at" field.
func SetAtNEQ(v time.Time) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNEQ(FieldSetAt, v))
}

// SetAtIn applies the In predicate on the "set_at" field.
func SetAtIn(vs ...time.Time) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldIn(FieldSetAt, vs...))
}

// SetAtNotIn applies the NotIn predicate on the "set_at" field.
func SetAtNotIn(vs ...time.Time) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldNotIn(FieldSetAt, vs...))
}

// SetAtGT applies the GT predicate on the "set_at" field.
func SetAtGT(v time.Time) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGT(FieldSetAt, v))
}

// SetAtGTE applies the GTE predicate on the "set_at" field.
func SetAtGTE(v time.Time) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldGTE(FieldSetAt, v))
}

// SetAtLT applies the LT predicate on the "set_at" field.
func SetAtLT(v time.Time) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLT(FieldSetAt, v))
}

// SetAtLTE applies the LTE predicate on the "set_at" field.
func SetAtLTE(v time.Time) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.FieldLTE(FieldSetAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AssetMetadata) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AssetMetadata) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AssetMetadata) predicate.AssetMetadata {
	return predicate.AssetMetadata(sql.NotPredicates(p))
}
