// Code generated by ent, DO NOT EDIT.

package assetversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the assetversion type in the database.
	Label = "asset_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAsset holds the string denoting the asset field in the database.
	FieldAsset = "asset"
	// FieldCodeHash holds the string denoting the code_hash field in the database.
	FieldCodeHash = "code_hash"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldColumnLineage holds the string denoting the column_lineage field in the database.
	FieldColumnLineage = "column_lineage"
	// FieldDriftStatus holds the string denoting the drift_status field in the database.
	FieldDriftStatus = "drift_status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the assetversion in the database.
	Table = "asset_versions"
)

// Columns holds all SQL columns for assetversion fields.
var Columns = []string{
	FieldID,
	FieldAsset,
	FieldCodeHash,
	FieldDescription,
	FieldOwner,
	FieldTags,
	FieldColumnLineage,
	FieldDriftStatus,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AssetValidator is a validator for the "asset" field. It is called by the builders before save.
	AssetValidator func(string) error
	// CodeHashValidator is a validator for the "code_hash" field. It is called by the builders before save.
	CodeHashValidator func(string) error
	// OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	OwnerValidator func(string) error
	// DefaultDriftStatus holds the default value on creation for the "drift_status" field.
	DefaultDriftStatus string
	// DriftStatusValidator is a validator for the "drift_status" field. It is called by the builders before save.
	DriftStatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the AssetVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAsset orders the results by the asset field.
func ByAsset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAsset, opts...).ToFunc()
}

// ByCodeHash orders the results by the code_hash field.
func ByCodeHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeHash, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByOwner orders the results by the owner field.
func ByOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwner, opts...).ToFunc()
}

// ByDriftStatus orders the results by the drift_status field.
func ByDriftStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDriftStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
